#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>

static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=0x%08lx\n",n,(unsigned long)h);ExitProcess(1);}}
static std::vector<unsigned char> read_file(const char*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<unsigned char>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES x{};x.Type=t;x.CreationNodeMask=x.VisibleNodeMask=1;return x;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC x{};x.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;x.Width=n;x.Height=1;x.DepthOrArraySize=1;x.MipLevels=1;x.SampleDesc.Count=1;x.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;x.Flags=f;return x;}
static ID3D12Resource* make(ID3D12Device*d,UINT64 n,D3D12_HEAP_TYPE ht,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){auto h=hp(ht);auto b=bd(n,f);ID3D12Resource*r=nullptr;ck("resource",d->CreateCommittedResource(&h,D3D12_HEAP_FLAG_NONE,&b,s,nullptr,IID_PPV_ARGS(&r)));return r;}
static void uav_barrier(ID3D12GraphicsCommandList*c,ID3D12Resource*r){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;b.UAV.pResource=r;c->ResourceBarrier(1,&b);}

int main(int ac,char**av){
 if(ac!=6){std::fprintf(stderr,"usage: %s input.f32 directml-output.f16 post.f32 packed-input.f16 iterations\n",av[0]);return 2;}auto input=read_file(av[1]),raw=read_file(av[2]);UINT iters=std::strtoul(av[5],nullptr,10);if((input.size()&3)||(raw.size()&1))return 2;UINT inCount=input.size()/4,outCount=raw.size()/2;
 IDXGIFactory6*f=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;DXGI_ADAPTER_DESC1 ad{};for(UINT i=0;;i++){IDXGIAdapter1*x=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&x))==DXGI_ERROR_NOT_FOUND)break;x->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(ad.Description,L"AMD")){a=x;break;}x->Release();}if(!a)return 3;ID3D12Device*d=nullptr;ck("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));
 const char*shader=R"(
StructuredBuffer<float> source:register(t0);ByteAddressBuffer raw:register(t1);RWByteAddressBuffer packed:register(u0);RWStructuredBuffer<float> post:register(u1);
float F(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}
[numthreads(64,1,1)]void pack_cs(uint3 id:SV_DispatchThreadID){uint i=id.x*2;if(i>=IN_COUNT)return;uint lo=f32tof16(source[i]),hi=i+1<IN_COUNT?f32tof16(source[i+1]):0;packed.Store(i*2,lo|(hi<<16));}
[numthreads(64,1,1)]void unpack_cs(uint3 id:SV_DispatchThreadID){uint i=id.x*2;if(i>=OUT_COUNT)return;uint v=raw.Load(i*2);post[i]=F(f16tof32(v&65535));if(i+1<OUT_COUNT)post[i+1]=F(f16tof32(v>>16));}
)";char defs[2][32];std::snprintf(defs[0],32,"%u",inCount);std::snprintf(defs[1],32,"%u",outCount);D3D_SHADER_MACRO macros[]={{"IN_COUNT",defs[0]},{"OUT_COUNT",defs[1]},{nullptr,nullptr}};ID3DBlob*bc[2]{},*err=nullptr;const char*entry[2]={"pack_cs","unpack_cs"};for(int i=0;i<2;i++)ck("compile",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,entry[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&bc[i],&err));
 D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,2,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,2,0,0,2}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr;ck("signature",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&err));ID3D12RootSignature*rs=nullptr;ck("root",d->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&rs)));ID3D12PipelineState*pso[2]{};for(int i=0;i<2;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={bc[i]->GetBufferPointer(),bc[i]->GetBufferSize()};ck("pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));}
 ID3D12Resource*src=make(d,input.size(),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ),*rawr=make(d,raw.size(),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ),*packed=make(d,(UINT64)inCount*2,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*post=make(d,(UINT64)outCount*4,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);void*p=nullptr;src->Map(0,nullptr,&p);std::memcpy(p,input.data(),input.size());src->Unmap(0,nullptr);rawr->Map(0,nullptr,&p);std::memcpy(p,raw.data(),raw.size());rawr->Unmap(0,nullptr);
 D3D12_DESCRIPTOR_HEAP_DESC hh{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,4,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;ck("heap",d->CreateDescriptorHeap(&hh,IID_PPV_ARGS(&heap)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Buffer.StructureByteStride=4;sv.Buffer.NumElements=inCount;d->CreateShaderResourceView(src,&sv,cpu);cpu.ptr+=step;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.StructureByteStride=0;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;sv.Buffer.NumElements=raw.size()/4;d->CreateShaderResourceView(rawr,&sv,cpu);cpu.ptr+=step;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Format=DXGI_FORMAT_R32_TYPELESS;uv.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;uv.Buffer.NumElements=(inCount+1)/2;d->CreateUnorderedAccessView(packed,nullptr,&uv,cpu);cpu.ptr+=step;uv.Format=DXGI_FORMAT_UNKNOWN;uv.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_NONE;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=outCount;d->CreateUnorderedAccessView(post,nullptr,&uv,cpu);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("allocator",d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*hs[]={heap};cl->SetDescriptorHeaps(1,hs);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());
 D3D12_QUERY_HEAP_DESC qhd{};qhd.Type=D3D12_QUERY_HEAP_TYPE_TIMESTAMP;qhd.Count=2;ID3D12QueryHeap*qh=nullptr;ck("query heap",d->CreateQueryHeap(&qhd,IID_PPV_ARGS(&qh)));ID3D12Resource*qrb=make(d,16,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,0);for(UINT i=0;i<iters;i++){cl->SetPipelineState(pso[0]);cl->Dispatch((inCount+127)/128,1,1);uav_barrier(cl,packed);cl->SetPipelineState(pso[1]);cl->Dispatch((outCount+127)/128,1,1);uav_barrier(cl,post);}cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,1);cl->ResolveQueryData(qh,D3D12_QUERY_TYPE_TIMESTAMP,0,2,qrb,0);
 D3D12_RESOURCE_BARRIER tr[2]{};ID3D12Resource*outs[2]={post,packed};for(int i=0;i<2;i++){tr[i].Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;tr[i].Transition.pResource=outs[i];tr[i].Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;tr[i].Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;tr[i].Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;}cl->ResourceBarrier(2,tr);ID3D12Resource*postrb=make(d,(UINT64)outCount*4,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST),*packrb=make(d,(UINT64)inCount*2,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);cl->CopyResource(postrb,post);cl->CopyResource(packrb,packed);ck("close",cl->Close());ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*fe=nullptr;ck("fence",d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));q->Signal(fe,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);fe->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);
 UINT64*t=nullptr;D3D12_RANGE qrng{0,16};qrb->Map(0,&qrng,(void**)&t);UINT64 freq=0;q->GetTimestampFrequency(&freq);double ms=1000.0*double(t[1]-t[0])/freq/iters;D3D12_RANGE pr{0,(SIZE_T)outCount*4};postrb->Map(0,&pr,&p);std::ofstream(av[3],std::ios::binary).write((char*)p,(UINT64)outCount*4);D3D12_RANGE ir{0,(SIZE_T)inCount*2};packrb->Map(0,&ir,&p);std::ofstream(av[4],std::ios::binary).write((char*)p,(UINT64)inCount*2);wprintf(L"adapter=%ls input_values=%u output_values=%u iterations=%u pack_plus_unpack_ms=%.6f\n",ad.Description,inCount,outCount,iters,ms);return 0;
}
