#include <cuda.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,CUresult r){if(!r)return;const char*s=nullptr;cuGetErrorString(r,&s);std::fprintf(stderr,"%s=%d %s\n",n,r,s?s:"?");std::exit(1);}
int main(){constexpr size_t A=2097152;ck("init",cuInit(0));CUdevice d;ck("dev",cuDeviceGet(&d,0));CUcontext c;ck("ctx",cuDevicePrimaryCtxRetain(&c,d));ck("set",cuCtxSetCurrent(c));CUmodule m;ck("module",cuModuleLoad(&m,"/tmp/dlssnr-cubins/dlssnr-05.cubin"));CUfunction f;ck("function",cuModuleGetFunction(&f,m,"cc_vit_1d_attention_fp8"));CUdeviceptr q,k,v,work,aux,out;for(auto*p:{&q,&k,&v,&work,&aux,&out}){ck("alloc",cuMemAlloc(p,A));ck("zero",cuMemsetD8(*p,0,A));}CUdeviceptr a4=aux+0x1800,a5=aux+0x1e00;uint64_t dims=8ull|(8ull<<32);unsigned char p[0x40]{};std::memcpy(p,&q,8);std::memcpy(p+8,&k,8);std::memcpy(p+16,&v,8);std::memcpy(p+24,&out,8);std::memcpy(p+32,&work,8);std::memcpy(p+40,&a4,8);std::memcpy(p+48,&a5,8);std::memcpy(p+56,&dims,8);void*args[]={p};const int qb[10]={0,1,3,4,5,9,10,11,12,13},kb[10]={0,1,2,4,5,9,10,11,12,13};unsigned char value=0;
 for(int qi=0;qi<10;qi++)for(int ki=0;ki<10;ki++){for(auto x:{q,k,v,out})ck("clear",cuMemsetD8(x,0,A));ck("q",cuMemsetD8(q+(1u<<qb[qi]),0x38,1));ck("k",cuMemsetD8(k+(1u<<kb[ki]),0x38,1));ck("v",cuMemsetD8(v,0x38,1));ck("launch",cuLaunchKernel(f,32,1,1,32,4,1,0,nullptr,args,nullptr));ck("sync",cuCtxSynchronize());ck("read",cuMemcpyDtoH(&value,out,1));std::printf("low,%d,%d,%u\n",qi,ki,(unsigned)value);}const int vb[10]={3,6,7,8,9,10,11,12,13,14},ob[10]={1,0,4,5,3,9,10,11,12,13},qt[5]={2,6,7,8,14},kt[5]={3,6,7,8,14},vt[5]={0,1,2,4,5},ot[5]={2,6,7,8,14};for(int qi=5;qi<10;qi++)for(int ki=5;ki<10;ki++){for(auto x:{q,k,v,out})ck("clear",cuMemsetD8(x,0,A));ck("q",cuMemsetD8(q+(1u<<qb[qi]),0x38,1));ck("k",cuMemsetD8(k+(1u<<kb[ki]),0x38,1));ck("v",cuMemsetD8(v+(1u<<vb[qi]),0x38,1));ck("launch",cuLaunchKernel(f,32,1,1,32,4,1,0,nullptr,args,nullptr));ck("sync",cuCtxSynchronize());ck("read",cuMemcpyDtoH(&value,out+(1u<<ob[qi]),1));std::printf("high,%d,%d,%u\n",qi-5,ki-5,(unsigned)value);}for(int qi=0;qi<5;qi++)for(int oi=0;oi<5;oi++){for(auto x:{q,k,v,out})ck("clear",cuMemsetD8(x,0,A));ck("q",cuMemsetD8(q+(1u<<qt[qi]),0x38,1));ck("k",cuMemsetD8(k,0x38,1));ck("v",cuMemsetD8(v,0x38,1));ck("launch",cuLaunchKernel(f,32,1,1,32,4,1,0,nullptr,args,nullptr));ck("sync",cuCtxSynchronize());ck("read",cuMemcpyDtoH(&value,out+(1u<<ot[oi]),1));std::printf("qout,%d,%d,%u\n",qi,oi,(unsigned)value);}for(int ki=0;ki<5;ki++)for(int vi=0;vi<5;vi++){for(auto x:{q,k,v,out})ck("clear",cuMemsetD8(x,0,A));ck("q",cuMemsetD8(q,0x38,1));ck("k",cuMemsetD8(k+(1u<<kt[ki]),0x38,1));ck("v",cuMemsetD8(v+(1u<<vt[vi]),0x38,1));ck("launch",cuLaunchKernel(f,32,1,1,32,4,1,0,nullptr,args,nullptr));ck("sync",cuCtxSynchronize());ck("read",cuMemcpyDtoH(&value,out,1));std::printf("kv,%d,%d,%u\n",ki,vi,(unsigned)value);}return 0;}
