#include <cuda.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,CUresult r){if(!r)return;const char*s=nullptr;cuGetErrorString(r,&s);std::fprintf(stderr,"%s=%d %s\n",n,r,s?s:"?");std::exit(1);}
static std::vector<unsigned char>rd(const char*p,size_t n){std::vector<unsigned char>x(n);std::ifstream f(p,std::ios::binary);if(!f||!f.read((char*)x.data(),n))std::exit(2);return x;}
int main(int ac,char**av){if(ac!=10){std::fprintf(stderr,"usage: %s arena off attention residual work aux output work-out aux-out\n",av[0]);return 2;}constexpr size_t A=2097152,WA=147719680;auto weights=rd(av[1],WA),hi=rd(av[3],A),hr=rd(av[4],A),hw=rd(av[5],A),ha=rd(av[6],A);ck("init",cuInit(0));CUdevice d;ck("dev",cuDeviceGet(&d,0));CUcontext c;ck("ctx",cuDevicePrimaryCtxRetain(&c,d));ck("set",cuCtxSetCurrent(c));CUmodule m;ck("module",cuModuleLoad(&m,"/tmp/dlssnr-cubins/dlssnr-05.cubin"));CUfunction f;ck("function",cuModuleGetFunction(&f,m,"cc_vit_1d_projection_fp8"));CUdeviceptr input,residual,out,work,aux,dw;for(auto*p:{&input,&residual,&out,&work,&aux}){ck("alloc",cuMemAlloc(p,A));ck("zero",cuMemsetD8(*p,0,A));}ck("wa",cuMemAlloc(&dw,WA));ck("weights",cuMemcpyHtoD(dw,weights.data(),WA));ck("input",cuMemcpyHtoD(input,hi.data(),A));ck("residual",cuMemcpyHtoD(residual,hr.data(),A));ck("work",cuMemcpyHtoD(work,hw.data(),A));ck("aux",cuMemcpyHtoD(aux,ha.data(),A));CUdeviceptr a5=aux+0x1e00,a20=aux+0x2800,a38=aux+0x2c00,wv=dw+std::strtoull(av[2],nullptr,0);uint64_t dims=8ull|(8ull<<32);unsigned char p[0x48]{};std::memcpy(p,&input,8);std::memcpy(p+8,&residual,8);std::memcpy(p+16,&out,8);std::memcpy(p+24,&wv,8);std::memcpy(p+32,&a20,8);std::memcpy(p+40,&work,8);std::memcpy(p+48,&a5,8);std::memcpy(p+56,&a38,8);std::memcpy(p+64,&dims,8);void*args[]={p};CUlaunchAttribute at{};at.id=CU_LAUNCH_ATTRIBUTE_CLUSTER_DIMENSION;at.value.clusterDim={1,1,4};CUlaunchConfig cfg{};cfg.gridDimX=8;cfg.gridDimY=1;cfg.gridDimZ=4;cfg.blockDimX=32;cfg.blockDimY=4;cfg.blockDimZ=1;cfg.attrs=&at;cfg.numAttrs=1;ck("launch",cuLaunchKernelEx(&cfg,f,args,nullptr));ck("sync",cuCtxSynchronize());std::vector<unsigned char>x(A);for(auto item:{std::pair<const char*,CUdeviceptr>{av[7],out},{av[8],work},{av[9],aux}}){ck("read",cuMemcpyDtoH(x.data(),item.second,A));std::ofstream(item.first,std::ios::binary).write((char*)x.data(),x.size());}return 0;}
