#include <cuda.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,CUresult r){if(r){const char*s=nullptr;cuGetErrorString(r,&s);std::fprintf(stderr,"%s=%d %s\n",n,r,s?s:"?");std::exit(1);}}
static std::vector<unsigned char>rd(const char*p,size_t n){std::vector<unsigned char>x(n);std::ifstream f(p,std::ios::binary);if(!f)std::exit(2);f.read((char*)x.data(),n);return x;}
int main(int ac,char**av){if(ac!=13&&ac!=14){std::fprintf(stderr,"usage: %s cubin symbol input output weights size height width gx gy blockY shift [skip]\n",av[0]);return 2;}constexpr size_t A=4194304;auto in=rd(av[3],A),w=rd(av[5],strtoull(av[6],0,0));std::vector<unsigned char>skip;if(ac==14)skip=rd(av[13],A);int h=atoi(av[7]),wd=atoi(av[8]),gx=atoi(av[9]),gy=atoi(av[10]),by=atoi(av[11]),sh=atoi(av[12])?-4:0;ck("init",cuInit(0));CUdevice d;ck("dev",cuDeviceGet(&d,0));CUcontext c;ck("ctx",cuDevicePrimaryCtxRetain(&c,d));ck("set",cuCtxSetCurrent(c));CUmodule m;ck("module",cuModuleLoad(&m,av[1]));CUfunction f;ck("function",cuModuleGetFunction(&f,m,av[2]));CUdeviceptr di,doo,dw,aux,ds=0;for(auto p:{&di,&doo,&aux}){ck("alloc",cuMemAlloc(p,A));ck("zero",cuMemsetD8(*p,0,A));}if(ac==14){ck("skip_alloc",cuMemAlloc(&ds,A));ck("skip_upload",cuMemcpyHtoD(ds,skip.data(),A));}ck("aw",cuMemAlloc(&dw,w.size()));ck("input",cuMemcpyHtoD(di,in.data(),A));ck("weight",cuMemcpyHtoD(dw,w.data(),w.size()));CUdeviceptr a1=aux+0x800;unsigned char p[0x58]{};std::memcpy(p,&di,8);std::memcpy(p+8,&doo,8);std::memcpy(p+16,&dw,8);if(ds)std::memcpy(p+24,&ds,8);std::memcpy(p+32,&h,4);std::memcpy(p+36,&wd,4);std::memcpy(p+40,&sh,4);std::memcpy(p+44,&sh,4);std::memcpy(p+48,&aux,8);std::memcpy(p+64,&a1,8);void*a[]={p};ck("launch",cuLaunchKernel(f,gx,gy,1,32,by,1,0,0,a,0));ck("sync",cuCtxSynchronize());std::vector<unsigned char>x(A);ck("read",cuMemcpyDtoH(x.data(),doo,A));size_t nz=0,last=0,nan=0;for(size_t i=0;i<A;i++){if(x[i]){++nz;last=i;}nan+=x[i]==0x7f||x[i]==0xff;}std::printf("nonzero=%zu last=%zu nan=%zu\n",nz,last,nan);std::ofstream(av[4],std::ios::binary).write((char*)x.data(),A);return nan?3:0;}
