#include <cstring>
#include "fast_history_fixture.h"
#include "../src/native_low_frequency_temporal.h"
#include "../src/native_temporal_mode.h"
#include <cmath>
#include <cstring>
static float HalfReference(float v){if(v==0)return v;int e=0;std::frexp(double(v),&e);double spacing=std::ldexp(1.0,e-11);return float(std::nearbyint(double(v)/spacing)*spacing);}
int main(int argc,char**){try{Gpu g(argc>1);constexpr UINT w=8,h=8,n=w*h;auto raw=g.Buffer(n*16),out=g.Buffer(n*12);std::vector<float>x(n*4,.4f),y(n*3,.6f);g.Upload(raw.Get(),x);g.Upload(out.Get(),y);NativeLowFrequencyTemporal f;f.Create(g.device.Get(),w,h,h);
 auto step=[&](UINT id,float value,bool reset,float exposure=1.f,bool checker=false){for(UINT p=0;p<n;p++)for(UINT c=0;c<3;c++)y[p*3+c]=value+(checker?((p%w+p/w)&1?.05f:-.05f):0);g.Upload(out.Get(),y);f.Prepare(g.queue.Get(),id,true,exposure,reset,nullptr,0,0,0,0,false,.08*std::log(2.));g.Run([&](auto*c){f.Record(c,raw.Get(),out.Get());});f.Submitted(g.queue.Get());return g.Read(out.Get());};
 auto callback0=NativeAdmitTemporalSource(NativeTemporalMode::LowFrequency,false,false,true,true,true);auto callback1=NativeAdmitTemporalSource(NativeTemporalMode::LowFrequency,false,false,true,true,false);Require(!callback1.motion_read&&callback1.metadata&&!callback1.reset,"actual shared FFX admission retains mode2 metadata without declaration");auto a=step(0,.6f,callback0.reset);Require(a==y,"cold/reset exact output");auto b=step(1,.8f,callback1.reset);Require(f.UsingPast()==1,"static second frame must actually accumulate");UINT p=4*w+4;float l0=HalfReference(.6f-.4f),l1=HalfReference(.8f-.4f);float expected=.8f+(l0-l1)*.5f;Require(std::abs(b[p*3]-expected)<4e-6f,"independent constant low EMA and half storage");
 f.Reset();step(2,.6f,true,1,true);auto c=step(3,.8f,false,1,true);Require(std::abs((c[p*3]-c[(p+1)*3])-(y[p*3]-y[(p+1)*3]))<4e-6,"current high-frequency contrast preserved");auto reset=step(4,.7f,true);Require(reset==y,"explicit reset exact");auto expo=step(5,.8f,false,2);Require(expo==y,"exposure change exact cold");auto gap=step(7,.8f,false,2);Require(gap==y,"frame gap cold");
 std::fill(x.begin(),x.end(),.9f);g.Upload(raw.Get(),x);auto reject=step(8,.7f,false,2);Require(reject==y,"strong original-colour change rejects history");f.Reset();auto zero=step(9,.0f,true,2);Require(zero==y,"zero failed NR never resurrected");g.NoErrors();puts("PASS low-frequency constant/halfEMA/high complement/reset/exposure/gap/colour reject/zero output");return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
