#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cwchar>
#include <cstring>
#include <fstream>
#include <vector>

static void check(const char *name, HRESULT hr) {
    if (FAILED(hr)) { std::fprintf(stderr, "%s: 0x%08lx\n", name, hr); ExitProcess(1); }
}
static std::vector<uint8_t> read_file(const wchar_t *path) {
    std::ifstream f(path, std::ios::binary | std::ios::ate); if (!f) ExitProcess(2);
    const size_t n=(size_t)f.tellg(); f.seekg(0); std::vector<uint8_t> b(n); f.read((char*)b.data(),n); return b;
}
static void write_file(const wchar_t *path, const void *data, size_t size) {
    std::ofstream f(path, std::ios::binary); if (!f) ExitProcess(2); f.write((const char*)data,size);
}
static D3D12_HEAP_PROPERTIES heap(D3D12_HEAP_TYPE t) { D3D12_HEAP_PROPERTIES h{}; h.Type=t; h.CreationNodeMask=h.VisibleNodeMask=1; return h; }
static D3D12_RESOURCE_DESC buffer(UINT64 n, D3D12_RESOURCE_FLAGS flags=D3D12_RESOURCE_FLAG_NONE) {
    D3D12_RESOURCE_DESC d{}; d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER; d.Width=n; d.Height=1; d.DepthOrArraySize=1; d.MipLevels=1; d.SampleDesc.Count=1; d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR; d.Flags=flags; return d;
}

int wmain(int argc, wchar_t **argv) {
    const bool dump_ffn=std::getenv("DUMP_FFN")!=nullptr;
    const bool stage_mode=argc==7;
    if (argc != 4 && !stage_mode) { std::fwprintf(stderr,L"usage: %ls effective.bin input.f32 oracle.f32\n       %ls effective.bin input.f32 output.f32 width height shift\n",argv[0],argv[0]); return 2; }
    const auto weights=read_file(argv[1]); auto input=read_file(argv[2]);
    const bool split512=weights.size()==3936320;
    const bool fused256=weights.size()==1247264;
    const bool fused64=weights.size()==115208;
    const bool precomputed=true;
    const auto oracle=stage_mode?std::vector<uint8_t>{}:read_file(argv[3]);
    const UINT width=stage_mode?(UINT)_wtoi(argv[4]):512, height=stage_mode?(UINT)_wtoi(argv[5]):64, shifted=stage_mode?(UINT)_wtoi(argv[6]):0;
    const UINT padded_tokens=width*height;
    const UINT channels=split512?512:(fused256?256:(fused64?64:128));
    const UINT active_height=stage_mode&&width&&channels&&input.size()%(UINT64(width)*channels*4)==0?(UINT)(input.size()/(UINT64(width)*channels*4)):height;
    if ((!split512&&!fused256&&!fused64&&weights.size()!=361488) || active_height>height || height-active_height>=8 || width%8 || height%8 || (!stage_mode && oracle.size()!=input.size())) { std::fprintf(stderr,"bad input: argc=%d weights=%zu input=%zu oracle=%zu shape=%ux%u active_height=%u shift=%u channels=%u\n",argc,weights.size(),input.size(),oracle.size(),width,height,active_height,shifted,channels); return 2; }
    const UINT active_tokens=width*active_height,tokens=padded_tokens;const UINT64 active_tensor_bytes=UINT64(active_tokens)*channels*4,tensor_bytes=UINT64(tokens)*channels*4;
    if(input.size()!=active_tensor_bytes)return 2;
    if(active_height!=height)input.resize((size_t)tensor_bytes,0);

    IDXGIFactory6 *factory=nullptr; check("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)));
    IDXGIAdapter1 *adapter=nullptr; DXGI_ADAPTER_DESC1 ad{};
    for(UINT i=0;;++i){IDXGIAdapter1*c=nullptr;if(factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){adapter=c;ad=d;break;}c->Release();}
    if(!adapter)return 1; ID3D12Device *dev=nullptr; check("device",D3D12CreateDevice(adapter,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));
    std::wprintf(L"adapter: %ls\n",ad.Description);
    D3D12_COMMAND_QUEUE_DESC qd{}; qd.Type=D3D12_COMMAND_LIST_TYPE_DIRECT; ID3D12CommandQueue*q=nullptr;check("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));
    ID3D12CommandAllocator*alloc=nullptr;check("alloc",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&alloc)));
    ID3D12GraphicsCommandList*cmd=nullptr;check("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,alloc,nullptr,IID_PPV_ARGS(&cmd)));

    const char shader128[] = R"(
ByteAddressBuffer w:register(t0);StructuredBuffer<float> inp:register(t1),feat_in:register(t2),qkv_in:register(t3),attn_in:register(t4);RWStructuredBuffer<float> feat:register(u0),outp:register(u1),qkv_out:register(u2),attn_out:register(u3);static const uint tokens=WIDTH*HEIGHT;float W(uint i){return asfloat(w.Load(i*4));}
float fp8(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}
[numthreads(64,1,1)]void ffn_expand(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*160)return;uint t=z/160,j=z%160;float a=0;[loop]for(uint c=0;c<128;c++)a+=inp[t*128+c]*W(j*128+c);a=clamp(a,-4.,4.);qkv_out[t*384+j]=a*(.89453125+a*(.447265625-.055908203125*abs(a)));}
[numthreads(64,1,1)]void ffn_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*128)return;uint t=z/128,c=z%128;float v=0;[loop]for(uint j=0;j<160;j++)v+=qkv_in[t*384+j]*W(20480+c*160+j);feat[z]=fp8(v+inp[z]*W(90116+c));}
 [numthreads(64,1,1)]void qkv_precompute(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*192)return;uint t=z/192,r=z%192;float v=0;[loop]for(uint c=0;c<128;c++)v+=feat_in[t*128+c]*W(40960+r*128+c);qkv_out[z]=v;}
void qkv(uint t,out float q[64],out float k[64],out float v[64]){[loop]for(uint o=0;o<64;o++){q[o]=qkv_in[t*192+o];k[o]=qkv_in[t*192+64+o];v[o]=qkv_in[t*192+128+o];}}
void qkv_head(uint t,uint head,out float q[16],out float k[16],out float v[16]){[unroll]for(uint d=0;d<16;d++){uint o=head*16+d;q[d]=qkv_in[t*192+o];k[d]=qkv_in[t*192+64+o];v[d]=qkv_in[t*192+128+o];}}
[numthreads(64,1,1)]void attention(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*4)return;uint t=z/4,head=z%4,qi=query_index(t);float q[16],k0[16],v0[16];qkv_head(t,head,q,k0,v0);float qq=0;[unroll]for(uint d=0;d<16;d++)qq+=q[d]*q[d];float mx=-3.4e38;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){float x=k[d];kk+=x*x;dot+=q[d]*x;}mx=max(mx,dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(90112+head)+W(73728+head*4096+qi*64+key));}float den=0,tmp[16];[unroll]for(uint d=0;d<16;d++)tmp[d]=0;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){float x=k[d];kk+=x*x;dot+=q[d]*x;}float e=exp(dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(90112+head)+W(73728+head*4096+qi*64+key)-mx);den+=e;[unroll]for(uint d=0;d<16;d++)tmp[d]+=e*v[d];}[unroll]for(uint d=0;d<16;d++)attn_out[t*64+head*16+d]=tmp[d]/den;}
[numthreads(64,1,1)]void attention_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*128)return;uint t=z/128,c=z%128;float x=0;[loop]for(uint i=0;i<64;i++)x+=attn_in[t*64+i]*W(65536+c*64+i);outp[z]=fp8(x+feat_in[z]*W(90244+c));}
)";
    const char shader512[] = R"(
ByteAddressBuffer w:register(t0);StructuredBuffer<float> inp:register(t1),feat_in:register(t2),qkv_in:register(t3),attn_in:register(t4);RWStructuredBuffer<float> feat:register(u0),outp:register(u1),qkv_out:register(u2),attn_out:register(u3);static const uint tokens=WIDTH*HEIGHT;float W(uint i){return asfloat(w.Load(i*4));}
float fp8(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}
float fast(float a){a=clamp(a,-4.,4.);return a*(.89453125+a*(.447265625-.055908203125*abs(a)));}
[numthreads(64,1,1)]void ffn_expand(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*256)return;uint t=z/256,j=z%256;float g=0,u=0;[loop]for(uint c=0;c<512;c++){float x=inp[t*512+c];g+=x*W(j*512+c);u+=x*W(131072+j*512+c);}qkv_out[t*768+j]=fast(g)*u;}
[numthreads(64,1,1)]void ffn_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*512)return;uint t=z/512,c=z%512;float v=0;[loop]for(uint j=0;j<256;j++)v+=qkv_in[t*768+j]*W(262144+c*256+j);feat[z]=fp8(v+inp[z]*W(393216+c));}
 [numthreads(64,1,1)]void qkv_precompute(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*768)return;uint t=z/768,r=z%768,g=r/256,o=r%256;float v=0;[loop]for(uint c=0;c<512;c++)v+=feat_in[t*512+c]*W(393728+(g*256+o)*512+c);qkv_out[z]=v;}
void qkv_head(uint t,uint head,out float q[16],out float k[16],out float v[16]){[unroll]for(uint o=0;o<16;o++){uint row=head*16+o;q[o]=qkv_in[t*768+row];k[o]=qkv_in[t*768+256+row];v[o]=qkv_in[t*768+512+row];}}
[numthreads(64,1,1)]void attention(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*16)return;uint t=z/16,head=z%16,qi=query_index(t);float q[16],k0[16],v0[16];qkv_head(t,head,q,k0,v0);float qq=0;[unroll]for(uint d=0;d<16;d++)qq+=q[d]*q[d];float mx=-3.4e38;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){kk+=k[d]*k[d];dot+=q[d]*k[d];}mx=max(mx,dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(852480+head)+W(786944+head*4096+qi*64+key));}float den=0,tmp[16];[unroll]for(uint d=0;d<16;d++)tmp[d]=0;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){kk+=k[d]*k[d];dot+=q[d]*k[d];}float e=exp(dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(852480+head)+W(786944+head*4096+qi*64+key)-mx);den+=e;[unroll]for(uint d=0;d<16;d++)tmp[d]+=e*v[d];}[unroll]for(uint d=0;d<16;d++)attn_out[t*256+head*16+d]=tmp[d]/den;}
[numthreads(64,1,1)]void attention_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*512)return;uint t=z/512,c=z%512;float x=0;[loop]for(uint i=0;i<256;i++)x+=attn_in[t*256+i]*W(852496+c*256+i);outp[z]=fp8(x+feat_in[z]*W(983568+c));}
)";
    const char shader256[] = R"(
ByteAddressBuffer w:register(t0);StructuredBuffer<float> inp:register(t1),feat_in:register(t2),qkv_in:register(t3),attn_in:register(t4);RWStructuredBuffer<float> feat:register(u0),outp:register(u1),qkv_out:register(u2),attn_out:register(u3);static const uint tokens=WIDTH*HEIGHT;float W(uint i){return asfloat(w.Load(i*4));}
float fp8(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}
float fast(float a){a=clamp(a,-4.,4.);return a*(.89453125+a*(.447265625-.055908203125*abs(a)));}
[numthreads(64,1,1)]void ffn_expand(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*288)return;uint t=z/288,j=z%288;float a=0;[loop]for(uint c=0;c<256;c++)a+=inp[t*256+c]*W(j*256+c);qkv_out[t*384+j]=fast(a);}
[numthreads(64,1,1)]void ffn_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*256)return;uint t=z/256,c=z%256;float v=0;[loop]for(uint j=0;j<288;j++)v+=qkv_in[t*384+j]*W(73728+c*288+j);feat[z]=fp8(v+inp[z]*W(147456+c));}
[numthreads(64,1,1)]void qkv_precompute(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*384)return;uint t=z/384,r=z%384;float v=0;[loop]for(uint c=0;c<256;c++)v+=feat_in[t*256+c]*W(147712+r*256+c);qkv_out[z]=v;}
void qkv_head(uint t,uint head,out float q[16],out float k[16],out float v[16]){[unroll]for(uint o=0;o<16;o++){uint row=head*16+o;q[o]=qkv_in[t*384+row];k[o]=qkv_in[t*384+128+row];v[o]=qkv_in[t*384+256+row];}}
[numthreads(64,1,1)]void attention(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*8)return;uint t=z/8,head=z%8,qi=query_index(t);float q[16],k0[16],v0[16];qkv_head(t,head,q,k0,v0);float qq=0;[unroll]for(uint d=0;d<16;d++)qq+=q[d]*q[d];float mx=-3.4e38;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){kk+=k[d]*k[d];dot+=q[d]*k[d];}mx=max(mx,dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(278784+head)+W(246016+head*4096+qi*64+key));}float den=0,tmp[16];[unroll]for(uint d=0;d<16;d++)tmp[d]=0;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){kk+=k[d]*k[d];dot+=q[d]*k[d];}float e=exp(dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(278784+head)+W(246016+head*4096+qi*64+key)-mx);den+=e;[unroll]for(uint d=0;d<16;d++)tmp[d]+=e*v[d];}[unroll]for(uint d=0;d<16;d++)attn_out[t*128+head*16+d]=tmp[d]/den;}
[numthreads(64,1,1)]void attention_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*256)return;uint t=z/256,c=z%256;float x=0;[loop]for(uint i=0;i<128;i++)x+=attn_in[t*128+i]*W(278792+c*128+i);outp[z]=fp8(x+feat_in[z]*W(311560+c));}
)";
    const char shader64[] = R"(
ByteAddressBuffer w:register(t0);StructuredBuffer<float> inp:register(t1),feat_in:register(t2),qkv_in:register(t3),attn_in:register(t4);RWStructuredBuffer<float> feat:register(u0),outp:register(u1),qkv_out:register(u2),attn_out:register(u3);static const uint tokens=WIDTH*HEIGHT;float W(uint i){return asfloat(w.Load(i*4));}
float fp8(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}
float fast(float a){a=clamp(a,-4.,4.);return a*(.89453125+a*(.447265625-.055908203125*abs(a)));}
[numthreads(64,1,1)]void ffn_expand(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*96)return;uint t=z/96,j=z%96;float a=0;[loop]for(uint c=0;c<64;c++)a+=inp[t*64+c]*W(j*64+c);qkv_out[t*384+j]=fast(a);}
[numthreads(64,1,1)]void ffn_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*64)return;uint t=z/64,c=z%64;float v=0;[loop]for(uint j=0;j<96;j++)v+=qkv_in[t*384+j]*W(6144+c*96+j);feat[z]=fp8(v+inp[z]*W(12288+c));}
[numthreads(64,1,1)]void qkv_precompute(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*96)return;uint t=z/96,r=z%96;float v=0;[loop]for(uint c=0;c<64;c++)v+=feat_in[t*64+c]*W(12352+r*64+c);qkv_out[z]=v;}
void qkv_head(uint t,uint head,out float q[16],out float k[16],out float v[16]){[unroll]for(uint o=0;o<16;o++){uint row=head*16+o;q[o]=qkv_in[t*96+row];k[o]=qkv_in[t*96+32+row];v[o]=qkv_in[t*96+64+row];}}
[numthreads(64,1,1)]void attention(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*2)return;uint t=z/2,head=z%2,qi=query_index(t);float q[16],k0[16],v0[16];qkv_head(t,head,q,k0,v0);float qq=0;[unroll]for(uint d=0;d<16;d++)qq+=q[d]*q[d];float mx=-3.4e38;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){kk+=k[d]*k[d];dot+=q[d]*k[d];}mx=max(mx,dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(26688+head)+W(18496+head*4096+qi*64+key));}float den=0,tmp[16];[unroll]for(uint d=0;d<16;d++)tmp[d]=0;[loop]for(uint key=0;key<64;key++){float tq[16],k[16],v[16];qkv_head(key_token(t,key),head,tq,k,v);float kk=0,dot=0;[unroll]for(uint d=0;d<16;d++){kk+=k[d]*k[d];dot+=q[d]*k[d];}float e=exp(dot*rsqrt(max(qq,1e-12))*rsqrt(max(kk,1e-12))*W(26688+head)+W(18496+head*4096+qi*64+key)-mx);den+=e;[unroll]for(uint d=0;d<16;d++)tmp[d]+=e*v[d];}[unroll]for(uint d=0;d<16;d++)attn_out[t*32+head*16+d]=tmp[d]/den;}
[numthreads(64,1,1)]void attention_project(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=tokens*64)return;uint t=z/64,c=z%64;float x=0;[loop]for(uint i=0;i<32;i++)x+=attn_in[t*32+i]*W(26690+c*32+i);outp[z]=fp8(x+feat_in[z]*W(28738+c));}
)";
    std::string shader_storage=split512?shader512:(fused256?shader256:(fused64?shader64:shader128));
    auto replace_all = [&](const char *from, const char *to) {
        size_t position=0;
        while((position=shader_storage.find(from,position))!=std::string::npos){shader_storage.replace(position,std::strlen(from),to);position+=std::strlen(to);}
    };
    replace_all(
        "static const uint tokens=WIDTH*HEIGHT;",
        "static const uint tokens=WIDTH*HEIGHT;"
        "uint query_index(uint t){uint y=t/WIDTH,x=t%WIDTH;uint ry=SHIFT_Y?((y+HEIGHT-4)%HEIGHT):y;uint rx=SHIFT_X?((x+WIDTH-4)%WIDTH):x;return (ry%8)*8+(rx%8);}"
        "uint key_token(uint t,uint key){uint y=t/WIDTH,x=t%WIDTH;uint ry=SHIFT_Y?((y+HEIGHT-4)%HEIGHT):y;uint rx=SHIFT_X?((x+WIDTH-4)%WIDTH):x;uint ky=(ry/8)*8+key/8,kx=(rx/8)*8+key%8;if(SHIFT_Y)ky=(ky+4)%HEIGHT;if(SHIFT_X)kx=(kx+4)%WIDTH;return ky*WIDTH+kx;}"
    );
    replace_all("uint tile=t/64,qi=t%64;","uint qi=query_index(t);");
    replace_all("tile*64+key","key_token(t,key)");
    const char *shader=shader_storage.c_str();
    const UINT shift_x=shifted==1||shifted==2,shift_y=shifted==1||shifted==3;
    char ws[16],hs[16],sx[4],sy[4];std::snprintf(ws,sizeof(ws),"%u",width);std::snprintf(hs,sizeof(hs),"%u",height);std::snprintf(sx,sizeof(sx),"%u",shift_x);std::snprintf(sy,sizeof(sy),"%u",shift_y);D3D_SHADER_MACRO macros[]={{"WIDTH",ws},{"HEIGHT",hs},{"SHIFT_X",sx},{"SHIFT_Y",sy},{nullptr,nullptr}};
    const bool parallel_ffn=channels==64||channels==128||channels==256||channels==512;
    const bool split_attention=true;
    const UINT ffn_hidden=channels==64?96:(channels==128?160:(channels==256?288:(channels==512?256:0)));
    ID3DBlob *b1=nullptr,*b2=nullptr,*b3=nullptr,*b4=nullptr,*b5=nullptr,*err=nullptr;
    wchar_t cache_dir[MAX_PATH],cache_ffn[MAX_PATH],cache_expand[MAX_PATH],cache_project[MAX_PATH],cache_qkv[MAX_PATH],cache_attention[MAX_PATH],cache_attention_project[MAX_PATH];
    GetModuleFileNameW(nullptr,cache_dir,MAX_PATH);wchar_t *slash=wcsrchr(cache_dir,L'\\');if(slash)std::wcscpy(slash+1,L"shader-cache");else std::wcscpy(cache_dir,L"shader-cache");CreateDirectoryW(cache_dir,nullptr);
    std::swprintf(cache_ffn,MAX_PATH,L"%ls\\block128-v1-c%u-%ux%u-s%u-ffn.cso",cache_dir,channels,width,height,shifted);
    std::swprintf(cache_expand,MAX_PATH,L"%ls\\block128-v2-c%u-%ux%u-s%u-ffn-expand.cso",cache_dir,channels,width,height,shifted);
    std::swprintf(cache_project,MAX_PATH,L"%ls\\block128-v2-c%u-%ux%u-s%u-ffn-project.cso",cache_dir,channels,width,height,shifted);
    std::swprintf(cache_qkv,MAX_PATH,L"%ls\\block128-v1-c%u-%ux%u-s%u-qkv.cso",cache_dir,channels,width,height,shifted);
    std::swprintf(cache_attention,MAX_PATH,L"%ls\\block128-v4-c%u-%ux%u-s%u-attention.cso",cache_dir,channels,width,height,shifted);
    std::swprintf(cache_attention_project,MAX_PATH,L"%ls\\block128-v4-c%u-%ux%u-s%u-attention-project.cso",cache_dir,channels,width,height,shifted);
    if(parallel_ffn){D3DReadFileToBlob(cache_expand,&b1);D3DReadFileToBlob(cache_project,&b4);}else D3DReadFileToBlob(cache_ffn,&b1);D3DReadFileToBlob(cache_qkv,&b3);D3DReadFileToBlob(cache_attention,&b2);if(split_attention)D3DReadFileToBlob(cache_attention_project,&b5);const bool cache_hit=b1&&b2&&b3&&(!parallel_ffn||b4)&&(!split_attention||b5);
    if(parallel_ffn&&!b1){check("compile ffn expand",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,"ffn_expand","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b1,&err));if(err)err->Release();err=nullptr;check("cache expand",D3DWriteBlobToFile(b1,cache_expand,TRUE));}
    if(parallel_ffn&&!b4){check("compile ffn project",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,"ffn_project","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b4,&err));if(err)err->Release();err=nullptr;check("cache project",D3DWriteBlobToFile(b4,cache_project,TRUE));}
    else if(!b1){check("compile ffn",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,"ffn","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b1,&err));if(err)err->Release();err=nullptr;check("cache ffn",D3DWriteBlobToFile(b1,cache_ffn,TRUE));}
    if(precomputed&&!b3){check("compile qkv",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,"qkv_precompute","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b3,&err));if(err)err->Release();err=nullptr;check("cache qkv",D3DWriteBlobToFile(b3,cache_qkv,TRUE));}
    if(!b2){check("compile attention",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,"attention","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b2,&err));if(err)err->Release();check("cache attention",D3DWriteBlobToFile(b2,cache_attention,TRUE));}
    if(split_attention&&!b5){check("compile attention project",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,"attention_project","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b5,&err));if(err)err->Release();check("cache attention project",D3DWriteBlobToFile(b5,cache_attention_project,TRUE));}
    std::printf("shader_cache: %s\n",cache_hit?"hit":"miss");
    D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0]={D3D12_DESCRIPTOR_RANGE_TYPE_SRV,5,0,0,0};ranges[1]={D3D12_DESCRIPTOR_RANGE_TYPE_UAV,4,0,0,5};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*rsb=nullptr;check("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&rsb,&err));ID3D12RootSignature*rs=nullptr;check("rootsig",dev->CreateRootSignature(0,rsb->GetBufferPointer(),rsb->GetBufferSize(),IID_PPV_ARGS(&rs)));rsb->Release();
    D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={b1->GetBufferPointer(),b1->GetBufferSize()};ID3D12PipelineState*p1=nullptr,*p2=nullptr,*p3=nullptr,*p4=nullptr,*p5=nullptr;check("pso1",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&p1)));if(parallel_ffn){pd.CS={b4->GetBufferPointer(),b4->GetBufferSize()};check("pso4",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&p4)));}if(precomputed){pd.CS={b3->GetBufferPointer(),b3->GetBufferSize()};check("pso3",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&p3)));}pd.CS={b2->GetBufferPointer(),b2->GetBufferSize()};check("pso2",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&p2)));if(split_attention){pd.CS={b5->GetBufferPointer(),b5->GetBufferSize()};check("pso5",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&p5)));}b1->Release();b2->Release();if(b3)b3->Release();if(b4)b4->Release();if(b5)b5->Release();
    auto hp=heap(D3D12_HEAP_TYPE_UPLOAD),hd=heap(D3D12_HEAP_TYPE_DEFAULT),hr=heap(D3D12_HEAP_TYPE_READBACK);ID3D12Resource *wr=nullptr,*ir=nullptr,*fr=nullptr,*orr=nullptr,*qr=nullptr,*ar=nullptr,*rb=nullptr;auto wd=buffer(weights.size()),td=buffer(tensor_bytes),ud=buffer(tensor_bytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);const UINT qkv_stride=split512?768:384;const UINT64 qkv_bytes=UINT64(tokens)*qkv_stride*4,attention_bytes=UINT64(tokens)*std::max(1u,channels/2)*4;auto qd2=buffer(qkv_bytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),ad2=buffer(attention_bytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);check("wr",dev->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&wd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&wr)));check("ir",dev->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&ir)));check("fr",dev->CreateCommittedResource(&hd,D3D12_HEAP_FLAG_NONE,&ud,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&fr)));check("or",dev->CreateCommittedResource(&hd,D3D12_HEAP_FLAG_NONE,&ud,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&orr)));if(precomputed)check("qr",dev->CreateCommittedResource(&hd,D3D12_HEAP_FLAG_NONE,&qd2,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&qr)));check("ar",dev->CreateCommittedResource(&hd,D3D12_HEAP_FLAG_NONE,&ad2,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&ar)));check("rb",dev->CreateCommittedResource(&hr,D3D12_HEAP_FLAG_NONE,&td,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&rb)));void*m=nullptr;D3D12_RANGE none{0,0};wr->Map(0,&none,&m);memcpy(m,weights.data(),weights.size());wr->Unmap(0,nullptr);ir->Map(0,&none,&m);memcpy(m,input.data(),input.size());ir->Unmap(0,nullptr);
    D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,9,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*dh=nullptr;check("heap",dev->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&dh)));UINT ds=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=dh->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sd{};sd.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sd.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sd.Format=DXGI_FORMAT_R32_TYPELESS;sd.Buffer.NumElements=weights.size()/4;sd.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;dev->CreateShaderResourceView(wr,&sd,h);h.ptr+=ds;sd.Format=DXGI_FORMAT_UNKNOWN;sd.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sd.Buffer.StructureByteStride=4;sd.Buffer.NumElements=tensor_bytes/4;dev->CreateShaderResourceView(ir,&sd,h);h.ptr+=ds;dev->CreateShaderResourceView(fr,&sd,h);h.ptr+=ds;sd.Buffer.NumElements=qkv_bytes/4;dev->CreateShaderResourceView(qr,&sd,h);h.ptr+=ds;sd.Buffer.NumElements=attention_bytes/4;dev->CreateShaderResourceView(ar,&sd,h);h.ptr+=ds;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.NumElements=tensor_bytes/4;uv.Buffer.StructureByteStride=4;dev->CreateUnorderedAccessView(fr,nullptr,&uv,h);h.ptr+=ds;dev->CreateUnorderedAccessView(orr,nullptr,&uv,h);h.ptr+=ds;uv.Buffer.NumElements=qkv_bytes/4;dev->CreateUnorderedAccessView(qr,nullptr,&uv,h);h.ptr+=ds;uv.Buffer.NumElements=attention_bytes/4;dev->CreateUnorderedAccessView(ar,nullptr,&uv,h);
    D3D12_QUERY_HEAP_DESC qhd{};qhd.Type=D3D12_QUERY_HEAP_TYPE_TIMESTAMP;qhd.Count=6;ID3D12QueryHeap*qh=nullptr;check("query heap",dev->CreateQueryHeap(&qhd,IID_PPV_ARGS(&qh)));auto qtd=buffer(6*sizeof(UINT64));ID3D12Resource*qtr=nullptr;check("query readback",dev->CreateCommittedResource(&hr,D3D12_HEAP_FLAG_NONE,&qtd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&qtr)));
    ID3D12DescriptorHeap*heaps[]={dh};cmd->SetDescriptorHeaps(1,heaps);cmd->SetComputeRootSignature(rs);cmd->SetComputeRootDescriptorTable(0,dh->GetGPUDescriptorHandleForHeapStart());cmd->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,0);cmd->SetPipelineState(p1);cmd->Dispatch((tokens*(parallel_ffn?ffn_hidden:1)+63)/64,1,1);cmd->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,1);
    if(parallel_ffn){D3D12_RESOURCE_BARRIER hidden{};hidden.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;hidden.Transition.pResource=qr;hidden.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;hidden.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;hidden.Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;cmd->ResourceBarrier(1,&hidden);cmd->SetPipelineState(p4);cmd->Dispatch((tokens*channels+63)/64,1,1);hidden.Transition.StateBefore=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;hidden.Transition.StateAfter=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;cmd->ResourceBarrier(1,&hidden);}cmd->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,2);
    D3D12_RESOURCE_BARRIER bs[2]{};bs[0].Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;bs[0].UAV.pResource=fr;bs[1].Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;bs[1].Transition.pResource=fr;bs[1].Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;bs[1].Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;bs[1].Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;cmd->ResourceBarrier(2,bs);if(precomputed){cmd->SetPipelineState(p3);cmd->Dispatch((tokens*qkv_stride+63)/64,1,1);D3D12_RESOURCE_BARRIER qb{};qb.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;qb.Transition.pResource=qr;qb.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;qb.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;qb.Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;cmd->ResourceBarrier(1,&qb);}cmd->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,3);cmd->SetPipelineState(p2);cmd->Dispatch((tokens*(channels/32)+63)/64,1,1);cmd->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,4);if(split_attention){D3D12_RESOURCE_BARRIER ab{};ab.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;ab.Transition.pResource=ar;ab.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;ab.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;ab.Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;cmd->ResourceBarrier(1,&ab);cmd->SetPipelineState(p5);cmd->Dispatch((tokens*channels+63)/64,1,1);}cmd->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,5);D3D12_RESOURCE_BARRIER bo{};bo.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;bo.Transition.pResource=dump_ffn?fr:orr;bo.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;bo.Transition.StateBefore=dump_ffn?D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE:D3D12_RESOURCE_STATE_UNORDERED_ACCESS;bo.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cmd->ResourceBarrier(1,&bo);cmd->CopyBufferRegion(rb,0,dump_ffn?fr:orr,0,tensor_bytes);cmd->ResolveQueryData(qh,D3D12_QUERY_TYPE_TIMESTAMP,0,6,qtr,0);check("close",cmd->Close());
    LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cmd};q->ExecuteCommandLists(1,ls);ID3D12Fence*f=nullptr;check("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));q->Signal(f,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);f->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);CloseHandle(ev);UINT64 tf=0;q->GetTimestampFrequency(&tf);UINT64*ts=nullptr;D3D12_RANGE tr{0,6*sizeof(UINT64)};qtr->Map(0,&tr,(void**)&ts);
    D3D12_RANGE all{0,(SIZE_T)tensor_bytes};rb->Map(0,&all,&m);const float*got=(const float*)m;size_t n=active_tensor_bytes/4;std::printf("submit_to_fence_ms: %.3f\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart);const char*pn[5]={"ffn_expand","ffn_project","qkv","attention","attention_project"};for(int i=0;i<5;i++)std::printf("%s_ms: %.3f\n",pn[i],1000.0*double(ts[i+1]-ts[i])/double(tf));if(stage_mode){write_file(argv[3],got,active_tensor_bytes);std::printf("wrote: %zu floats active=%ux%u padded_height=%u\n",n,width,active_height,height);}else{const float*want=(const float*)oracle.data();double ae=0,se=0;size_t exact=0;for(size_t i=0;i<n;i++){double d=got[i]-want[i];ae+=fabs(d);se+=d*d;exact+=got[i]==want[i];}std::printf("MAE: %.9f\nRMSE: %.9f\nexact: %.6f\n",ae/n,sqrt(se/n),(double)exact/n);}rb->Unmap(0,&none);
    return 0;
}
