#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#define DML_TARGET_VERSION_USE_LATEST
#ifndef _Maybenull_
#define _Maybenull_
#endif
#include <DirectML.h>
#include "directml_gemm_runtime.h"
#include <cstdio>
#include <vector>
static const GUID IID_DEV={0x6dbd6437,0x96fd,0x423f,{0xa9,0x8c,0xae,0x5e,0x7c,0x2a,0x57,0x3f}},IID_REC={0xe6857a76,0x2e3e,0x4fdd,{0xbf,0xf4,0x5d,0x2b,0xa1,0x0f,0xb4,0x53}};using CreateFn=HRESULT(WINAPI*)(ID3D12Device*,DML_CREATE_DEVICE_FLAGS,REFIID,void**);
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES x{};x.Type=t;x.CreationNodeMask=x.VisibleNodeMask=1;return x;}static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f){D3D12_RESOURCE_DESC x{};x.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;x.Width=n;x.Height=1;x.DepthOrArraySize=1;x.MipLevels=1;x.SampleDesc.Count=1;x.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;x.Flags=f;return x;}static ID3D12Resource*buf(ID3D12Device*d,UINT64 n,D3D12_HEAP_TYPE h=D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATES s=D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS){auto p=hp(h);auto b=bd(n,f);ID3D12Resource*r=nullptr;dmlrt_check("resource",d->CreateCommittedResource(&p,D3D12_HEAP_FLAG_NONE,&b,s,nullptr,IID_PPV_ARGS(&r)));return r;}static void ub(ID3D12GraphicsCommandList*c,ID3D12Resource*r){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;b.UAV.pResource=r;c->ResourceBarrier(1,&b);}
int main(){constexpr UINT L=8,T=8640,C=512,H=256,Q=768;IDXGIFactory6*f=nullptr;dmlrt_check("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;DXGI_ADAPTER_DESC1 ad{};for(UINT i=0;;i++){IDXGIAdapter1*x=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&x))==DXGI_ERROR_NOT_FOUND)break;x->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(ad.Description,L"AMD")){a=x;break;}x->Release();}ID3D12Device*d=nullptr;dmlrt_check("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));HMODULE m=LoadLibraryW(L"DirectML.dll");auto create=(CreateFn)GetProcAddress(m,"DMLCreateDevice");IDMLDevice*ml=nullptr;dmlrt_check("dml",create(d,DML_CREATE_DEVICE_FLAG_NONE,IID_DEV,(void**)&ml));IDMLCommandRecorder*rec=nullptr;dmlrt_check("rec",ml->CreateCommandRecorder(IID_REC,(void**)&rec));DmlGemmOperator gate[L],up[L],project[L],qkv[L],attentionProject[L];for(UINT i=0;i<L;i++){gate[i].Create(ml,d,1,T,C,H);up[i].Create(ml,d,1,T,C,H);project[i].Create(ml,d,1,T,H,C);qkv[i].Create(ml,d,1,T,C,Q);attentionProject[i].Create(ml,d,1,T,H,C);}D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*queue=nullptr;dmlrt_check("queue",d->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)));ID3D12CommandAllocator*ca=nullptr;dmlrt_check("alloc",d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;dmlrt_check("list",d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12Fence*fe=nullptr;dmlrt_check("fence",d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 fv=0;auto wait=[&](){cl->Close();ID3D12CommandList*l[]={cl};queue->ExecuteCommandLists(1,l);queue->Signal(fe,++fv);fe->SetEventOnCompletion(fv,ev);WaitForSingleObject(ev,INFINITE);ca->Reset();cl->Reset(ca,nullptr);};for(UINT i=0;i<L;i++)for(auto*o:{&gate[i],&up[i],&project[i],&qkv[i],&attentionProject[i]})o->RecordInitialization(rec,cl);wait();
 UINT64 mainBytes=UINT64(T)*C*2,hiddenBytes=UINT64(T)*H*2,qkvBytes=UINT64(T)*Q*2;ID3D12Resource*main[2]={buf(d,mainBytes),buf(d,mainBytes)},*g=buf(d,hiddenBytes),*u=buf(d,hiddenBytes),*hidden=buf(d,hiddenBytes),*feat=buf(d,mainBytes),*qkvOut=buf(d,qkvBytes),*attention=buf(d,hiddenBytes);ID3D12Resource*gw[L]{},*uw[L]{},*pw[L]{},*qw[L]{},*aw[L]{};std::vector<ID3D12Resource*>resources={main[0],main[1],g,u,hidden,feat,qkvOut,attention};for(UINT i=0;i<L;i++){gw[i]=buf(d,UINT64(C)*H*2);uw[i]=buf(d,UINT64(C)*H*2);pw[i]=buf(d,UINT64(H)*C*2);qw[i]=buf(d,UINT64(C)*Q*2);aw[i]=buf(d,UINT64(H)*C*2);for(auto*r:{gw[i],uw[i],pw[i],qw[i],aw[i]})resources.push_back(r);}D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,(UINT)resources.size(),D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;dmlrt_check("heap",d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();for(auto*r:resources){D3D12_UNORDERED_ACCESS_VIEW_DESC v{};v.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;v.Format=DXGI_FORMAT_R32_TYPELESS;v.Buffer.NumElements=(UINT)(r->GetDesc().Width/4);v.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;d->CreateUnorderedAccessView(r,nullptr,&v,cpu);cpu.ptr+=step;}ID3D12DescriptorHeap*heaps[]={heap};cl->SetDescriptorHeaps(1,heaps);auto gpu=heap->GetGPUDescriptorHandleForHeapStart();cpu=heap->GetCPUDescriptorHandleForHeapStart();UINT zero[4]{};for(auto*r:resources){cl->ClearUnorderedAccessViewUint(gpu,cpu,r,zero,0,nullptr);gpu.ptr+=step;cpu.ptr+=step;}wait();for(UINT i=0;i<L;i++){UINT p=i&1,n=p^1;gate[i].Bind(main[p],gw[i],g);up[i].Bind(main[p],uw[i],u);project[i].Bind(hidden,pw[i],feat);qkv[i].Bind(feat,qw[i],qkvOut);attentionProject[i].Bind(attention,aw[i],main[n]);}
 D3D12_QUERY_HEAP_DESC qh{};qh.Type=D3D12_QUERY_HEAP_TYPE_TIMESTAMP;qh.Count=2;ID3D12QueryHeap*queries=nullptr;dmlrt_check("queries",d->CreateQueryHeap(&qh,IID_PPV_ARGS(&queries)));ID3D12Resource*rb=buf(d,16,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE);cl->EndQuery(queries,D3D12_QUERY_TYPE_TIMESTAMP,0);for(UINT i=0;i<L;i++){gate[i].Record(rec,cl);ub(cl,g);up[i].Record(rec,cl);ub(cl,u);project[i].Record(rec,cl);ub(cl,feat);qkv[i].Record(rec,cl);ub(cl,qkvOut);attentionProject[i].Record(rec,cl);ub(cl,main[(i&1)^1]);}cl->EndQuery(queries,D3D12_QUERY_TYPE_TIMESTAMP,1);cl->ResolveQueryData(queries,D3D12_QUERY_TYPE_TIMESTAMP,0,2,rb,0);wait();UINT64*t=nullptr;D3D12_RANGE range{0,16};rb->Map(0,&range,(void**)&t);UINT64 freq=0;queue->GetTimestampFrequency(&freq);double ms=1000.0*(t[1]-t[0])/freq;UINT64 bytes=0;for(auto*r:resources)bytes+=r->GetDesc().Width;wprintf(L"adapter=%ls layers=8 directml_ops=40 resources=%u resident_mib=%.2f matrix_gpu_ms=%.6f zero_chain=pass\n",ad.Description,(UINT)resources.size(),bytes/1048576.0,ms);return 0;}
