#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT r){if(FAILED(r)){std::fprintf(stderr,"%s=%08lx\n",n,r);ExitProcess(1);}}
static std::vector<uint8_t>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=f.tellg();f.seekg(0);std::vector<uint8_t>x(n);f.read((char*)x.data(),n);return x;}
static float e4(uint8_t v){float s=v&128?-1.f:1.f;unsigned e=(v>>3)&15,m=v&7;if(!e)return s*(m/8.f)*std::ldexp(1.f,-6);if(e==15&&m==7)return NAN;return s*(1.f+m/8.f)*std::ldexp(1.f,(int)e-7);}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
int wmain(int ac,wchar_t**av){
 if(ac!=11){std::fwprintf(stderr,L"usage: %ls matrix.fp8 main.fp8 q.fp8 k.fp8 v.fp8 input-off q-off k-off v-off metrics.txt\n",av[0]);return 2;}
 auto mat=rd(av[1]),main=rd(av[2]),hq=rd(av[3]),hk=rd(av[4]),hv=rd(av[5]),iob=rd(av[6]),qob=rd(av[7]),kob=rd(av[8]),vob=rd(av[9]);if(mat.size()!=1024ull*3*1024||main.size()!=2097152||hq.size()!=2097152||hk.size()!=2097152||hv.size()!=2097152||iob.size()!=4096||qob.size()!=4096||kob.size()!=4096||vob.size()!=4096)return 2;auto*io=(uint32_t*)iob.data();uint32_t*oo[3]={(uint32_t*)qob.data(),(uint32_t*)kob.data(),(uint32_t*)vob.data()};std::vector<float>input(1024),oracle(3072),scale(64);for(int i=0;i<1024;i++)input[i]=e4(main[io[i]]);for(int g=0;g<3;g++){auto&src=g==0?hq:(g==1?hk:hv);for(int o=0;o<1024;o++)oracle[g*1024+o]=e4(src[oo[g][o]]);}for(int g=0;g<2;g++)for(int h=0;h<32;h++){std::vector<float>norms(1024);for(int i=0;i<1024;i++){float z=0;for(int d=0;d<32;d++){size_t x=(i*3+g)*1024+h*32+d;float v=e4(mat[x]);z+=v*v;}norms[i]=std::sqrt(z);}std::nth_element(norms.begin(),norms.begin()+512,norms.end());scale[g*32+h]=norms[512];}
 IDXGIFactory6*fac=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&fac)));IDXGIAdapter1*ad=nullptr;DXGI_ADAPTER_DESC1 dd{};for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(fac->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;c->GetDesc1(&dd);if(!(dd.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(dd.Description,L"AMD")){ad=c;break;}c->Release();}if(!ad)return 1;ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(ad,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));std::fwprintf(stderr,L"adapter: %ls\n",dd.Description);
 const char shader[]=R"(
ByteAddressBuffer packedWeights:register(t0);StructuredBuffer<float> input:register(t1),scales:register(t2);RWStructuredBuffer<float> output:register(u0);
float e4(uint v){float s=(v&128)?-1:1;uint e=(v>>3)&15,m=v&7;if(e==0)return s*(m/8.0)*exp2(-6.0);return s*(1+m/8.0)*exp2((int)e-7);}
float W(uint i){uint x=packedWeights.Load(i&~3);return e4((x>>((i&3)*8))&255);}
float fp8(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.);float m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}
[numthreads(32,1,1)]void main(uint3 id:SV_DispatchThreadID){uint h=id.x;float q[32],k[32],v[32];[loop]for(uint d=0;d<32;d++){q[d]=k[d]=v[d]=0;}[loop]for(uint i=0;i<1024;i++){float x=input[i];[loop]for(uint d=0;d<32;d++){uint o=h*32+d;q[d]+=x*W((i*3+0)*1024+o);k[d]+=x*W((i*3+1)*1024+o);v[d]+=x*W((i*3+2)*1024+o);}}float qn=0,kn=0;[loop]for(uint d=0;d<32;d++){qn+=q[d]*q[d];kn+=k[d]*k[d];}qn=scales[h]*rsqrt(max(qn,1e-12));kn=scales[32+h]*rsqrt(max(kn,1e-12));[loop]for(uint d=0;d<32;d++){uint o=h*32+d;output[o]=fp8(q[d]*qn);output[1024+o]=fp8(k[d]*kn);output[2048+o]=fp8(v[d]);}}
)";
 ID3DBlob*code=nullptr,*err=nullptr;HRESULT cr=D3DCompile(shader,sizeof(shader)-1,nullptr,nullptr,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&err);if(err){std::fwrite(err->GetBufferPointer(),1,err->GetBufferSize(),stderr);err->Release();}ck("compile",cr);D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0]={D3D12_DESCRIPTOR_RANGE_TYPE_SRV,3,0,0,0};ranges[1]={D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,3};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*rsb=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&rsb,&err));ID3D12RootSignature*rs=nullptr;ck("root",dev->CreateRootSignature(0,rsb->GetBufferPointer(),rsb->GetBufferSize(),IID_PPV_ARGS(&rs)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));
 auto hu=hp(D3D12_HEAP_TYPE_UPLOAD),hd=hp(D3D12_HEAP_TYPE_DEFAULT),hrb=hp(D3D12_HEAP_TYPE_READBACK);auto make=[&](UINT64 n,D3D12_HEAP_PROPERTIES*h,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS f){ID3D12Resource*r=nullptr;auto d=bd(n,f);ck("resource",dev->CreateCommittedResource(h,D3D12_HEAP_FLAG_NONE,&d,s,nullptr,IID_PPV_ARGS(&r)));return r;};ID3D12Resource*mr=make(mat.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),*ir=make(input.size()*4,&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),*sr=make(scale.size()*4,&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),*out=make(oracle.size()*4,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*rb=make(oracle.size()*4,&hrb,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE);void*m=nullptr;D3D12_RANGE none{0,0};for(auto item:{std::pair<ID3D12Resource*,std::pair<const void*,size_t>>{mr,{mat.data(),mat.size()}},{ir,{input.data(),input.size()*4}},{sr,{scale.data(),scale.size()*4}}}){item.first->Map(0,&none,&m);std::memcpy(m,item.second.first,item.second.second);item.first->Unmap(0,nullptr);}
 D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,4,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*dh=nullptr;ck("heap",dev->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&dh)));UINT ds=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=dh->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sd{};sd.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sd.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sd.Format=DXGI_FORMAT_R32_TYPELESS;sd.Buffer.NumElements=mat.size()/4;sd.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;dev->CreateShaderResourceView(mr,&sd,h);h.ptr+=ds;sd.Format=DXGI_FORMAT_UNKNOWN;sd.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sd.Buffer.StructureByteStride=4;sd.Buffer.NumElements=input.size();dev->CreateShaderResourceView(ir,&sd,h);h.ptr+=ds;sd.Buffer.NumElements=scale.size();dev->CreateShaderResourceView(sr,&sd,h);h.ptr+=ds;D3D12_UNORDERED_ACCESS_VIEW_DESC ud{};ud.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;ud.Buffer.NumElements=oracle.size();ud.Buffer.StructureByteStride=4;dev->CreateUnorderedAccessView(out,nullptr,&ud,h);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("allocator",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,pso,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={dh};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,dh->GetGPUDescriptorHandleForHeapStart());cl->Dispatch(1,1,1);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=out;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;b.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;b.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&b);cl->CopyBufferRegion(rb,0,out,0,oracle.size()*4);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*f=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));q->Signal(f,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);f->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,oracle.size()*4};rb->Map(0,&all,&m);float*got=(float*)m;std::ofstream metrics(av[10]);for(int g=0;g<3;g++){double ae=0,se=0,sx=0,sy=0,sxx=0,syy=0,sxy=0;size_t exact=0;for(int i=0;i<1024;i++){double x=got[g*1024+i],y=oracle[g*1024+i],z=x-y;ae+=std::abs(z);se+=z*z;exact+=x==y;sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y;}double n=1024,c=(sxy-sx*sy/n)/std::sqrt((sxx-sx*sx/n)*(syy-sy*sy/n));std::printf("%c corr=%.9f MAE=%.9f RMSE=%.9f exact=%.6f\n","QKV"[g],c,ae/n,std::sqrt(se/n),(double)exact/n);metrics<<"QKV"[g]<<" corr="<<c<<" mae="<<ae/n<<" rmse="<<std::sqrt(se/n)<<" exact="<<(double)exact/n<<"\n";}std::printf("submit_to_fence_ms: %.3f\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart);return 0;
}
