#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <dxgi1_6.h>
#include <fstream>
#include <cstdio>
#include <cmath>
#include <cstdint>
#include "native_c32_stage.h"
#include "native_c32_ds.h"
#include "native_c64.h"
#include "native_c64_shift.h"
#include "native_split_window.h"
#include "native_vit_block.h"
#include "native_vit_gather.h"
static ID3D12Device* diagnostic_device=nullptr;
static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("D3D HRESULT="+std::to_string(unsigned(h)));}
static std::vector<float> read(const std::wstring&p){std::ifstream f(p.c_str(),std::ios::binary|std::ios::ate);if(!f)throw std::runtime_error("missing input");auto n=f.tellg();if(n<=0||size_t(n)%4)throw std::runtime_error("input size");std::vector<float>v(size_t(n)/4);f.seekg(0);if(!f.read(reinterpret_cast<char*>(v.data()),n))throw std::runtime_error("truncated input");return v;}
static ID3D12Resource* buffer(ID3D12Device*d,UINT64 n,D3D12_HEAP_TYPE t,D3D12_RESOURCE_STATES s){D3D12_HEAP_PROPERTIES h{};h.Type=t;D3D12_RESOURCE_DESC rd{};rd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;rd.Width=n;rd.Height=1;rd.DepthOrArraySize=rd.MipLevels=1;rd.SampleDesc.Count=1;rd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&h,D3D12_HEAP_FLAG_NONE,&rd,s,nullptr,IID_PPV_ARGS(&r)));return r;}
static void barrier(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER v{};v.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;v.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,a,b};c->ResourceBarrier(1,&v);}
int wmain(int argc,wchar_t**argv){try{
 if(argc<2||argc>3)return 2;const bool with_up48=argc==3&&!wcscmp(argv[2],L"rgb512up48"),with_decoder=with_up48||(argc==3&&!wcscmp(argv[2],L"rgb512decoder")),with_vit=with_decoder||(argc==3&&!wcscmp(argv[2],L"rgb512vit")),with_head=with_vit||(argc==3&&!wcscmp(argv[2],L"rgb256head"));
 const bool with_split=with_head||(argc==3&&!wcscmp(argv[2],L"rgb128split")),with_c256ds=with_split||(argc==3&&!wcscmp(argv[2],L"c256ds")),with_c256shift=with_c256ds||(argc==3&&!wcscmp(argv[2],L"c256shift")),with_c256=with_c256shift||(argc==3&&!wcscmp(argv[2],L"c256")),with_c128ds=with_c256||(argc==3&&!wcscmp(argv[2],L"c128ds")),with_c128shift=with_c128ds||(argc==3&&!wcscmp(argv[2],L"c128shift")),with_c128=with_c128shift||(argc==3&&!wcscmp(argv[2],L"c128")),with_ds64=with_c128||(argc==3&&!wcscmp(argv[2],L"c64ds")),with_shift=with_ds64||(argc==3&&!wcscmp(argv[2],L"c64shift")),with_c64=with_shift||(argc==3&&!wcscmp(argv[2],L"c64")),with_ds=with_c64||(argc==3&&!wcscmp(argv[2],L"ds"));if(argc==3&&!with_ds)return 2;const UINT input_width=with_vit?512:with_head?256:128,input_height=with_vit?512:with_head?256:with_split?128:64;std::wstring dir=argv[1];auto file=[&](const wchar_t*n){return dir+L"\\"+n;};auto rgb=read(file(L"input.rgba32f"));if(rgb.size()!=input_width*input_height*4)throw std::runtime_error("fixture shape");
 IDXGIFactory6*factory=nullptr;ck(CreateDXGIFactory2(0,IID_PPV_ARGS(&factory)));IDXGIAdapter1*adapter=nullptr;for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(factory->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 desc{};c->GetDesc1(&desc);if(desc.VendorId==0x1002&&!(desc.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)){adapter=c;std::wprintf(L"adapter=%ls\n",desc.Description);break;}c->Release();}if(!adapter)throw std::runtime_error("AMD missing");ID3D12Device*device=nullptr;ck(D3D12CreateDevice(adapter,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&device)));
 diagnostic_device=device;auto*input=buffer(device,rgb.size()*4,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);void*m=nullptr;D3D12_RANGE none{};ck(input->Map(0,&none,&m));std::memcpy(m,rgb.data(),rgb.size()*4);input->Unmap(0,nullptr);
 std::vector<float>noise_table;const wchar_t*noise_path=_wgetenv(L"DLSS5_NOISE_TABLE");if(noise_path)noise_table=read(noise_path);
 NativePreblockRuntime pre;pre.Create(device,input,input_width,input_height,read(file(L"block0-ffn.f32")),read(file(L"block0-attention.f32")),dir,true,false,noise_path?&noise_table:nullptr);
 NativeC32Stage stages[4];UINT shifts[]={0,3,1,2};UINT stage_count=with_ds?4:3;ID3D12Resource*source=pre.Downsample();
 for(UINT i=0;i<stage_count;i++){auto prefix=L"block"+std::to_wstring(i+1);stages[i].Create(device,source,input_width/2,input_height/2,shifts[i],read(file((prefix+L"-ffn.f32").c_str())),read(file((prefix+L"-attention.f32").c_str())),dir);source=stages[i].Output();}
 NativeC32Downsample ds;if(with_ds){ds.Create(device,stages[3].PooledWork(),input_width/2,input_height/2,2,read(file(L"block4-ds.f32")),dir);source=ds.Output();}
 NativeC64 c64;if(with_c64){c64.Create(device,source,input_width/4,input_height/4,read(file(L"block5-ffn.f32")),read(file(L"block5-attention.f32")),dir);source=c64.Output();}
 NativeC64Shift shifted[2];if(with_shift)for(UINT i=0;i<2;i++){auto prefix=L"block"+std::to_wstring(i+6);shifted[i].Create(device,source,input_width/4,input_height/4,i?1:3,read(file((prefix+L"-ffn.f32").c_str())),read(file((prefix+L"-attention.f32").c_str())),dir);source=shifted[i].Output();}
 NativeC64Shift block8;NativeC32Downsample ds64;if(with_ds64){block8.Create(device,source,input_width/4,input_height/4,2,read(file(L"block8-ffn.f32")),read(file(L"block8-attention.f32")),dir,true);ds64.Create(device,block8.Output(),input_width/4,input_height/4,0,read(file(L"block8-ds.f32")),dir,true);source=ds64.Output();}
 NativeC64 c128;if(with_c128){c128.Create(device,source,input_width/8,input_height/8,read(file(L"block9-ffn.f32")),read(file(L"block9-attention.f32")),dir,false,128);source=c128.Output();}
 NativeC64Shift c128shift[4];UINT shift128[]={3,1,2,0};if(with_c128shift)for(UINT i=0;i<4;i++){auto prefix=L"block"+std::to_wstring(i+10);c128shift[i].Create(device,source,input_width/8,input_height/8,shift128[i],read(file((prefix+L"-ffn.f32").c_str())),read(file((prefix+L"-attention.f32").c_str())),dir,false,128);source=c128shift[i].Output();}
 NativeC64Shift block14;NativeC32Downsample ds128;if(with_c128ds){block14.Create(device,source,input_width/8,input_height/8,3,read(file(L"block14-ffn.f32")),read(file(L"block14-attention.f32")),dir,true,128);ds128.Create(device,block14.Output(),input_width/8,input_height/8,0,read(file(L"block14-ds.f32")),dir,true,128);source=ds128.Output();}
 NativeC64Shift c256;if(with_c256){c256.Create(device,source,input_width/16,input_height/16,0,read(file(L"block15-ffn.f32")),read(file(L"block15-attention.f32")),dir,false,256);source=c256.Output();}
 NativeC64Shift c256shift[6];UINT shifts256[]={3,1,2,0,3,1};if(with_c256shift)for(UINT i=0;i<6;i++){auto prefix=L"block"+std::to_wstring(i+16);c256shift[i].Create(device,source,input_width/16,input_height/16,shifts256[i],read(file((prefix+L"-ffn.f32").c_str())),read(file((prefix+L"-attention.f32").c_str())),dir,false,256,true);source=c256shift[i].Output();}
 NativeC64Shift block22;NativeC32Downsample ds256;if(with_c256ds){block22.Create(device,source,input_width/16,input_height/16,2,read(file(L"block22-ffn.f32")),read(file(L"block22-attention.f32")),dir,true,256,true);ds256.Create(device,block22.Output(),input_width/16,input_height/16,0,read(file(L"block22-ds.f32")),dir,true,256);source=ds256.Output();}
 const bool with_tail=with_head||_wgetenv(L"DLSS5_SPLIT_TAIL")!=nullptr;if(with_tail&&!with_split)throw std::runtime_error("split tail needs split mode");
 NativeSplitWindow split;if(with_split){split.Create(device,source,input_width/32,input_height/32,0,read(file(L"block23-ffwd.f32")),read(file(L"block23-ffwd-projection.f32")),read(file(L"block23-attention.f32")),dir);source=split.Output();}
 NativeSplitWindow tail[6];const UINT tail_shift[]={3,1,2,0,3,1};
 if(with_tail)for(UINT i=0;i<6;i++){auto prefix=L"block"+std::to_wstring(24+i);tail[i].Create(device,source,input_width/32,input_height/32,tail_shift[i],read(file((prefix+L"-ffwd.f32").c_str())),read(file((prefix+L"-ffwd-projection.f32").c_str())),read(file((prefix+L"-attention.f32").c_str())),dir);source=tail[i].Output();}
 NativeSplitWindow block30;NativeC32Downsample head;
 if(with_head){block30.Create(device,source,input_width/32,input_height/32,2,read(file(L"block30-ffwd.f32")),read(file(L"block30-ffwd-projection.f32")),read(file(L"block30-attention.f32")),dir,true);head.Create(device,block30.Output(),input_width/32,input_height/32,0,read(file(L"head-matrix.f32")),dir,true,512);source=head.Output();}
 NativeVitGather bridge;NativeVitBlock vit[8];
 if(with_vit){std::ifstream f(file(L"hwc-to-vit.i32").c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=65536*4)throw std::runtime_error("bridge map size");std::vector<UINT>map(65536);f.seekg(0);if(!f.read((char*)map.data(),map.size()*4))throw std::runtime_error("bridge map read");bridge.Create(device,source,map,dir);source=bridge.Output();for(UINT i=0;i<8;i++){auto prefix=L"block"+std::to_wstring(i+31)+L"-";vit[i].Create(device,source,64,read(file((prefix+L"expand.f32").c_str())),read(file((prefix+L"contract.f32").c_str())),read(file((prefix+L"qkv.f32").c_str())),read(file((prefix+L"projection.f32").c_str())),dir);source=vit[i].Output();}}
 NativeVitGather decoder_bridge;NativeVitLinear decoder;
 if(with_decoder){std::ifstream f(file(L"vit-to-decoder.i32").c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=65536*4)throw std::runtime_error("decoder map size");std::vector<UINT>map(65536);f.seekg(0);if(!f.read((char*)map.data(),map.size()*4))throw std::runtime_error("decoder map read");decoder_bridge.Create(device,source,map,dir);decoder.Create(device,decoder_bridge.Output(),block30.Output(),64,1024,512,false,read(file(L"decoder39-weights.f32")),dir,true);source=decoder.Output();}
 NativeSplitWindow decoder_split[8];NativeVitLinear up48_projection;NativeC64Shift up48_body;
 if(with_up48){const UINT shifts[]={0,1,3,2,0,1,3,2};for(UINT i=0;i<8;i++){auto prefix=L"block"+std::to_wstring(40+i)+L"-";decoder_split[i].Create(device,source,16,16,shifts[i],read(file((prefix+L"ffwd.f32").c_str())),read(file((prefix+L"ffwd-projection.f32").c_str())),read(file((prefix+L"attention.f32").c_str())),dir);source=decoder_split[i].Output();}up48_projection.Create(device,source,block22.Output(),256,512,256,false,read(file(L"block48-weights.f32")),dir,true);up48_body.Create(device,up48_projection.Output(),32,32,0,read(file(L"block48-ffn.f32")),read(file(L"block48-attention.f32")),dir,false,256);source=up48_body.Output();}
 {auto&cache=NativeShaderCache();std::lock_guard<std::mutex>lock(cache.mutex);std::fprintf(stderr,"shader_compiles=%zu shader_cache_hits=%zu\n",cache.compiles,cache.hits);}
 ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(device->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*allocator=nullptr;ck(device->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&allocator)));ID3D12GraphicsCommandList*c=nullptr;ck(device->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,allocator,nullptr,IID_PPV_ARGS(&c)));ID3D12Fence*fence=nullptr;ck(device->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)));HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);
 const UINT64 bytes=with_up48?32*32*256*4:with_decoder?16*16*512*4:with_vit?64*1024*4:with_head?4*4*1024*4:with_split?4*4*512*4:with_c256ds?4*2*512*4:with_c128ds?8*4*256*4:with_ds64?16*8*128*4:with_ds?32*16*64*4:64*32*32*4;auto*rb=buffer(device,bytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);std::vector<float>result(bytes/4),baseline;
 for(UINT frame=0;frame<3;frame++){
  if(frame){ck(allocator->Reset());ck(c->Reset(allocator,nullptr));}pre.Record(c,0,false);for(UINT i=0;i<stage_count;i++)stages[i].Record(c);if(with_ds)ds.Record(c);if(with_c64)c64.Record(c);if(with_shift)for(auto&s:shifted)s.Record(c);if(with_ds64){block8.Record(c);ds64.Record(c);}if(with_c128)c128.Record(c);if(with_c128shift)for(auto&s:c128shift)s.Record(c);if(with_c128ds){block14.Record(c);ds128.Record(c);}if(with_c256)c256.Record(c);if(with_c256shift)for(auto&s:c256shift)s.Record(c);if(with_c256ds){block22.Record(c);ds256.Record(c);}if(with_split)split.Record(c);
  if(with_tail)for(auto&layer:tail)layer.Record(c);
  if(with_head){block30.Record(c);head.Record(c);}
  if(with_vit){bridge.Record(c);for(auto&layer:vit)layer.Record(c);}
  if(with_decoder){decoder_bridge.Record(c);decoder.Record(c);}
  if(with_up48){for(auto&layer:decoder_split)layer.Record(c);up48_projection.Record(c);up48_body.Record(c);}
  barrier(c,source,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(rb,0,source,0,bytes);barrier(c,source,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);ck(c->Close());ID3D12CommandList*lists[]={c};auto submitted=GetTickCount64();q->ExecuteCommandLists(1,lists);ck(q->Signal(fence,frame+1));ck(fence->SetEventOnCompletion(frame+1,event));if(WaitForSingleObject(event,30000)!=WAIT_OBJECT_0)throw std::runtime_error("GPU timeout");
  std::fprintf(stderr,"frame=%u fence_wait_ms=%llu\n",frame,GetTickCount64()-submitted);
  ck(device->GetDeviceRemovedReason());auto completed=fence->GetCompletedValue();if(completed==UINT64_MAX||completed<frame+1)throw std::runtime_error("GPU fence did not complete successfully");
  D3D12_RANGE all{0,bytes};ck(rb->Map(0,&all,&m));std::memcpy(result.data(),m,bytes);rb->Unmap(0,&none);for(float v:result)if(!std::isfinite(v))throw std::runtime_error("nonfinite result");if(frame==0)baseline=result;else if(result!=baseline)throw std::runtime_error("replay mismatch");std::printf("frame=%u replay=pass\n",frame);
 }
 if(with_split){
  ID3D12Resource*checkpoints[]={pre.Downsample(),ds.Output(),ds64.Output(),ds128.Output(),ds256.Output()};UINT labels[]={0,4,8,14,22};const UINT64 pixels=UINT64(input_width)*input_height;UINT64 counts[]={pixels/4*32,pixels/16*64,pixels/64*128,pixels/256*256,pixels/1024*512};
  for(UINT i=0;i<5;i++){auto n=counts[i]*4;auto*readback=buffer(device,n,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);ck(allocator->Reset());ck(c->Reset(allocator,nullptr));barrier(c,checkpoints[i],D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);c->CopyBufferRegion(readback,0,checkpoints[i],0,n);barrier(c,checkpoints[i],D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);ck(c->Close());ID3D12CommandList*lists[]={c};q->ExecuteCommandLists(1,lists);ck(q->Signal(fence,4+i));ck(fence->SetEventOnCompletion(4+i,event));if(WaitForSingleObject(event,30000)!=WAIT_OBJECT_0)throw std::runtime_error("audit timeout");ck(device->GetDeviceRemovedReason());auto done=fence->GetCompletedValue();if(done==UINT64_MAX||done<4+i)throw std::runtime_error("audit fence incomplete");D3D12_RANGE range{0,SIZE_T(n)};ck(readback->Map(0,&range,&m));std::ofstream audit(file((L"audit-ds"+std::to_wstring(labels[i])+L".f32").c_str()).c_str(),std::ios::binary);if(!audit.write(static_cast<const char*>(m),n))throw std::runtime_error("audit write");readback->Unmap(0,&none);readback->Release();}
 }
 if(with_up48){std::ofstream out(file(L"output-rgb512-upsample48.f32").c_str(),std::ios::binary);if(!out.write(reinterpret_cast<const char*>(result.data()),bytes))throw std::runtime_error("upsample output write");std::printf("native_RGB512_blocks0_48=executed intermediate_cpu_transfers=0\n");return 0;}
 if(with_decoder){std::ofstream out(file(L"output-rgb512-decoder39.f32").c_str(),std::ios::binary);if(!out.write(reinterpret_cast<const char*>(result.data()),bytes))throw std::runtime_error("decoder output write");std::printf("native_RGB512_blocks0_39=executed intermediate_cpu_transfers=0\n");return 0;}
 if(with_vit){std::ofstream out(file(L"output-rgb512-vit.f32").c_str(),std::ios::binary);if(!out.write(reinterpret_cast<const char*>(result.data()),bytes))throw std::runtime_error("ViT output write");std::printf("native_RGB512_blocks0_38=executed intermediate_cpu_transfers=0\n");return 0;}
 if(with_head){std::ofstream out(file(L"output-rgb256-head.f32").c_str(),std::ios::binary);if(!out.write(reinterpret_cast<const char*>(result.data()),bytes))throw std::runtime_error("head output write");std::printf("native_blocks0_30_head=executed intermediate_cpu_transfers=0\n");return 0;}
 if(with_tail){std::ofstream out(file(L"output-rgb128-block29.f32").c_str(),std::ios::binary);if(!out.write(reinterpret_cast<const char*>(result.data()),bytes))throw std::runtime_error("tail output write");std::printf("native_blocks0_29=executed intermediate_cpu_transfers=0\n");return 0;}
 std::ofstream out(file(with_split?L"output-rgb128-split.f32":with_c256ds?L"output-c256-ds.f32":with_c256shift?L"output-c256-shift.f32":with_c256?L"output-c256.f32":with_c128ds?L"output-c128-ds.f32":with_c128shift?L"output-c128-shift.f32":with_c128?L"output-c128.f32":with_ds64?L"output-c64-ds.f32":with_shift?L"output-c64-shift.f32":with_c64?L"output-c64.f32":with_ds?L"output-ds.f32":L"output.f32").c_str(),std::ios::binary);if(!out.write(reinterpret_cast<const char*>(result.data()),bytes))throw std::runtime_error("output write");std::printf("native_blocks0_%u=executed intermediate_cpu_transfers=0\n",with_split?23:with_c256ds?22:with_c256shift?21:with_c256?15:with_c128ds?14:with_c128shift?13:with_c128?9:with_ds64?8:with_shift?7:with_c64?5:stage_count);return 0;
}catch(const std::exception&e){std::fprintf(stderr,"%s\n",e.what());if(diagnostic_device)std::fprintf(stderr,"device_removed_reason=0x%08x\n",unsigned(diagnostic_device->GetDeviceRemovedReason()));return 1;}}
