#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cstdint>
#include <cstdio>
#include <cwchar>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=0x%08lx\n",n,h);ExitProcess(1);}}
static std::vector<uint8_t>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<uint8_t>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
static void tr(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER x{};x.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;x.Transition.pResource=r;x.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;x.Transition.StateBefore=a;x.Transition.StateAfter=b;c->ResourceBarrier(1,&x);}
int wmain(int ac,wchar_t**av){
 if(ac!=7){std::fwprintf(stderr,L"usage: %ls input.f32 output.f32 weight0 weight1 weight2 weight3\n",av[0]);return 2;}constexpr UINT W=1920,H=1088,C=32,N=4;UINT shifts[N]={0,1,1,1};if(wcsstr(av[3],L"block66")){shifts[0]=0;shifts[1]=1;shifts[2]=1;shifts[3]=0;}const UINT tokens=W*H;const UINT64 tb=UINT64(tokens)*C*4,qb=UINT64(tokens)*48*4;auto input=rd(av[1]);if(input.size()!=tb)return 2;std::vector<std::vector<uint8_t>>weights;for(UINT i=0;i<N;i++){weights.push_back(rd(av[3+i]));if(weights.back().size()!=41220)return 2;}
 IDXGIFactory6*f=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;DXGI_ADAPTER_DESC1 ad{};for(UINT i=0;;i++){IDXGIAdapter1*x=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&x))==DXGI_ERROR_NOT_FOUND)break;x->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(ad.Description,L"AMD")){a=x;break;}x->Release();}if(!a)return 1;ID3D12Device*d=nullptr;ck("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));std::fwprintf(stderr,L"adapter: %ls\n",ad.Description);
 auto hu=hp(D3D12_HEAP_TYPE_UPLOAD),hd=hp(D3D12_HEAP_TYPE_DEFAULT),hr=hp(D3D12_HEAP_TYPE_READBACK);auto make=[&](UINT64 n,D3D12_HEAP_PROPERTIES*h,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS fl=D3D12_RESOURCE_FLAG_NONE){ID3D12Resource*r=nullptr;auto z=bd(n,fl);ck("resource",d->CreateCommittedResource(h,D3D12_HEAP_FLAG_NONE,&z,s,nullptr,IID_PPV_ARGS(&r)));return r;};ID3D12Resource*in=make(tb,&hu,D3D12_RESOURCE_STATE_GENERIC_READ),*mainb[2]={make(tb,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),make(tb,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS)},*feat=make(tb,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*qkv=make(qb,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*rb=make(tb,&hr,D3D12_RESOURCE_STATE_COPY_DEST);void*m=nullptr;D3D12_RANGE none{0,0};in->Map(0,&none,&m);memcpy(m,input.data(),tb);in->Unmap(0,nullptr);ID3D12Resource*wr[N]{};for(UINT i=0;i<N;i++){wr[i]=make(weights[i].size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ);wr[i]->Map(0,&none,&m);memcpy(m,weights[i].data(),weights[i].size());wr[i]->Unmap(0,nullptr);}
 D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,3,0,0,4}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr,*er=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&er));ID3D12RootSignature*rs=nullptr;ck("root",d->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&rs)));wchar_t dir[MAX_PATH];GetModuleFileNameW(nullptr,dir,MAX_PATH);wchar_t*s=wcsrchr(dir,L'\\');if(s)*s=0;ID3D12PipelineState*pso[N][3]{};const wchar_t*names[3]={L"ffn",L"qkv",L"attention"};const UINT versions[3]={1,2,2};for(UINT b=0;b<N;b++)for(UINT p=0;p<3;p++){wchar_t path[MAX_PATH];std::swprintf(path,MAX_PATH,L"%ls\\shader-cache\\block1-v%u-1920x1088-s%u-%ls.cso",dir,versions[p],shifts[b],names[p]);ID3DBlob*code=nullptr;ck("shader",D3DReadFileToBlob(path,&code));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ck("pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[b][p])));code->Release();}
 D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,N*7,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;ck("heap",d->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&heap)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();for(UINT b=0;b<N;b++){ID3D12Resource*src=b?mainb[(b-1)&1]:in,*dst=mainb[b&1];D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.NumElements=weights[b].size()/4;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;d->CreateShaderResourceView(wr[b],&sv,cpu);cpu.ptr+=step;sv.Format=DXGI_FORMAT_UNKNOWN;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sv.Buffer.StructureByteStride=4;for(auto pair:{std::pair<ID3D12Resource*,UINT64>{src,tb},{feat,tb},{qkv,qb}}){sv.Buffer.NumElements=(UINT)(pair.second/4);d->CreateShaderResourceView(pair.first,&sv,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;for(auto pair:{std::pair<ID3D12Resource*,UINT64>{feat,tb},{dst,tb},{qkv,qb}}){uv.Buffer.NumElements=(UINT)(pair.second/4);d->CreateUnorderedAccessView(pair.first,nullptr,&uv,cpu);cpu.ptr+=step;}}
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("alloc",d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={heap};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);UINT groups=(tokens+63)/64,gx=std::min(groups,65535u),gy=(groups+65534)/65535;for(UINT b=0;b<N;b++){if(b){tr(cl,feat,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);tr(cl,qkv,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);if(b>=2)tr(cl,mainb[b&1],D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);}auto gpu=heap->GetGPUDescriptorHandleForHeapStart();gpu.ptr+=UINT64(b)*7*step;cl->SetComputeRootDescriptorTable(0,gpu);cl->SetPipelineState(pso[b][0]);cl->Dispatch(gx,gy,1);tr(cl,feat,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);cl->SetPipelineState(pso[b][1]);cl->Dispatch(gx,gy,1);tr(cl,qkv,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);cl->SetPipelineState(pso[b][2]);cl->Dispatch(gx,gy,1);tr(cl,mainb[b&1],D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);}ID3D12Resource*final=mainb[1];tr(cl,final,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);cl->CopyBufferRegion(rb,0,final,0,tb);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*fe=nullptr;ck("fence",d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));q->Signal(fe,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);fe->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,(SIZE_T)tb};rb->Map(0,&all,&m);std::ofstream(av[2],std::ios::binary).write((char*)m,tb);std::printf("blocks=4 gpu_plus_copy_ms=%.3f output_floats=%llu\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,(unsigned long long)tb/4);return 0;
}
