#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <algorithm>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=%08lx\n",n,h);ExitProcess(1);}}static std::vector<unsigned char>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<unsigned char>b(n);f.read((char*)b.data(),n);return b;}static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;return h;}static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
int wmain(int ac,wchar_t**av){if(ac!=5)return 2;auto sparse=rd(av[1]),input=rd(av[2]);UINT tiles=_wtoi(av[4]);UINT64 outputs=UINT64(tiles)*2048,outbytes=outputs*4;if(input.size()!=UINT64(tiles)*1024*4||sparse.size()<8196)return 2;UINT nnz=*reinterpret_cast<const UINT*>(sparse.data()+2048*4);
 IDXGIFactory6*f=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){a=c;break;}c->Release();}ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));
 const char s[]=R"(ByteAddressBuffer p:register(t0);StructuredBuffer<float>x:register(t1);RWStructuredBuffer<float>y:register(u0);uint id(uint3 g,uint3 t){return (g.y*65535+g.x)*64+t.x;}[numthreads(64,1,1)]void main(uint3 g:SV_GroupID,uint3 t:SV_GroupThreadID){uint z=id(g,t);if(z>=OUTPUTS)return;uint sample=z/2048,o=z%2048,b=p.Load(o*4),e=p.Load((o+1)*4),ibase=8196,wbase=8196+NNZ*4;float v=0;[loop]for(uint k=b;k<e;k++)v+=x[sample*1024+p.Load(ibase+k*4)]*asfloat(p.Load(wbase+k*4));y[z]=v;})";char os[32],ns[16];sprintf(os,"%llu",(unsigned long long)outputs);sprintf(ns,"%u",nnz);D3D_SHADER_MACRO m[]={{"OUTPUTS",os},{"NNZ",ns},{nullptr,nullptr}};ID3DBlob*cs=nullptr,*er=nullptr;ck("compile",D3DCompile(s,sizeof(s)-1,nullptr,m,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&cs,&er));D3D12_DESCRIPTOR_RANGE r[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,2,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,2}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,r};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&er));ID3D12RootSignature*rs=nullptr;ck("root",dev->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&rs)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={cs->GetBufferPointer(),cs->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));
 auto up=hp(D3D12_HEAP_TYPE_UPLOAD),df=hp(D3D12_HEAP_TYPE_DEFAULT),rh=hp(D3D12_HEAP_TYPE_READBACK);std::vector<unsigned char>*src[]={&sparse,&input};ID3D12Resource*in[2]{};for(int i=0;i<2;i++){auto d=bd(src[i]->size());ck("in",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&in[i])));void*q;D3D12_RANGE z{0,0};in[i]->Map(0,&z,&q);memcpy(q,src[i]->data(),src[i]->size());in[i]->Unmap(0,nullptr);}auto od=bd(outbytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),rbd=bd(outbytes);ID3D12Resource*out=nullptr,*read=nullptr;ck("out",dev->CreateCommittedResource(&df,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));ck("read",dev->CreateCommittedResource(&rh,D3D12_HEAP_FLAG_NONE,&rbd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&read)));D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,3,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*h=nullptr;ck("heap",dev->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&h)));UINT inc=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=h->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;sv.Buffer.NumElements=sparse.size()/4;dev->CreateShaderResourceView(in[0],&sv,cpu);cpu.ptr+=inc;sv.Format=DXGI_FORMAT_UNKNOWN;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sv.Buffer.StructureByteStride=4;sv.Buffer.NumElements=input.size()/4;dev->CreateShaderResourceView(in[1],&sv,cpu);cpu.ptr+=inc;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=outbytes/4;dev->CreateUnorderedAccessView(out,nullptr,&uv,cpu);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("ca",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("cl",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,pso,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*hs[]={h};cl->SetDescriptorHeaps(1,hs);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,h->GetGPUDescriptorHandleForHeapStart());UINT64 groups=(outputs+63)/64;cl->Dispatch((UINT)std::min<UINT64>(groups,65535),(UINT)((groups+65534)/65535),1);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=out;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;b.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;b.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&b);cl->CopyBufferRegion(read,0,out,0,outbytes);cl->Close();LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*fe=nullptr;dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe));q->Signal(fe,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);fe->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);void*map=nullptr;D3D12_RANGE all{0,(SIZE_T)outbytes};read->Map(0,&all,&map);std::ofstream(av[3],std::ios::binary).write((char*)map,outbytes);printf("tiles=%u nnz=%u ms=%.3f bytes=%llu\n",tiles,nnz,1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,(unsigned long long)outbytes);return 0;}
