#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#define DML_TARGET_VERSION_USE_LATEST
#ifndef _Maybenull_
#define _Maybenull_
#endif
#include <DirectML.h>
#include "directml_gemm_runtime.h"
#include <cstdio>
#include <vector>
static const GUID IID_DML_DEVICE={0x6dbd6437,0x96fd,0x423f,{0xa9,0x8c,0xae,0x5e,0x7c,0x2a,0x57,0x3f}},IID_DML_RECORDER={0xe6857a76,0x2e3e,0x4fdd,{0xbf,0xf4,0x5d,0x2b,0xa1,0x0f,0xb4,0x53}};
using CreateFn=HRESULT(WINAPI*)(ID3D12Device*,DML_CREATE_DEVICE_FLAGS,REFIID,void**);
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES x{};x.Type=t;x.CreationNodeMask=x.VisibleNodeMask=1;return x;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f){D3D12_RESOURCE_DESC x{};x.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;x.Width=n;x.Height=1;x.DepthOrArraySize=1;x.MipLevels=1;x.SampleDesc.Count=1;x.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;x.Flags=f;return x;}
static ID3D12Resource* make(ID3D12Device*d,UINT64 n,D3D12_HEAP_TYPE h=D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATES s=D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS){auto p=hp(h);auto b=bd(n,f);ID3D12Resource*r=nullptr;dmlrt_check("resource",d->CreateCommittedResource(&p,D3D12_HEAP_FLAG_NONE,&b,s,nullptr,IID_PPV_ARGS(&r)));return r;}
static void barrier(ID3D12GraphicsCommandList*c,ID3D12Resource*r){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;b.UAV.pResource=r;c->ResourceBarrier(1,&b);}
int main(){constexpr UINT T=2160,H=32,D=32;IDXGIFactory6*f=nullptr;dmlrt_check("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;DXGI_ADAPTER_DESC1 ad{};for(UINT i=0;;i++){IDXGIAdapter1*x=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&x))==DXGI_ERROR_NOT_FOUND)break;x->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(ad.Description,L"AMD")){a=x;break;}x->Release();}if(!a)return 2;ID3D12Device*d=nullptr;dmlrt_check("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));HMODULE module=LoadLibraryW(L"DirectML.dll");auto create=(CreateFn)GetProcAddress(module,"DMLCreateDevice");IDMLDevice*ml=nullptr;dmlrt_check("DMLCreateDevice",create(d,DML_CREATE_DEVICE_FLAG_NONE,IID_DML_DEVICE,(void**)&ml));IDMLCommandRecorder*rec=nullptr;dmlrt_check("recorder",ml->CreateCommandRecorder(IID_DML_RECORDER,(void**)&rec));DmlGemmOperator expand,contract,qkv,qk,av,projection;expand.Create(ml,d,1,T,1024,4096);contract.Create(ml,d,1,T,4096,1024);qkv.Create(ml,d,1,T,1024,3072);qk.Create(ml,d,H,T,D,T);av.Create(ml,d,H,T,T,D);projection.Create(ml,d,1,T,1024,1024);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*queue=nullptr;dmlrt_check("queue",d->CreateCommandQueue(&qd,IID_PPV_ARGS(&queue)));ID3D12CommandAllocator*ca=nullptr;dmlrt_check("allocator",d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;dmlrt_check("list",d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12Fence*fe=nullptr;dmlrt_check("fence",d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 fv=0;auto wait=[&](){dmlrt_check("close",cl->Close());ID3D12CommandList*l[]={cl};queue->ExecuteCommandLists(1,l);queue->Signal(fe,++fv);fe->SetEventOnCompletion(fv,ev);WaitForSingleObject(ev,INFINITE);ca->Reset();cl->Reset(ca,nullptr);};for(auto*o:{&expand,&contract,&qkv,&qk,&av,&projection})o->RecordInitialization(rec,cl);wait();
 UINT64 mainBytes=UINT64(T)*1024*2,branchBytes=UINT64(T)*4096*2,qkvBytes=UINT64(T)*3072*2,qvBytes=UINT64(H)*T*D*2,scoreBytes=UINT64(H)*T*T*2;ID3D12Resource*main=make(d,mainBytes),*ew=make(d,UINT64(1024)*4096*2),*branch=make(d,branchBytes),*cw=make(d,UINT64(4096)*1024*2),*hidden=make(d,mainBytes),*qw=make(d,UINT64(1024)*3072*2),*qkvOut=make(d,qkvBytes),*qr=make(d,qvBytes),*kr=make(d,qvBytes),*vr=make(d,qvBytes),*score=make(d,scoreBytes),*prob=make(d,scoreBytes),*att=make(d,qvBytes),*pw=make(d,UINT64(1024)*1024*2),*final=make(d,mainBytes);std::vector<ID3D12Resource*>resources={main,ew,branch,cw,hidden,qw,qkvOut,qr,kr,vr,score,prob,att,pw,final};
 D3D12_DESCRIPTOR_HEAP_DESC chd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,(UINT)resources.size(),D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*ch=nullptr;dmlrt_check("clear heap",d->CreateDescriptorHeap(&chd,IID_PPV_ARGS(&ch)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=ch->GetCPUDescriptorHandleForHeapStart();for(auto*r:resources){D3D12_UNORDERED_ACCESS_VIEW_DESC v{};v.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;v.Format=DXGI_FORMAT_R32_TYPELESS;v.Buffer.NumElements=(UINT)(r->GetDesc().Width/4);v.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;d->CreateUnorderedAccessView(r,nullptr,&v,cpu);cpu.ptr+=step;}ID3D12DescriptorHeap*hs[]={ch};cl->SetDescriptorHeaps(1,hs);auto gpu=ch->GetGPUDescriptorHandleForHeapStart();cpu=ch->GetCPUDescriptorHandleForHeapStart();UINT zero[4]{};for(auto*r:resources){cl->ClearUnorderedAccessViewUint(gpu,cpu,r,zero,0,nullptr);gpu.ptr+=step;cpu.ptr+=step;}wait();
 expand.Bind(main,ew,branch);contract.Bind(branch,cw,hidden);qkv.Bind(hidden,qw,qkvOut);qk.Bind(qr,kr,score);av.Bind(prob,vr,att);projection.Bind(att,pw,final);D3D12_QUERY_HEAP_DESC qh{};qh.Type=D3D12_QUERY_HEAP_TYPE_TIMESTAMP;qh.Count=7;ID3D12QueryHeap*queries=nullptr;dmlrt_check("queries",d->CreateQueryHeap(&qh,IID_PPV_ARGS(&queries)));ID3D12Resource*readback=make(d,56,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE);DmlGemmOperator*ops[]={&expand,&contract,&qkv,&qk,&av,&projection};ID3D12Resource*outs[]={branch,hidden,qkvOut,score,att,final};cl->EndQuery(queries,D3D12_QUERY_TYPE_TIMESTAMP,0);for(UINT i=0;i<6;i++){ops[i]->Record(rec,cl);barrier(cl,outs[i]);cl->EndQuery(queries,D3D12_QUERY_TYPE_TIMESTAMP,i+1);}cl->ResolveQueryData(queries,D3D12_QUERY_TYPE_TIMESTAMP,0,7,readback,0);wait();UINT64*t=nullptr;D3D12_RANGE range{0,56};readback->Map(0,&range,(void**)&t);UINT64 freq=0;queue->GetTimestampFrequency(&freq);const char*names[]={"expand","contract","qkv","qk","av","projection"};double total=0;for(UINT i=0;i<6;i++){double ms=1000.0*(t[i+1]-t[i])/freq;total+=ms;std::printf("%s_ms=%.6f\n",names[i],ms);}UINT64 bytes=0;for(auto*r:resources)bytes+=r->GetDesc().Width;wprintf(L"adapter=%ls directml_gemms=6 resident_resources=%u resident_mib=%.2f gemm_gpu_ms=%.6f zero_chain=pass\n",ad.Description,(UINT)resources.size(),bytes/1048576.0,total);return 0;}
