#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>

static void ck(const char *n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s: %08lx\n",n,h);ExitProcess(1);}}
static std::vector<uint8_t> read(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<uint8_t>b(n);f.read((char*)b.data(),n);return b;}
static void write(const wchar_t*p,const void*d,size_t n){std::ofstream f(p,std::ios::binary);if(!f)ExitProcess(2);f.write((const char*)d,n);}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
static float e4m3(uint8_t x){float s=(x&128)?-1.f:1.f;unsigned e=(x>>3)&15,m=x&7;return e?s*std::ldexp(1.f,(int)e-7)*(1.f+m/8.f):s*m/512.f;}

int wmain(int argc,wchar_t**argv){
 if(argc!=4&&argc!=5){std::fwprintf(stderr,L"usage: %ls block0-distilled.bin input.rgba32f oracle.fp8 [output.f32]\n",argv[0]);return 2;}
 auto weights=read(argv[1]),input=read(argv[2]),oracle=read(argv[3]);
 if(weights.size()!=2582528||input.empty()||input.size()%(8*8*4*4))return 2;UINT tiles=(UINT)(input.size()/(8*8*4*4));if(oracle.size()!=UINT64(tiles)*2048)return 2;
 IDXGIFactory6*fac=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&fac)));IDXGIAdapter1*ad=nullptr;DXGI_ADAPTER_DESC1 desc{};
 for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(fac->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){ad=c;desc=d;break;}c->Release();}if(!ad)return 1;
 ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(ad,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));std::wprintf(L"adapter: %ls tiles=%u\n",desc.Description,tiles);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*a=nullptr;ck("allocator",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&a)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,a,nullptr,IID_PPV_ARGS(&cl)));
 const char src[]=R"(
ByteAddressBuffer w:register(t0);StructuredBuffer<float> input:register(t1),h1in:register(t2),h2in:register(t3);
RWStructuredBuffer<float> h1:register(u0),h2:register(u1),output:register(u2);
float W(uint i){return asfloat(w.Load(i*4));}float silu(float x){return x/(1+exp(-x));}
[numthreads(64,1,1)]void layer1(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=TILES*256)return;uint tile=z/256,j=z%256;float v=W(49152+j);[loop]for(uint i=0;i<192;i++){uint pixel=i/3,c=i%3;v+=input[tile*256+pixel*4+c]*W(j*192+i);}h1[z]=silu(v);}
[numthreads(64,1,1)]void layer2(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=TILES*256)return;uint tile=z/256,j=z%256;float v=W(114944+j);[loop]for(uint i=0;i<256;i++)v+=h1in[tile*256+i]*W(49408+j*256+i);h2[z]=silu(v);}
[numthreads(64,1,1)]void layer3(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=TILES*2048)return;uint tile=z/2048,j=z%2048;float v=W(639488+j);[loop]for(uint i=0;i<256;i++)v+=h2in[tile*256+i]*W(115200+j*256+i);output[z]=v*W(643584+j)+W(641536+j);}
)";
 char ts[24];std::snprintf(ts,sizeof(ts),"%u",tiles);D3D_SHADER_MACRO macros[]={{"TILES",ts},{nullptr,nullptr}};ID3DBlob*b[3]{},*er=nullptr;const char*names[]={"layer1","layer2","layer3"};for(int i=0;i<3;i++){ck("compile",D3DCompile(src,sizeof(src)-1,nullptr,macros,nullptr,names[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b[i],&er));if(er){er->Release();er=nullptr;}}
 D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0]={D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0};ranges[1]={D3D12_DESCRIPTOR_RANGE_TYPE_UAV,3,0,0,4};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=1;rd.pParameters=&rp;ID3DBlob*rb=nullptr;ck("serialize",D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&rb,&er));ID3D12RootSignature*rs=nullptr;ck("rootsig",dev->CreateRootSignature(0,rb->GetBufferPointer(),rb->GetBufferSize(),IID_PPV_ARGS(&rs)));rb->Release();ID3D12PipelineState*pso[3]{};for(int i=0;i<3;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={b[i]->GetBufferPointer(),b[i]->GetBufferSize()};ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));b[i]->Release();}
 auto up=hp(D3D12_HEAP_TYPE_UPLOAD),de=hp(D3D12_HEAP_TYPE_DEFAULT),re=hp(D3D12_HEAP_TYPE_READBACK);UINT64 hs=UINT64(tiles)*256*4,os=UINT64(tiles)*2048*4;ID3D12Resource*wr,*ir,*h1r,*h2r,*out,*readback;auto wd=bd(weights.size()),id=bd(input.size()),hd=bd(hs,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),od=bd(os,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),rbd=bd(os);ck("wr",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&wd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&wr)));ck("ir",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&id,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&ir)));ck("h1",dev->CreateCommittedResource(&de,D3D12_HEAP_FLAG_NONE,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&h1r)));ck("h2",dev->CreateCommittedResource(&de,D3D12_HEAP_FLAG_NONE,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&h2r)));ck("out",dev->CreateCommittedResource(&de,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));ck("readback",dev->CreateCommittedResource(&re,D3D12_HEAP_FLAG_NONE,&rbd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&readback)));void*m;D3D12_RANGE none{0,0};wr->Map(0,&none,&m);memcpy(m,weights.data(),weights.size());wr->Unmap(0,nullptr);ir->Map(0,&none,&m);memcpy(m,input.data(),input.size());ir->Unmap(0,nullptr);
 D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,7,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*dh=nullptr;ck("descriptors",dev->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&dh)));UINT inc=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=dh->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sd{};sd.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sd.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sd.Format=DXGI_FORMAT_R32_TYPELESS;sd.Buffer.NumElements=(UINT)weights.size()/4;sd.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;dev->CreateShaderResourceView(wr,&sd,h);h.ptr+=inc;sd.Format=DXGI_FORMAT_UNKNOWN;sd.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sd.Buffer.StructureByteStride=4;sd.Buffer.NumElements=(UINT)input.size()/4;dev->CreateShaderResourceView(ir,&sd,h);h.ptr+=inc;sd.Buffer.NumElements=(UINT)hs/4;dev->CreateShaderResourceView(h1r,&sd,h);h.ptr+=inc;dev->CreateShaderResourceView(h2r,&sd,h);h.ptr+=inc;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=(UINT)hs/4;dev->CreateUnorderedAccessView(h1r,nullptr,&uv,h);h.ptr+=inc;dev->CreateUnorderedAccessView(h2r,nullptr,&uv,h);h.ptr+=inc;uv.Buffer.NumElements=(UINT)os/4;dev->CreateUnorderedAccessView(out,nullptr,&uv,h);
 ID3D12DescriptorHeap*heaps[]={dh};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,dh->GetGPUDescriptorHandleForHeapStart());cl->SetPipelineState(pso[0]);cl->Dispatch((tiles*256+63)/64,1,1);D3D12_RESOURCE_BARRIER bar{};bar.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;bar.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;bar.Transition.pResource=h1r;bar.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;bar.Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;cl->ResourceBarrier(1,&bar);cl->SetPipelineState(pso[1]);cl->Dispatch((tiles*256+63)/64,1,1);bar.Transition.pResource=h2r;cl->ResourceBarrier(1,&bar);cl->SetPipelineState(pso[2]);cl->Dispatch((tiles*2048+63)/64,1,1);bar.Transition.pResource=out;bar.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&bar);cl->CopyBufferRegion(readback,0,out,0,os);ck("close",cl->Close());
 LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*lists[]={cl};q->ExecuteCommandLists(1,lists);ID3D12Fence*f=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));q->Signal(f,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);f->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,(SIZE_T)os};readback->Map(0,&all,&m);float*got=(float*)m;double ae=0,se=0,sx=0,sy=0,sxx=0,syy=0,sxy=0;size_t n=oracle.size();for(size_t i=0;i<n;i++){double x=got[i],y=e4m3(oracle[i]),d=x-y;ae+=fabs(d);se+=d*d;sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y;}double corr=(n*sxy-sx*sy)/sqrt((n*sxx-sx*sx)*(n*syy-sy*sy));std::printf("submit_to_fence_ms: %.3f\nMAE: %.7f\nRMSE: %.7f\ncorrelation: %.7f\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,ae/n,sqrt(se/n),corr);if(argc==5){write(argv[4],got,(size_t)os);std::printf("wrote_floats: %llu\n",(unsigned long long)os/4);}return 0;
}
