#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>

static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s: %08lx\n",n,h);ExitProcess(1);}}
static std::vector<unsigned char>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<unsigned char>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}

int wmain(int argc,wchar_t**argv){
 if(argc!=8){std::fwprintf(stderr,L"usage: %ls input.f32 downsample-matrix.f32 enter-matrix.f32 output.f32 width height channels\n",argv[0]);return 2;}
 auto input=rd(argv[1]),down=rd(argv[2]),enter=rd(argv[3]);UINT width=_wtoi(argv[5]),height=_wtoi(argv[6]),channels=_wtoi(argv[7]),out_channels=channels*2;UINT64 pixels=UINT64(width)*height,out_pixels=UINT64(width/2)*(height/2);
 if(!width||!height||width%2||height%2||input.size()!=pixels*channels*4||down.size()!=UINT64(channels)*channels*4||enter.size()!=UINT64(out_channels)*channels*4)return 2;
 IDXGIFactory6*f=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){a=c;break;}c->Release();}if(!a)return 1;ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));
 const char source[]=R"(StructuredBuffer<float> down:register(t0),enter:register(t1),input:register(t2),midin:register(t3);RWStructuredBuffer<float> mid:register(u0),output:register(u1);[numthreads(64,1,1)]void apply_matrix(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=PIXELS*CHANNELS)return;uint p=z/CHANNELS,j=z%CHANNELS;float v=0;[loop]for(uint c=0;c<CHANNELS;c++)v+=input[p*CHANNELS+c]*down[c*CHANNELS+j];mid[z]=v;}[numthreads(64,1,1)]void pool_enter(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=OUTPIXELS*OUTCHANNELS)return;uint p=z/OUTCHANNELS,o=z%OUTCHANNELS,x=p%(WIDTH/2),y=p/(WIDTH/2);float v=0;[loop]for(uint c=0;c<CHANNELS;c++){float q=0;[unroll]for(uint dy=0;dy<2;dy++)for(uint dx=0;dx<2;dx++)q+=midin[((y*2+dy)*WIDTH+x*2+dx)*CHANNELS+c];v+=q*.25*enter[o*CHANNELS+c];}output[z]=v;})";
 char ws[16],ps[32],os[32],cs[16],ocs[16];std::snprintf(ws,sizeof(ws),"%u",width);std::snprintf(ps,sizeof(ps),"%llu",(unsigned long long)pixels);std::snprintf(os,sizeof(os),"%llu",(unsigned long long)out_pixels);std::snprintf(cs,sizeof(cs),"%u",channels);std::snprintf(ocs,sizeof(ocs),"%u",out_channels);D3D_SHADER_MACRO macros[]={{"WIDTH",ws},{"PIXELS",ps},{"OUTPIXELS",os},{"CHANNELS",cs},{"OUTCHANNELS",ocs},{nullptr,nullptr}};ID3DBlob*b[2]{},*err=nullptr;const char*names[]={"apply_matrix","pool_enter"};for(int i=0;i<2;i++){HRESULT hr=D3DCompile(source,sizeof(source)-1,nullptr,macros,nullptr,names[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&b[i],&err);if(FAILED(hr)&&err)std::fprintf(stderr,"%s\n",(const char*)err->GetBufferPointer());ck("compile",hr);if(err){err->Release();err=nullptr;}}
 D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,2,0,0,4}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&err));ID3D12RootSignature*rs=nullptr;ck("root",dev->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&rs)));ID3D12PipelineState*pso[2]{};for(int i=0;i<2;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={b[i]->GetBufferPointer(),b[i]->GetBufferSize()};ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));}
 auto upload=hp(D3D12_HEAP_TYPE_UPLOAD),def=hp(D3D12_HEAP_TYPE_DEFAULT),read=hp(D3D12_HEAP_TYPE_READBACK);std::vector<unsigned char>*bytes[]={&down,&enter,&input};ID3D12Resource*in[3]{};for(int i=0;i<3;i++){auto d=bd(bytes[i]->size());ck("input",dev->CreateCommittedResource(&upload,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&in[i])));void*m;D3D12_RANGE none{0,0};in[i]->Map(0,&none,&m);memcpy(m,bytes[i]->data(),bytes[i]->size());in[i]->Unmap(0,nullptr);}UINT64 mid_bytes=input.size(),out_bytes=out_pixels*out_channels*4;auto md=bd(mid_bytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),od=bd(out_bytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),rbd=bd(out_bytes);ID3D12Resource*mid=nullptr,*out=nullptr,*rb=nullptr;ck("mid",dev->CreateCommittedResource(&def,D3D12_HEAP_FLAG_NONE,&md,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&mid)));ck("out",dev->CreateCommittedResource(&def,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));ck("readback",dev->CreateCommittedResource(&read,D3D12_HEAP_FLAG_NONE,&rbd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&rb)));
 D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,6,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;ck("heap",dev->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));UINT inc=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=heap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Buffer.StructureByteStride=4;for(int i=0;i<3;i++){sv.Buffer.NumElements=bytes[i]->size()/4;dev->CreateShaderResourceView(in[i],&sv,h);h.ptr+=inc;}sv.Buffer.NumElements=mid_bytes/4;dev->CreateShaderResourceView(mid,&sv,h);h.ptr+=inc;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=mid_bytes/4;dev->CreateUnorderedAccessView(mid,nullptr,&uv,h);h.ptr+=inc;uv.Buffer.NumElements=out_bytes/4;dev->CreateUnorderedAccessView(out,nullptr,&uv,h);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("allocator",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={heap};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());cl->SetPipelineState(pso[0]);cl->Dispatch((pixels*channels+63)/64,1,1);D3D12_RESOURCE_BARRIER bar{};bar.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;bar.Transition.pResource=mid;bar.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;bar.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;bar.Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;cl->ResourceBarrier(1,&bar);cl->SetPipelineState(pso[1]);cl->Dispatch((out_pixels*out_channels+63)/64,1,1);bar.Transition.pResource=out;bar.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&bar);cl->CopyBufferRegion(rb,0,out,0,out_bytes);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*lists[]={cl};q->ExecuteCommandLists(1,lists);ID3D12Fence*fence=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)));q->Signal(fence,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);fence->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);void*m=nullptr;D3D12_RANGE all{0,(SIZE_T)out_bytes};rb->Map(0,&all,&m);std::ofstream(argv[4],std::ios::binary).write((char*)m,out_bytes);std::printf("submit_to_fence_ms: %.3f\nwrote: %llu floats shape=%ux%ux%u\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,(unsigned long long)out_bytes/4,width/2,height/2,out_channels);return 0;
}
