#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s: %08lx\n",n,h);ExitProcess(1);}}
static std::vector<unsigned char>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<unsigned char>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
int wmain(int ac,wchar_t**av){if(ac!=6){std::fwprintf(stderr,L"usage: %ls weights.f32 input.f32 output.f32 input_channels output_channels\n",av[0]);return 2;}auto w=rd(av[1]),in=rd(av[2]);UINT ni=_wtoi(av[4]),no=_wtoi(av[5]);if(!ni||!no||w.size()!=UINT64(ni+1)*no*4||in.size()%(ni*4))return 2;UINT64 samples=in.size()/(ni*4),out_bytes=samples*no*4;
 IDXGIFactory6*f=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){a=c;break;}c->Release();}if(!a)return 1;ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));
 const char src[]=R"(StructuredBuffer<float>w:register(t0),input:register(t1);RWStructuredBuffer<float>output:register(u0);[numthreads(64,1,1)]void main(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=SAMPLES*NO)return;uint s=z/NO,o=z%NO;float v=w[NI*NO+o];[loop]for(uint i=0;i<NI;i++)v+=input[s*NI+i]*w[i*NO+o];output[z]=v;})";char ns[16],is[16],os[16];std::snprintf(ns,sizeof(ns),"%llu",(unsigned long long)samples);std::snprintf(is,sizeof(is),"%u",ni);std::snprintf(os,sizeof(os),"%u",no);D3D_SHADER_MACRO m[]={{"SAMPLES",ns},{"NI",is},{"NO",os},{nullptr,nullptr}};ID3DBlob*cs=nullptr,*er=nullptr;ck("compile",D3DCompile(src,sizeof(src)-1,nullptr,m,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&cs,&er));D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,2,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,2}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&er));ID3D12RootSignature*rs=nullptr;ck("root",dev->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&rs)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={cs->GetBufferPointer(),cs->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));
 auto up=hp(D3D12_HEAP_TYPE_UPLOAD),df=hp(D3D12_HEAP_TYPE_DEFAULT),rbh=hp(D3D12_HEAP_TYPE_READBACK);std::vector<unsigned char>*data[]={&w,&in};ID3D12Resource*r[2]{};for(int i=0;i<2;i++){auto d=bd(data[i]->size());ck("input",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&d,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&r[i])));void*p;D3D12_RANGE z{0,0};r[i]->Map(0,&z,&p);memcpy(p,data[i]->data(),data[i]->size());r[i]->Unmap(0,nullptr);}auto od=bd(out_bytes,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),rdsc=bd(out_bytes);ID3D12Resource*out=nullptr,*rb=nullptr;ck("output",dev->CreateCommittedResource(&df,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));ck("readback",dev->CreateCommittedResource(&rbh,D3D12_HEAP_FLAG_NONE,&rdsc,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&rb)));
 D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,3,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*h=nullptr;ck("heap",dev->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&h)));UINT inc=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=h->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Buffer.StructureByteStride=4;for(int i=0;i<2;i++){sv.Buffer.NumElements=data[i]->size()/4;dev->CreateShaderResourceView(r[i],&sv,cpu);cpu.ptr+=inc;}D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=out_bytes/4;dev->CreateUnorderedAccessView(out,nullptr,&uv,cpu);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("alloc",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,pso,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={h};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,h->GetGPUDescriptorHandleForHeapStart());cl->Dispatch((samples*no+63)/64,1,1);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=out;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;b.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;b.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&b);cl->CopyBufferRegion(rb,0,out,0,out_bytes);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*fe=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));q->Signal(fe,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);fe->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);void*p=nullptr;D3D12_RANGE all{0,(SIZE_T)out_bytes};rb->Map(0,&all,&p);std::ofstream(av[3],std::ios::binary).write((char*)p,out_bytes);std::printf("submit_to_fence_ms: %.3f\nwrote: %llu floats samples=%llu %u->%u\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,(unsigned long long)out_bytes/4,(unsigned long long)samples,ni,no);return 0;}
