#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#define DML_TARGET_VERSION_USE_LATEST
#ifndef _Maybenull_
#define _Maybenull_
#endif
#include <DirectML.h>
#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>

static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=0x%08lx\n",n,(unsigned long)h);ExitProcess(1);}}
static const GUID iid_dev={0x6dbd6437,0x96fd,0x423f,{0xa9,0x8c,0xae,0x5e,0x7c,0x2a,0x57,0x3f}},iid_op={0x26caae7a,0x3081,0x4633,{0x95,0x81,0x22,0x6f,0xbe,0x57,0x69,0x5d}},iid_comp={0x6b15e56a,0xbf5c,0x4902,{0x92,0xd8,0xda,0x3a,0x65,0x0a,0xfe,0xa4}},iid_init={0x427c1113,0x435c,0x469c,{0x86,0x76,0x4d,0x5d,0xd0,0x72,0xf8,0x13}},iid_table={0x29c687dc,0xde74,0x4e3b,{0xab,0x00,0x11,0x68,0xf2,0xfc,0x3c,0xfc}},iid_rec={0xe6857a76,0x2e3e,0x4fdd,{0xbf,0xf4,0x5d,0x2b,0xa1,0x0f,0xb4,0x53}};
using CreateFn=HRESULT(WINAPI*)(ID3D12Device*,DML_CREATE_DEVICE_FLAGS,REFIID,void**);
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES x{};x.Type=t;x.CreationNodeMask=x.VisibleNodeMask=1;return x;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC x{};x.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;x.Width=n;x.Height=1;x.DepthOrArraySize=1;x.MipLevels=1;x.SampleDesc.Count=1;x.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;x.Flags=f;return x;}
static ID3D12Resource*buf(ID3D12Device*d,UINT64 n,D3D12_HEAP_TYPE h,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){auto a=hp(h);auto b=bd(n,f);ID3D12Resource*r=nullptr;ck("resource",d->CreateCommittedResource(&a,D3D12_HEAP_FLAG_NONE,&b,s,nullptr,IID_PPV_ARGS(&r)));return r;}
static void ub(ID3D12GraphicsCommandList*c,ID3D12Resource*r){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;b.UAV.pResource=r;c->ResourceBarrier(1,&b);}
static DML_BINDING_PROPERTIES props(IDMLDispatchable*x){DML_BINDING_PROPERTIES p{};using F=void(WINAPI*)(IDMLDispatchable*,DML_BINDING_PROPERTIES*);((F)(*(void***)x)[8])(x,&p);return p;}
static std::vector<unsigned char>readf(const char*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<unsigned char>b(n);f.read((char*)b.data(),n);return b;}

struct Gemm{
 IDMLCompiledOperator*op{};IDMLOperatorInitializer*init{};IDMLBindingTable*table{};ID3D12DescriptorHeap*heap{};UINT count{};
 void create(IDMLDevice*d,ID3D12Device*dx,UINT batch,UINT m,UINT k,UINT n){UINT as[4]={batch,1,m,k},bs[4]={batch,1,k,n},os[4]={batch,1,m,n};DML_BUFFER_TENSOR_DESC ab{DML_TENSOR_DATA_TYPE_FLOAT16,DML_TENSOR_FLAG_NONE,4,as,nullptr,UINT64(batch)*m*k*2,0},bb{DML_TENSOR_DATA_TYPE_FLOAT16,DML_TENSOR_FLAG_NONE,4,bs,nullptr,UINT64(batch)*k*n*2,0},ob{DML_TENSOR_DATA_TYPE_FLOAT16,DML_TENSOR_FLAG_NONE,4,os,nullptr,UINT64(batch)*m*n*2,0};DML_TENSOR_DESC a{DML_TENSOR_TYPE_BUFFER,&ab},b{DML_TENSOR_TYPE_BUFFER,&bb},o{DML_TENSOR_TYPE_BUFFER,&ob};DML_GEMM_OPERATOR_DESC gd{&a,&b,nullptr,&o,DML_MATRIX_TRANSFORM_NONE,DML_MATRIX_TRANSFORM_NONE,1,0,nullptr};DML_OPERATOR_DESC od{DML_OPERATOR_GEMM,&gd};IDMLOperator*raw=nullptr;ck("CreateOperator",d->CreateOperator(&od,iid_op,(void**)&raw));ck("CompileOperator",d->CompileOperator(raw,DML_EXECUTION_FLAG_ALLOW_HALF_PRECISION_COMPUTATION,iid_comp,(void**)&op));IDMLCompiledOperator*ops[]={op};ck("CreateInitializer",d->CreateOperatorInitializer(1,ops,iid_init,(void**)&init));auto ip=props(init),ep=props(op);if(ip.TemporaryResourceSize||ep.TemporaryResourceSize||ep.PersistentResourceSize){std::fprintf(stderr,"unexpected GEMM scratch\n");ExitProcess(3);}count=std::max<UINT>(1,std::max(ip.RequiredDescriptorCount,ep.RequiredDescriptorCount));D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,count,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ck("DML heap",dx->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));DML_BINDING_TABLE_DESC td{init,heap->GetCPUDescriptorHandleForHeapStart(),heap->GetGPUDescriptorHandleForHeapStart(),count};ck("binding table",d->CreateBindingTable(&td,iid_table,(void**)&table));}
 void initialize(IDMLCommandRecorder*r,ID3D12GraphicsCommandList*c){ID3D12DescriptorHeap*h[]={heap};c->SetDescriptorHeaps(1,h);r->RecordDispatch(c,init,table);}
 void bind(ID3D12Resource*a,UINT64 az,ID3D12Resource*b,UINT64 bz,ID3D12Resource*o,UINT64 oz){DML_BINDING_TABLE_DESC td{op,heap->GetCPUDescriptorHandleForHeapStart(),heap->GetGPUDescriptorHandleForHeapStart(),count};ck("binding reset",table->Reset(&td));DML_BUFFER_BINDING bs[2]={{a,0,az},{b,0,bz}},bo{o,0,oz};DML_BINDING_DESC in[3]={{DML_BINDING_TYPE_BUFFER,&bs[0]},{DML_BINDING_TYPE_BUFFER,&bs[1]},{DML_BINDING_TYPE_NONE,nullptr}},out{DML_BINDING_TYPE_BUFFER,&bo};table->BindInputs(3,in);table->BindOutputs(1,&out);}
 void record(IDMLCommandRecorder*r,ID3D12GraphicsCommandList*c){ID3D12DescriptorHeap*h[]={heap};c->SetDescriptorHeaps(1,h);r->RecordDispatch(c,op,table);}
};

int main(int ac,char**av){if(ac!=3){std::fprintf(stderr,"usage: %s qkv.f32 output.f32\n",av[0]);return 2;}constexpr UINT T=2160,H=32,D=32;auto input=readf(av[1]);if(input.size()!=UINT64(T)*3*H*D*4)return 2;
 IDXGIFactory6*fac=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&fac)));IDXGIAdapter1*adp=nullptr;DXGI_ADAPTER_DESC1 ad{};for(UINT i=0;;i++){IDXGIAdapter1*x=nullptr;if(fac->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&x))==DXGI_ERROR_NOT_FOUND)break;x->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(ad.Description,L"AMD")){adp=x;break;}x->Release();}if(!adp)return 3;ID3D12Device*dx=nullptr;ck("device",D3D12CreateDevice(adp,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dx)));D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dx->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("allocator",dx->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dx->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12Fence*fe=nullptr;ck("fence",dx->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);UINT64 fv=0;auto wait=[&](){ck("close",cl->Close());ID3D12CommandList*l[]={cl};q->ExecuteCommandLists(1,l);q->Signal(fe,++fv);fe->SetEventOnCompletion(fv,ev);WaitForSingleObject(ev,INFINITE);ca->Reset();cl->Reset(ca,nullptr);};
 HMODULE mod=LoadLibraryW(L"DirectML.dll");auto create=(CreateFn)GetProcAddress(mod,"DMLCreateDevice");IDMLDevice*dml=nullptr;ck("DMLCreateDevice",create(dx,DML_CREATE_DEVICE_FLAG_NONE,iid_dev,(void**)&dml));IDMLCommandRecorder*rec=nullptr;ck("recorder",dml->CreateCommandRecorder(iid_rec,(void**)&rec));Gemm qk,avgemm;qk.create(dml,dx,H,T,D,T);avgemm.create(dml,dx,H,T,T,D);qk.initialize(rec,cl);avgemm.initialize(rec,cl);wait();
 const UINT64 qvBytes=UINT64(H)*T*D*2,scoreBytes=UINT64(H)*T*T*2,outBytes=UINT64(T)*H*D*4;ID3D12Resource*upload=buf(dx,input.size(),D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ),*src=buf(dx,input.size(),D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_COPY_DEST),*qr=buf(dx,qvBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*kr=buf(dx,qvBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*vr=buf(dx,qvBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*score=buf(dx,scoreBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*prob=buf(dx,scoreBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*att=buf(dx,qvBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*out=buf(dx,outBytes,D3D12_HEAP_TYPE_DEFAULT,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);void*p=nullptr;upload->Map(0,nullptr,&p);std::memcpy(p,input.data(),input.size());upload->Unmap(0,nullptr);cl->CopyResource(src,upload);D3D12_RESOURCE_BARRIER ready{};ready.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;ready.Transition.pResource=src;ready.Transition.StateBefore=D3D12_RESOURCE_STATE_COPY_DEST;ready.Transition.StateAfter=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;ready.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;cl->ResourceBarrier(1,&ready);wait();
 const char*shader=R"(StructuredBuffer<float> input:register(t0);ByteAddressBuffer score:register(t1),attention:register(t2);RWByteAddressBuffer q:register(u0),k:register(u1),v:register(u2),prob:register(u3);RWStructuredBuffer<float> output:register(u4);float h(ByteAddressBuffer b,uint i){uint x=b.Load((i&~1)*2);return f16tof32((x>>((i&1)*16))&65535);}float F(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}[numthreads(64,1,1)]void pack_qv(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=H*T*(D/2))return;uint pair=z%(D/2),x=z/(D/2),t=x%T,head=x/T,d=pair*2;uint q0=(t*3)*H*D+head*D+d,v0=q0+2*H*D;uint qbits=f32tof16(input[q0])|(f32tof16(input[q0+1])<<16),vbits=f32tof16(input[v0])|(f32tof16(input[v0+1])<<16);uint o=(head*T*D+t*D+d)*2;q.Store(o,qbits);v.Store(o,vbits);}[numthreads(64,1,1)]void pack_k(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=H*D*((T+1)/2))return;uint pair=z%((T+1)/2),x=z/((T+1)/2),d=x%D,head=x/D,t=pair*2;uint k0=(t*3+1)*H*D+head*D+d;uint bits=f32tof16(input[k0]);if(t+1<T)bits|=f32tof16(input[k0+3*H*D])<<16;uint o=(head*D*T+d*T+t)*2;k.Store(o,bits);}groupshared float tmp[64];[numthreads(64,1,1)]void softmax(uint3 lane:SV_GroupThreadID,uint3 gid:SV_GroupID){uint query=gid.x,head=gid.y,base=(head*T*T+query*T);float mx=-3.4e38;for(uint key=lane.x;key<T;key+=64)mx=max(mx,h(score,base+key));tmp[lane.x]=mx;GroupMemoryBarrierWithGroupSync();for(uint s=32;s;s>>=1){if(lane.x<s)tmp[lane.x]=max(tmp[lane.x],tmp[lane.x+s]);GroupMemoryBarrierWithGroupSync();}mx=tmp[0];float sum=0;for(uint key=lane.x;key<T;key+=64)sum+=exp(h(score,base+key)-mx);tmp[lane.x]=sum;GroupMemoryBarrierWithGroupSync();for(uint s=32;s;s>>=1){if(lane.x<s)tmp[lane.x]+=tmp[lane.x+s];GroupMemoryBarrierWithGroupSync();}sum=tmp[0];for(uint pair=lane.x;pair<(T+1)/2;pair+=64){uint key=pair*2;uint bits=f32tof16(exp(h(score,base+key)-mx)/sum);if(key+1<T)bits|=f32tof16(exp(h(score,base+key+1)-mx)/sum)<<16;prob.Store((base+key)*2,bits);}}[numthreads(64,1,1)]void unpack(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=H*T*(D/2))return;uint pair=z%(D/2),x=z/(D/2),t=x%T,head=x/T,d=pair*2,i=head*T*D+t*D+d,o=t*H*D+head*D+d;output[o]=F(h(attention,i));output[o+1]=F(h(attention,i+1));})";
 char defs[3][16];std::snprintf(defs[0],16,"%u",T);std::snprintf(defs[1],16,"%u",H);std::snprintf(defs[2],16,"%u",D);D3D_SHADER_MACRO macros[]={{"T",defs[0]},{"H",defs[1]},{"D",defs[2]},{nullptr,nullptr}};const char*entries[4]={"pack_qv","pack_k","softmax","unpack"};ID3DBlob*code[4]{},*err=nullptr;for(int i=0;i<4;i++)ck("compile",D3DCompile(shader,std::strlen(shader),nullptr,macros,nullptr,entries[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code[i],&err));D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,3,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,5,0,0,3}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr;ck("sig",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&err));ID3D12RootSignature*root=nullptr;ck("root",dx->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root)));ID3D12PipelineState*pso[4]{};for(int i=0;i<4;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={code[i]->GetBufferPointer(),code[i]->GetBufferSize()};ck("pso",dx->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));}D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,8,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;ck("heap",dx->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));UINT step=dx->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Buffer.StructureByteStride=4;sv.Buffer.NumElements=input.size()/4;dx->CreateShaderResourceView(src,&sv,cpu);cpu.ptr+=step;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.StructureByteStride=0;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;for(auto x:{std::pair<ID3D12Resource*,UINT64>{score,scoreBytes},{att,qvBytes}}){sv.Buffer.NumElements=x.second/4;dx->CreateShaderResourceView(x.first,&sv,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Format=DXGI_FORMAT_R32_TYPELESS;uv.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;for(auto x:{std::pair<ID3D12Resource*,UINT64>{qr,qvBytes},{kr,qvBytes},{vr,qvBytes},{prob,scoreBytes}}){uv.Buffer.NumElements=x.second/4;dx->CreateUnorderedAccessView(x.first,nullptr,&uv,cpu);cpu.ptr+=step;}uv.Format=DXGI_FORMAT_UNKNOWN;uv.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_NONE;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=outBytes/4;dx->CreateUnorderedAccessView(out,nullptr,&uv,cpu);
 qk.bind(qr,qvBytes,kr,qvBytes,score,scoreBytes);avgemm.bind(prob,scoreBytes,vr,qvBytes,att,qvBytes);D3D12_QUERY_HEAP_DESC qhd{};qhd.Type=D3D12_QUERY_HEAP_TYPE_TIMESTAMP;qhd.Count=6;ID3D12QueryHeap*qh=nullptr;ck("queries",dx->CreateQueryHeap(&qhd,IID_PPV_ARGS(&qh)));ID3D12Resource*qrb=buf(dx,48,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);auto custom=[&](int i,UINT x,UINT y){ID3D12DescriptorHeap*h[]={heap};cl->SetDescriptorHeaps(1,h);cl->SetComputeRootSignature(root);cl->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());cl->SetPipelineState(pso[i]);cl->Dispatch(x,y,1);};auto run=[&](bool timestamps){if(timestamps)cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,0);custom(0,(H*T*(D/2)+63)/64,1);custom(1,(H*D*((T+1)/2)+63)/64,1);ub(cl,qr);ub(cl,kr);ub(cl,vr);if(timestamps)cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,1);qk.record(rec,cl);ub(cl,score);if(timestamps)cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,2);custom(2,T,H);ub(cl,prob);if(timestamps)cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,3);avgemm.record(rec,cl);ub(cl,att);if(timestamps)cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,4);custom(3,(H*T*(D/2)+63)/64,1);ub(cl,out);if(timestamps)cl->EndQuery(qh,D3D12_QUERY_TYPE_TIMESTAMP,5);};run(false);wait();run(true);cl->ResolveQueryData(qh,D3D12_QUERY_TYPE_TIMESTAMP,0,6,qrb,0);D3D12_RESOURCE_BARRIER tr{};tr.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;tr.Transition.pResource=out;tr.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;tr.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;tr.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;cl->ResourceBarrier(1,&tr);ID3D12Resource*rb=buf(dx,outBytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);cl->CopyResource(rb,out);wait();UINT64*ts=nullptr;D3D12_RANGE r{0,48};qrb->Map(0,&r,(void**)&ts);UINT64 freq=0;q->GetTimestampFrequency(&freq);const char*names[5]={"pack","qk","softmax","av","unpack"};double total=0;for(int i=0;i<5;i++){double ms=1000.0*(ts[i+1]-ts[i])/freq;total+=ms;std::printf("%s_ms=%.6f\n",names[i],ms);}D3D12_RANGE all{0,(SIZE_T)outBytes};rb->Map(0,&all,&p);std::ofstream(av[2],std::ios::binary).write((char*)p,outBytes);std::printf("attention_gpu_ms=%.6f output_floats=%llu\n",total,(unsigned long long)outBytes/4);return 0;}
