#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cwchar>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=0x%08lx\n",n,h);ExitProcess(1);}}
static std::vector<uint8_t>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<uint8_t>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
static void tr(ID3D12GraphicsCommandList*c,ID3D12Resource*r,D3D12_RESOURCE_STATES a,D3D12_RESOURCE_STATES b){D3D12_RESOURCE_BARRIER x{};x.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;x.Transition.pResource=r;x.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;x.Transition.StateBefore=a;x.Transition.StateAfter=b;c->ResourceBarrier(1,&x);}
static void ub(ID3D12GraphicsCommandList*c,ID3D12Resource*r){D3D12_RESOURCE_BARRIER x{};x.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;x.UAV.pResource=r;c->ResourceBarrier(1,&x);}
static float e4(uint8_t v){float s=v&128?-1.f:1.f;unsigned e=(v>>3)&15,m=v&7;if(!e)return s*(m/8.f)*std::ldexp(1.f,-6);if(e==15&&m==7)return NAN;return s*(1.f+m/8.f)*std::ldexp(1.f,(int)e-7);}
static size_t add(std::vector<uint8_t>&d,const std::vector<uint8_t>&s){while(d.size()&3)d.push_back(0);size_t o=d.size();d.insert(d.end(),s.begin(),s.end());return o;}
int wmain(int ac,wchar_t**av){
 if(ac!=3){std::fwprintf(stderr,L"usage: %ls block30-or-block30-body.f32 block38.f32\n",av[0]);return 2;}constexpr UINT N=8,T=2160,C=1024;const UINT64 mainBytes=UINT64(T)*C*4,block30BodyBytes=UINT64(68)*120*512*4,branchBytes=UINT64(T)*4096*4,qkvBytes=UINT64(T)*3072*4;auto input=rd(av[1]);const bool predown=input.size()==block30BodyBytes;if(input.size()!=mainBytes&&!predown)return 2;wchar_t dir[MAX_PATH];GetModuleFileNameW(nullptr,dir,MAX_PATH);wchar_t*slash=wcsrchr(dir,L'\\');if(slash)*slash=0;auto path=[&](const wchar_t*name){static wchar_t p[MAX_PATH];std::swprintf(p,MAX_PATH,L"%ls\\%ls",dir,name);return p;};auto pool=predown?rd(path(L"block30-pool-identity.bin")):std::vector<uint8_t>{},enter30=predown?rd(path(L"block30-enter-512x1024.bin")):std::vector<uint8_t>{};
 auto contract=rd(path(L"block31-vit-contract.f16")),contractSkip=rd(path(L"block31-vit-contract-skip.f16")),projection=rd(path(L"block31-vit-projection.f16")),projectionSkip=rd(path(L"block31-vit-projection-skip.f16"));std::vector<std::vector<uint8_t>>packed(N);std::vector<std::vector<float>>scales(N,std::vector<float>(64));
 for(UINT b=0;b<N;b++){UINT id=31+b;wchar_t n[MAX_PATH];std::swprintf(n,MAX_PATH,L"block%u-vit-expand-effective.f16",id);auto expand=rd(path(n));std::swprintf(n,MAX_PATH,id==31?L"block31-qkv-effective.fp8":L"block%u-qkv-main.fp8",id);auto qm=rd(path(n));std::swprintf(n,MAX_PATH,id==31?L"block31-qkv-work-effective.f16":L"block%u-qkv-work.f16",id);auto qw=rd(path(n));if(expand.size()!=1024ull*4096*2||qm.size()!=1024ull*3072||qw.size()!=1024ull*3072*2)return 2;add(packed[b],expand);add(packed[b],contract);add(packed[b],contractSkip);size_t qo=add(packed[b],qm);add(packed[b],qw);add(packed[b],projection);add(packed[b],projectionSkip);for(UINT g=0;g<2;g++)for(UINT h=0;h<32;h++){std::vector<float>norm(1024);for(UINT r=0;r<1024;r++){float sum=0;for(UINT d=0;d<32;d++){float x=e4(packed[b][qo+(r*3+g)*1024+h*32+d]);sum+=x*x;}norm[r]=std::sqrt(sum);}std::nth_element(norm.begin(),norm.begin()+512,norm.end());scales[b][g*32+h]=norm[512];}}
 IDXGIFactory6*f=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));IDXGIAdapter1*a=nullptr;DXGI_ADAPTER_DESC1 ad{};for(UINT i=0;;i++){IDXGIAdapter1*x=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&x))==DXGI_ERROR_NOT_FOUND)break;x->GetDesc1(&ad);if(!(ad.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(ad.Description,L"AMD")){a=x;break;}x->Release();}if(!a)return 1;ID3D12Device*d=nullptr;ck("device",D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));std::fwprintf(stderr,L"adapter: %ls\n",ad.Description);auto hu=hp(D3D12_HEAP_TYPE_UPLOAD),hd=hp(D3D12_HEAP_TYPE_DEFAULT),hr=hp(D3D12_HEAP_TYPE_READBACK);auto make=[&](UINT64 n,D3D12_HEAP_PROPERTIES*h,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS fl=D3D12_RESOURCE_FLAG_NONE){ID3D12Resource*r=nullptr;auto z=bd(n,fl);ck("resource",d->CreateCommittedResource(h,D3D12_HEAP_FLAG_NONE,&z,s,nullptr,IID_PPV_ARGS(&r)));return r;};
 ID3D12Resource*in=make(input.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ),*stagein=predown?make(mainBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS):nullptr,*dsmid=predown?make(block30BodyBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS):nullptr,*mainb[2]={make(mainBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),make(mainBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS)},*branch=make(branchBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*hidden=make(mainBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*qkv=make(qkvBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*attention=make(mainBytes,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*rb=make(mainBytes,&hr,D3D12_RESOURCE_STATE_COPY_DEST);void*m=nullptr;D3D12_RANGE none{0,0};in->Map(0,&none,&m);memcpy(m,input.data(),input.size());in->Unmap(0,nullptr);ID3D12Resource*wr[N]{},*sr[N]{};for(UINT b=0;b<N;b++){wr[b]=make(packed[b].size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ);wr[b]->Map(0,&none,&m);memcpy(m,packed[b].data(),packed[b].size());wr[b]->Unmap(0,nullptr);sr[b]=make(256,&hu,D3D12_RESOURCE_STATE_GENERIC_READ);sr[b]->Map(0,&none,&m);memcpy(m,scales[b].data(),256);sr[b]->Unmap(0,nullptr);}
 ID3D12Resource*poolr=nullptr,*enter30r=nullptr;if(predown){poolr=make(pool.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ);poolr->Map(0,&none,&m);memcpy(m,pool.data(),pool.size());poolr->Unmap(0,nullptr);enter30r=make(enter30.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ);enter30r->Map(0,&none,&m);memcpy(m,enter30.data(),enter30.size());enter30r->Unmap(0,nullptr);}
 D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,3,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,5,0,0,3}};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*sig=nullptr,*er=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&er));ID3D12RootSignature*rs=nullptr;ck("root",d->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&rs)));const wchar_t*sn[5]={L"expand_cs",L"contract_cs",L"qkv_cs",L"attention_cs",L"projection_cs"};ID3D12PipelineState*pso[5]{};for(UINT p=0;p<5;p++){wchar_t n[MAX_PATH];if(p==3)std::swprintf(n,MAX_PATH,L"%ls\\vit-attention-wave32.cso",dir);else std::swprintf(n,MAX_PATH,L"%ls\\shader-cache\\vit-v5-t2160-%ls.cso",dir,sn[p]);ID3DBlob*code=nullptr;ck("shader",D3DReadFileToBlob(n,&code));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ck("pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[p])));code->Release();}
 D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,N*8,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;ck("heap",d->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&heap)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();for(UINT b=0;b<N;b++){ID3D12Resource*src=b?mainb[(b-1)&1]:(predown?stagein:in),*dst=mainb[b&1];D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.NumElements=packed[b].size()/4;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;d->CreateShaderResourceView(wr[b],&sv,cpu);cpu.ptr+=step;sv.Format=DXGI_FORMAT_UNKNOWN;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sv.Buffer.StructureByteStride=4;for(auto pair:{std::pair<ID3D12Resource*,UINT>{src,T*C},{sr[b],64}}){sv.Buffer.NumElements=pair.second;d->CreateShaderResourceView(pair.first,&sv,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;for(auto pair:{std::pair<ID3D12Resource*,UINT64>{branch,branchBytes},{hidden,mainBytes},{qkv,qkvBytes},{attention,mainBytes},{dst,mainBytes}}){uv.Buffer.NumElements=(UINT)(pair.second/4);d->CreateUnorderedAccessView(pair.first,nullptr,&uv,cpu);cpu.ptr+=step;}}
 ID3D12RootSignature*dsrs=nullptr;ID3D12PipelineState*dsps[2]{};ID3D12DescriptorHeap*dsheap=nullptr;if(predown){const char src[]=R"(StructuredBuffer<float>down:register(t0),enter:register(t1),input:register(t2),midin:register(t3);RWStructuredBuffer<float>mid:register(u0),output:register(u1);[numthreads(64,1,1)]void apply_matrix(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=68*120*512)return;uint p=z/512,j=z%512;float v=0;[loop]for(uint c=0;c<512;c++)v+=input[p*512+c]*down[c*512+j];mid[z]=v;}[numthreads(64,1,1)]void pool_enter(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=34*60*1024)return;uint p=z/1024,o=z%1024,x=p%60,y=p/60;float v=0;[loop]for(uint c=0;c<512;c++){float q=0;[unroll]for(uint dy=0;dy<2;dy++)for(uint dx=0;dx<2;dx++)q+=midin[((y*2+dy)*120+x*2+dx)*512+c];v+=q*.25*enter[o*512+c];}output[z]=v;})";ID3DBlob*bc[2]{},*ee=nullptr;const char*en[2]={"apply_matrix","pool_enter"};for(int i=0;i<2;i++){wchar_t cp[MAX_PATH];std::swprintf(cp,MAX_PATH,L"%ls\\\\shader-cache\\\\vit-predown-v1-block30-%hs.cso",dir,en[i]);if(FAILED(D3DReadFileToBlob(cp,&bc[i]))){ck("ds compile",D3DCompile(src,sizeof(src)-1,nullptr,nullptr,nullptr,en[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&bc[i],&ee));ck("ds cache",D3DWriteBlobToFile(bc[i],cp,TRUE));}}D3D12_DESCRIPTOR_RANGE rr[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,2,0,0,4}};D3D12_ROOT_PARAMETER rp2{};rp2.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp2.DescriptorTable={2,rr};D3D12_ROOT_SIGNATURE_DESC rd2{};rd2.NumParameters=1;rd2.pParameters=&rp2;ID3DBlob*ss=nullptr;ck("ds sig",D3D12SerializeRootSignature(&rd2,D3D_ROOT_SIGNATURE_VERSION_1,&ss,&ee));ck("ds root",d->CreateRootSignature(0,ss->GetBufferPointer(),ss->GetBufferSize(),IID_PPV_ARGS(&dsrs)));for(int i=0;i<2;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=dsrs;pd.CS={bc[i]->GetBufferPointer(),bc[i]->GetBufferSize()};ck("ds pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&dsps[i])));}D3D12_DESCRIPTOR_HEAP_DESC hh{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,6,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ck("ds heap",d->CreateDescriptorHeap(&hh,IID_PPV_ARGS(&dsheap)));auto x=dsheap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Buffer.StructureByteStride=4;for(auto pair:{std::pair<ID3D12Resource*,UINT64>{poolr,pool.size()},{enter30r,enter30.size()},{in,input.size()},{dsmid,block30BodyBytes}}){sv.Buffer.NumElements=(UINT)(pair.second/4);d->CreateShaderResourceView(pair.first,&sv,x);x.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=(UINT)(block30BodyBytes/4);d->CreateUnorderedAccessView(dsmid,nullptr,&uv,x);x.ptr+=step;uv.Buffer.NumElements=(UINT)(mainBytes/4);d->CreateUnorderedAccessView(stagein,nullptr,&uv,x);}
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("alloc",d->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",d->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={heap};if(predown){heaps[0]=dsheap;cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(dsrs);cl->SetComputeRootDescriptorTable(0,dsheap->GetGPUDescriptorHandleForHeapStart());auto cg=dsheap->GetGPUDescriptorHandleForHeapStart();auto cc=dsheap->GetCPUDescriptorHandleForHeapStart();cg.ptr+=5*step;cc.ptr+=5*step;FLOAT zero[4]{};cl->ClearUnorderedAccessViewFloat(cg,cc,stagein,zero,0,nullptr);cl->SetPipelineState(dsps[0]);cl->Dispatch((68*120*512+63)/64,1,1);tr(cl,dsmid,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);cl->SetPipelineState(dsps[1]);cl->Dispatch((34*60*1024+63)/64,1,1);tr(cl,stagein,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);}heaps[0]=heap;cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);const UINT dispatch[5]={T*16,T*16,T,0,T*16};ID3D12Resource*uav[5]={branch,hidden,qkv,attention,nullptr};for(UINT b=0;b<N;b++){if(b>=2)tr(cl,mainb[b&1],D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);auto gpu=heap->GetGPUDescriptorHandleForHeapStart();gpu.ptr+=UINT64(b)*8*step;cl->SetComputeRootDescriptorTable(0,gpu);uav[4]=mainb[b&1];for(UINT p=0;p<5;p++){cl->SetPipelineState(pso[p]);if(p==3)cl->Dispatch(T,32,1);else cl->Dispatch(dispatch[p],1,1);ub(cl,uav[p]);}tr(cl,mainb[b&1],D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);}ID3D12Resource*final=mainb[1];tr(cl,final,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_COPY_SOURCE);cl->CopyBufferRegion(rb,0,final,0,mainBytes);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*fe=nullptr;ck("fence",d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fe)));q->Signal(fe,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);fe->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,(SIZE_T)mainBytes};rb->Map(0,&all,&m);std::ofstream(av[2],std::ios::binary).write((char*)m,mainBytes);std::printf("blocks=8 gpu_plus_copy_ms=%.3f output_floats=%llu\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,(unsigned long long)mainBytes/4);return 0;
}
