#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT r){if(FAILED(r)){std::fprintf(stderr,"%s=%08lx\n",n,r);ExitProcess(1);}}static std::vector<uint8_t>rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=f.tellg();f.seekg(0);std::vector<uint8_t>x(n);f.read((char*)x.data(),n);return x;}static float e4(uint8_t v){float s=v&128?-1.f:1.f;unsigned e=(v>>3)&15,m=v&7;if(!e)return s*(m/8.f)*std::ldexp(1.f,-6);if(e==15&&m==7)return NAN;return s*(1.f+m/8.f)*std::ldexp(1.f,(int)e-7);}static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
int wmain(int ac,wchar_t**av){if(ac!=12){std::fwprintf(stderr,L"usage: %ls matrix.f16 skip.f16 inputs outputs input.fp8 residual.fp8 oracle.fp8 input-offs.i32 output-offs.i32 activation metrics.txt\n",av[0]);return 2;}unsigned ni=_wtoi(av[3]),no=_wtoi(av[4]);bool act=_wtoi(av[10])!=0;auto w=rd(av[1]),skipb=rd(av[2]),pin=rd(av[5]),pres=rd(av[6]),por=rd(av[7]),iob=rd(av[8]),oob=rd(av[9]);if(w.size()!=size_t(ni)*no*2||skipb.size()!=size_t(no)*2||pin.size()!=2097152||pres.size()!=2097152||por.size()!=2097152||iob.size()!=size_t(ni)*4||oob.size()!=size_t(no)*4)return 2;auto*io=(uint32_t*)iob.data();auto*oo=(uint32_t*)oob.data();std::vector<float>input(ni),residual(no),oracle(no);for(unsigned i=0;i<ni;i++)input[i]=e4(pin[io[i]]);for(unsigned o=0;o<no;o++){residual[o]=e4(pres[oo[o]]);oracle[o]=e4(por[oo[o]]);}
 IDXGIFactory6*fac=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&fac)));IDXGIAdapter1*ad=nullptr;DXGI_ADAPTER_DESC1 dd{};for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(fac->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;c->GetDesc1(&dd);if(!(dd.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(dd.Description,L"AMD")){ad=c;break;}c->Release();}if(!ad)return 1;ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(ad,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));std::fwprintf(stderr,L"adapter: %ls\n",dd.Description);
 const char shader[]=R"(
ByteAddressBuffer weights:register(t0),skip:register(t1);StructuredBuffer<float> input:register(t2),residual:register(t3);RWStructuredBuffer<float> output:register(u0);float H(ByteAddressBuffer b,uint i){uint x=b.Load((i>>1)*4);return f16tof32((x>>((i&1)*16))&65535);}float fp8(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}[numthreads(64,1,1)]void main(uint3 id:SV_DispatchThreadID){uint o=id.x;if(o>=OUTPUTS)return;float y=0;[loop]for(uint i=0;i<INPUTS;i++){float x=input[i];if(ACTIVATE){x=clamp(x,-4.,4.);x=x*(.89453125+x*(.447265625-.055908203125*abs(x)));}y+=x*H(weights,i*OUTPUTS+o);}output[o]=fp8(y+residual[o]*H(skip,o));}
)";char nis[16],nos[16],acs[4];std::snprintf(nis,sizeof(nis),"%u",ni);std::snprintf(nos,sizeof(nos),"%u",no);std::snprintf(acs,sizeof(acs),"%u",act);D3D_SHADER_MACRO macros[]={{"INPUTS",nis},{"OUTPUTS",nos},{"ACTIVATE",acs},{nullptr,nullptr}};ID3DBlob*code=nullptr,*err=nullptr;HRESULT cr=D3DCompile(shader,sizeof(shader)-1,nullptr,macros,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&err);if(err){std::fwrite(err->GetBufferPointer(),1,err->GetBufferSize(),stderr);err->Release();}ck("compile",cr);D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0]={D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0};ranges[1]={D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,4};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*rsb=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&rsb,&err));ID3D12RootSignature*rs=nullptr;ck("root",dev->CreateRootSignature(0,rsb->GetBufferPointer(),rsb->GetBufferSize(),IID_PPV_ARGS(&rs)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));
 auto hu=hp(D3D12_HEAP_TYPE_UPLOAD),hd=hp(D3D12_HEAP_TYPE_DEFAULT),hb=hp(D3D12_HEAP_TYPE_READBACK);auto make=[&](UINT64 n,D3D12_HEAP_PROPERTIES*h,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS f){ID3D12Resource*r=nullptr;auto d=bd(n,f);ck("resource",dev->CreateCommittedResource(h,D3D12_HEAP_FLAG_NONE,&d,s,nullptr,IID_PPV_ARGS(&r)));return r;};std::vector<uint8_t>inbytes((ni+no)*4);std::memcpy(inbytes.data(),input.data(),ni*4);std::memcpy(inbytes.data()+ni*4,residual.data(),no*4);ID3D12Resource*wr=make(w.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),*sr=make(skipb.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),*ir=make(inbytes.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE),*out=make(no*4,&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),*rb=make(no*4,&hb,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE);void*m=nullptr;D3D12_RANGE none{0,0};for(auto z:{std::pair<ID3D12Resource*,std::pair<const void*,size_t>>{wr,{w.data(),w.size()}},{sr,{skipb.data(),skipb.size()}},{ir,{inbytes.data(),inbytes.size()}}}){z.first->Map(0,&none,&m);std::memcpy(m,z.second.first,z.second.second);z.first->Unmap(0,nullptr);}
 D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,5,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*dh=nullptr;ck("heap",dev->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&dh)));UINT ds=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=dh->GetCPUDescriptorHandleForHeapStart();auto raw=[&](ID3D12Resource*r,UINT n){D3D12_SHADER_RESOURCE_VIEW_DESC s{};s.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;s.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;s.Format=DXGI_FORMAT_R32_TYPELESS;s.Buffer.NumElements=n/4;s.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;dev->CreateShaderResourceView(r,&s,h);h.ptr+=ds;};raw(wr,w.size());raw(sr,skipb.size());for(int j=0;j<2;j++){D3D12_SHADER_RESOURCE_VIEW_DESC s{};s.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;s.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;s.Format=DXGI_FORMAT_UNKNOWN;s.Buffer.FirstElement=j?ni:0;s.Buffer.NumElements=j?no:ni;s.Buffer.StructureByteStride=4;dev->CreateShaderResourceView(ir,&s,h);h.ptr+=ds;}D3D12_UNORDERED_ACCESS_VIEW_DESC u{};u.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;u.Buffer.NumElements=no;u.Buffer.StructureByteStride=4;dev->CreateUnorderedAccessView(out,nullptr,&u,h);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("alloc",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,pso,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={dh};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,dh->GetGPUDescriptorHandleForHeapStart());cl->Dispatch((no+63)/64,1,1);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=out;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;b.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;b.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&b);cl->CopyBufferRegion(rb,0,out,0,no*4);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*f=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));q->Signal(f,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);f->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,no*4};rb->Map(0,&all,&m);float*got=(float*)m;double ae=0,se=0,sx=0,sy=0,sxx=0,syy=0,sxy=0;size_t exact=0;for(unsigned i=0;i<no;i++){double x=got[i],y=oracle[i],z=x-y;ae+=abs(z);se+=z*z;exact+=x==y;sx+=x;sy+=y;sxx+=x*x;syy+=y*y;sxy+=x*y;}double c=(sxy-sx*sy/no)/std::sqrt((sxx-sx*sx/no)*(syy-sy*sy/no));std::printf("corr=%.9f MAE=%.9f RMSE=%.9f exact=%.6f submit_to_fence_ms=%.3f\n",c,ae/no,std::sqrt(se/no),(double)exact/no,1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart);std::ofstream(av[11])<<"corr="<<c<<" mae="<<ae/no<<" rmse="<<std::sqrt(se/no)<<" exact="<<(double)exact/no<<"\n";return 0;}
