#define wmain unused_rgb_test
#include "d3d12_native_game_rgb_test.cpp"
#undef wmain
#include "native_game_submission.h"
int wmain(int argc,wchar_t**argv){try{
 if(argc!=2)return 2;std::wstring dir=argv[1];
 auto read=[&](const wchar_t*name,size_t count){std::vector<float>v(count);std::ifstream f((dir+L"\\"+name).c_str(),std::ios::binary|std::ios::ate);if(!f||f.tellg()!=std::streamoff(count*4))throw std::runtime_error("fixture size");f.seekg(0);if(!f.read((char*)v.data(),count*4))throw std::runtime_error("fixture read");return v;};
 auto history=read(L"history.f32",256),coords=read(L"coordinates.f32",256),oracle=read(L"oracle-half.f32",512);
 IDXGIFactory6*f=nullptr;ck(CreateDXGIFactory2(0,IID_PPV_ARGS(&f)));ID3D12Device*d=nullptr;
 for(UINT i=0;;i++){IDXGIAdapter1*a=nullptr;if(f->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&a))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 info{};a->GetDesc1(&info);if(info.VendorId==0x1002){ck(D3D12CreateDevice(a,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&d)));a->Release();break;}a->Release();}if(!d)throw std::runtime_error("AMD missing");
 auto upload=[&](const std::vector<float>&v){auto*r=buf(d,v.size()*4,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);void*p;D3D12_RANGE none{};ck(r->Map(0,&none,&p));memcpy(p,v.data(),v.size()*4);r->Unmap(0,nullptr);return r;};auto*h=upload(history);auto*xy=upload(coords);
 D3D12_RESOURCE_DESC rd{};rd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;rd.Width=2048;rd.Height=1;rd.DepthOrArraySize=rd.MipLevels=1;rd.SampleDesc.Count=1;rd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;rd.Flags=D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;D3D12_HEAP_PROPERTIES hp{};hp.Type=D3D12_HEAP_TYPE_DEFAULT;ID3D12Resource*out=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&rd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));auto*rb=buf(d,2048,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);
 D3D12_ROOT_PARAMETER p[4]{};p[0].ParameterType=p[1].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;p[1].Descriptor.ShaderRegister=1;p[2].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;p[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;p[3].Constants={0,0,3};D3D12_ROOT_SIGNATURE_DESC rs{};rs.NumParameters=4;rs.pParameters=p;ID3DBlob*code=nullptr,*error=nullptr;ck(D3D12SerializeRootSignature(&rs,D3D_ROOT_SIGNATURE_VERSION_1,&code,&error));ID3D12RootSignature*root=nullptr;ck(d->CreateRootSignature(0,code->GetBufferPointer(),code->GetBufferSize(),IID_PPV_ARGS(&root)));code->Release();if(error)error->Release();code=nullptr;error=nullptr;ck(CompileNativeShader(dir+L"\\native_temporal_sample.hlsl",nullptr,"main",&code,&error));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));code->Release();
 ID3D12CommandQueue*q=nullptr;D3D12_COMMAND_QUEUE_DESC qd{};ck(d->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));NativeGameSubmission submit;submit.Create(q);
 for(UINT frame=0;frame<3;frame++){
 submit.Submit([&](ID3D12GraphicsCommandList*c){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={out,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS};if(frame)c->ResourceBarrier(1,&b);c->SetComputeRootSignature(root);c->SetPipelineState(pso);c->SetComputeRootShaderResourceView(0,h->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,xy->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(2,out->GetGPUVirtualAddress());UINT constants[]={8,8,128};c->SetComputeRoot32BitConstants(3,3,constants,0);c->Dispatch(2,1,1);std::swap(b.Transition.StateBefore,b.Transition.StateAfter);c->ResourceBarrier(1,&b);c->CopyBufferRegion(rb,0,out,0,2048);});
 void*data;D3D12_RANGE range{0,2048},none{};ck(rb->Map(0,&range,&data));auto*v=static_cast<float*>(data);size_t different=0;for(UINT i=0;i<512;i++){if(!std::isfinite(v[i])||std::abs(v[i])>65504)throw std::runtime_error("invalid output");double step=std::ldexp(1.,std::max(v[i]==0?-14:std::ilogb(std::abs(v[i])),-14)-10);float half=float(std::nearbyint(double(v[i])/step)*step);different+=half!=oracle[i];}std::ofstream saved((dir+L"\\gpu.f32").c_str(),std::ios::binary);saved.write((char*)data,2048);rb->Unmap(0,&none);printf("frame=%u half_different=%zu values=512\n",frame,different);fflush(stdout);if(different)throw std::runtime_error("temporal sampling differs");}
 return 0;
}catch(const std::exception&e){fprintf(stderr,"%s\n",e.what());return 1;}}
