#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=%08lx\n",n,h);ExitProcess(1);}}
static std::vector<uint8_t> rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<uint8_t>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=1;d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}
int wmain(int ac,wchar_t**av){if(ac!=5){std::fwprintf(stderr,L"usage: %ls final-readout.bin activation.f32 input.rgba output.ppm\n",av[0]);return 2;}auto w=rd(av[1]);std::fprintf(stderr,"read weights\n");auto x=rd(av[2]);std::fprintf(stderr,"read activation\n");auto rgba=rd(av[3]);constexpr UINT W=256,H=144,T=576;if(w.size()!=1581824||x.size()!=UINT64(T)*2048*4||rgba.size()!=UINT64(W)*H*4)return 2;std::fprintf(stderr,"read inputs\n");
 IDXGIFactory6*fac=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&fac)));IDXGIAdapter1*ad=nullptr;DXGI_ADAPTER_DESC1 dd{};for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(fac->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){ad=c;dd=d;break;}c->Release();}if(!ad)return 1;ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(ad,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));std::wprintf(L"adapter: %ls\n",dd.Description);
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("allocator",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("list",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));
 const char sh[]=R"(ByteAddressBuffer weight:register(t0);StructuredBuffer<float> act:register(t1);ByteAddressBuffer source:register(t2);RWStructuredBuffer<uint> image:register(u0);float F(uint i){return asfloat(weight.Load(i*4));}[numthreads(64,1,1)]void main(uint3 id:SV_DispatchThreadID){uint p=id.x;if(p>=36864)return;uint gx=p%256,gy=p/256,tx=gx/8,ty=gy/8,lx=gx%8,ly=gy%8,tile=ty*32+tx,j=(ly*8+lx)*3;uint src=source.Load(p*4);uint rgb=0;[unroll]for(uint c=0;c<3;c++){float v=F(2048+j+c);[loop]for(uint i=0;i<2048;i++)v+=(act[tile*2048+i]-F(i))*F(2240+i*192+j+c);float orig=((src>>(c*8))&255)/255.0;v=saturate(orig*0.7397+saturate(v)*0.2603);rgb|=(uint)round(v*255)<<(c*8);}image[p]=rgb;})";
 ID3DBlob*cs=nullptr,*er=nullptr;ck("compile",D3DCompile(sh,sizeof(sh)-1,nullptr,nullptr,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&cs,&er));D3D12_DESCRIPTOR_RANGE rr[2]{};rr[0]={D3D12_DESCRIPTOR_RANGE_TYPE_SRV,3,0,0,0};rr[1]={D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,3};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,rr};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*rsb=nullptr;ck("serialize",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&rsb,&er));ID3D12RootSignature*rs=nullptr;ck("rootsig",dev->CreateRootSignature(0,rsb->GetBufferPointer(),rsb->GetBufferSize(),IID_PPV_ARGS(&rs)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=rs;pd.CS={cs->GetBufferPointer(),cs->GetBufferSize()};ID3D12PipelineState*pso=nullptr;ck("pso",dev->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso)));
 auto up=hp(D3D12_HEAP_TYPE_UPLOAD),de=hp(D3D12_HEAP_TYPE_DEFAULT),re=hp(D3D12_HEAP_TYPE_READBACK);ID3D12Resource*wr,*xr,*sr,*out,*rb;auto wd=bd(w.size()),xd=bd(x.size()),sd=bd(rgba.size()),od=bd(UINT64(W)*H*4,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS),rbd=bd(UINT64(W)*H*4);ck("wr",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&wd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&wr)));ck("xr",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&xd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&xr)));ck("sr",dev->CreateCommittedResource(&up,D3D12_HEAP_FLAG_NONE,&sd,D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&sr)));ck("out",dev->CreateCommittedResource(&de,D3D12_HEAP_FLAG_NONE,&od,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&out)));ck("rb",dev->CreateCommittedResource(&re,D3D12_HEAP_FLAG_NONE,&rbd,D3D12_RESOURCE_STATE_COPY_DEST,nullptr,IID_PPV_ARGS(&rb)));void*m;D3D12_RANGE z{0,0};for(auto [r,b]:{std::pair<ID3D12Resource*,std::vector<uint8_t>*>{wr,&w},{xr,&x},{sr,&rgba}}){r->Map(0,&z,&m);memcpy(m,b->data(),b->size());r->Unmap(0,nullptr);}
 D3D12_DESCRIPTOR_HEAP_DESC dhd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,4,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*dh=nullptr;ck("heap",dev->CreateDescriptorHeap(&dhd,IID_PPV_ARGS(&dh)));UINT inc=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=dh->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;sv.Buffer.NumElements=w.size()/4;dev->CreateShaderResourceView(wr,&sv,h);h.ptr+=inc;sv.Format=DXGI_FORMAT_UNKNOWN;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;sv.Buffer.StructureByteStride=4;sv.Buffer.NumElements=x.size()/4;dev->CreateShaderResourceView(xr,&sv,h);h.ptr+=inc;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;sv.Buffer.StructureByteStride=0;sv.Buffer.NumElements=rgba.size()/4;dev->CreateShaderResourceView(sr,&sv,h);h.ptr+=inc;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=W*H;dev->CreateUnorderedAccessView(out,nullptr,&uv,h);
 ID3D12DescriptorHeap*hs[]={dh};cl->SetDescriptorHeaps(1,hs);cl->SetComputeRootSignature(rs);cl->SetComputeRootDescriptorTable(0,dh->GetGPUDescriptorHandleForHeapStart());cl->SetPipelineState(pso);cl->Dispatch((W*H+63)/64,1,1);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=out;b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;b.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;b.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&b);cl->CopyBufferRegion(rb,0,out,0,UINT64(W)*H*4);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*ls[]={cl};q->ExecuteCommandLists(1,ls);ID3D12Fence*f=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));q->Signal(f,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);f->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,W*H*4};rb->Map(0,&all,&m);FILE*o=_wfopen(av[4],L"wb");std::fprintf(o,"P6\n256 144\n255\n");auto*v=(uint32_t*)m;for(UINT i=0;i<W*H;i++){uint8_t c[3]={(uint8_t)v[i],(uint8_t)(v[i]>>8),(uint8_t)(v[i]>>16)};fwrite(c,3,1,o);}fclose(o);std::printf("submit_to_fence_ms: %.3f\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart);return 0;}
