#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <d3dcompiler.h>
#include <cmath>
#include <cstdio>
#include <fstream>
#include <vector>

static void ck(const char*n,HRESULT h){if(FAILED(h)){std::fprintf(stderr,"%s=%08lx\n",n,h);ExitProcess(1);}}
static std::vector<unsigned char> rd(const wchar_t*p){std::ifstream f(p,std::ios::binary|std::ios::ate);if(!f)ExitProcess(2);size_t n=(size_t)f.tellg();f.seekg(0);std::vector<unsigned char>b(n);f.read((char*)b.data(),n);return b;}
static D3D12_HEAP_PROPERTIES hp(D3D12_HEAP_TYPE t){D3D12_HEAP_PROPERTIES h{};h.Type=t;h.CreationNodeMask=h.VisibleNodeMask=1;return h;}
static D3D12_RESOURCE_DESC bd(UINT64 n,D3D12_RESOURCE_FLAGS f=D3D12_RESOURCE_FLAG_NONE){D3D12_RESOURCE_DESC d{};d.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;d.Width=n;d.Height=1;d.DepthOrArraySize=d.MipLevels=1;d.SampleDesc.Count=1;d.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;d.Flags=f;return d;}

int wmain(int argc,wchar_t**argv){
 if(argc!=5&&argc!=7){std::fwprintf(stderr,L"usage: %ls weights.bin input66.f32 oracle3.f32 output3.f32 [width height]\n",argv[0]);return 2;}
 auto weights=rd(argv[1]),input=rd(argv[2]),oracle=rd(argv[3]);const UINT W=argc==7?_wtoi(argv[5]):256,H=argc==7?_wtoi(argv[6]):144,N=W*H;
 if(weights.size()!=32963ull*4||input.size()!=N*66ull*4||oracle.size()!=N*3ull*4)return 2;
 IDXGIFactory6*fac=nullptr;ck("factory",CreateDXGIFactory2(0,IID_PPV_ARGS(&fac)));IDXGIAdapter1*ad=nullptr;DXGI_ADAPTER_DESC1 desc{};
 for(UINT i=0;;i++){IDXGIAdapter1*c=nullptr;if(fac->EnumAdapterByGpuPreference(i,DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE,IID_PPV_ARGS(&c))==DXGI_ERROR_NOT_FOUND)break;DXGI_ADAPTER_DESC1 d{};c->GetDesc1(&d);if(!(d.Flags&DXGI_ADAPTER_FLAG_SOFTWARE)&&wcsstr(d.Description,L"AMD")){ad=c;desc=d;break;}c->Release();}if(!ad)return 1;
 ID3D12Device*dev=nullptr;ck("device",D3D12CreateDevice(ad,D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&dev)));std::wprintf(L"adapter: %ls\n",desc.Description);
 const char src[]=R"(
ByteAddressBuffer w:register(t0);StructuredBuffer<float> inp:register(t1);RWStructuredBuffer<float> outp:register(u0);float Wt(uint i){return asfloat(w.Load(i*4));}
float erf1(float x){float s=x<0?-1:1,a=abs(x),t=1/(1+.3275911*a);float y=1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+.254829592)*t)*exp(-a*a);return s*y;}float gelu(float x){return .5*x*(1+erf1(x*.7071067811865476));}
uint ix(int x,int y,uint c,uint channels){x=clamp(x,0,int(WIDTH)-1);y=clamp(y,0,int(HEIGHT)-1);return (y*WIDTH+x)*channels+c;}
[numthreads(64,1,1)]void l0(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=N*32)return;uint p=z/32,o=z%32,x=p%WIDTH,y=p/WIDTH;float v=Wt(19008+o);[loop]for(int dy=-1;dy<=1;dy++)[loop]for(int dx=-1;dx<=1;dx++)[loop]for(uint c=0;c<66;c++)v+=inp[ix(x+dx,y+dy,c,66)]*Wt(((o*66+c)*3+(dy+1))*3+dx+1);outp[z]=gelu(v);}
[numthreads(64,1,1)]void l1(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=N*32)return;uint p=z/32,o=z%32,x=p%WIDTH,y=p/WIDTH;float v=Wt(28256+o);[loop]for(int dy=-1;dy<=1;dy++)[loop]for(int dx=-1;dx<=1;dx++)[loop]for(uint c=0;c<32;c++)v+=inp[ix(x+dx,y+dy,c,32)]*Wt(19040+((o*32+c)*3+(dy+1))*3+dx+1);outp[z]=gelu(v);}
[numthreads(64,1,1)]void l2(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=N*16)return;uint p=z/16,o=z%16,x=p%WIDTH,y=p/WIDTH;float v=Wt(32896+o);[loop]for(int dy=-1;dy<=1;dy++)[loop]for(int dx=-1;dx<=1;dx++)[loop]for(uint c=0;c<32;c++)v+=inp[ix(x+dx,y+dy,c,32)]*Wt(28288+((o*32+c)*3+(dy+1))*3+dx+1);outp[z]=gelu(v);}
[numthreads(64,1,1)]void l3(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=N*3)return;uint p=z/3,o=z%3;float v=Wt(32960+o);[loop]for(uint c=0;c<16;c++)v+=inp[p*16+c]*Wt(32912+o*16+c);outp[z]=v;}
)";
 char ns[32],ws[16],hs[16];std::snprintf(ns,sizeof(ns),"%u",N);std::snprintf(ws,sizeof(ws),"%u",W);std::snprintf(hs,sizeof(hs),"%u",H);D3D_SHADER_MACRO macros[]={{"N",ns},{"WIDTH",ws},{"HEIGHT",hs},{nullptr,nullptr}};ID3DBlob*cs[4]{},*err=nullptr;const char*entry[]={"l0","l1","l2","l3"};for(int i=0;i<4;i++){ck("compile",D3DCompile(src,sizeof(src)-1,nullptr,macros,nullptr,entry[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&cs[i],&err));}
 D3D12_DESCRIPTOR_RANGE ranges[2]{};ranges[0]={D3D12_DESCRIPTOR_RANGE_TYPE_SRV,2,0,0,0};ranges[1]={D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,2};D3D12_ROOT_PARAMETER rp{};rp.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;rp.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rsd{};rsd.NumParameters=1;rsd.pParameters=&rp;ID3DBlob*rsb=nullptr;ck("rs",D3D12SerializeRootSignature(&rsd,D3D_ROOT_SIGNATURE_VERSION_1,&rsb,&err));ID3D12RootSignature*rs=nullptr;ck("rootsig",dev->CreateRootSignature(0,rsb->GetBufferPointer(),rsb->GetBufferSize(),IID_PPV_ARGS(&rs)));ID3D12PipelineState*pso[4]{};for(int i=0;i<4;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC p{};p.pRootSignature=rs;p.CS={cs[i]->GetBufferPointer(),cs[i]->GetBufferSize()};ck("pso",dev->CreateComputePipelineState(&p,IID_PPV_ARGS(&pso[i])));}
 auto hu=hp(D3D12_HEAP_TYPE_UPLOAD),hd=hp(D3D12_HEAP_TYPE_DEFAULT),hr=hp(D3D12_HEAP_TYPE_READBACK);ID3D12Resource*wr,*ir,*buf[4]{},*rb;auto make=[&](UINT64 n,D3D12_HEAP_PROPERTIES*h,D3D12_RESOURCE_STATES s,D3D12_RESOURCE_FLAGS f,ID3D12Resource**r){auto d=bd(n,f);ck("resource",dev->CreateCommittedResource(h,D3D12_HEAP_FLAG_NONE,&d,s,nullptr,IID_PPV_ARGS(r)));};make(weights.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE,&wr);make(input.size(),&hu,D3D12_RESOURCE_STATE_GENERIC_READ,D3D12_RESOURCE_FLAG_NONE,&ir);UINT64 sizes[]={N*32ull*4,N*32ull*4,N*16ull*4,N*3ull*4};for(int i=0;i<4;i++)make(sizes[i],&hd,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS,&buf[i]);make(sizes[3],&hr,D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_FLAG_NONE,&rb);void*m;D3D12_RANGE z{0,0};wr->Map(0,&z,&m);memcpy(m,weights.data(),weights.size());wr->Unmap(0,nullptr);ir->Map(0,&z,&m);memcpy(m,input.data(),input.size());ir->Unmap(0,nullptr);
 D3D12_DESCRIPTOR_HEAP_DESC dh{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,12,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};ID3D12DescriptorHeap*heap=nullptr;ck("heap",dev->CreateDescriptorHeap(&dh,IID_PPV_ARGS(&heap)));UINT inc=dev->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto h=heap->GetCPUDescriptorHandleForHeapStart();for(int pass=0;pass<4;pass++){ID3D12Resource*in=pass?buf[pass-1]:ir;UINT64 ibytes=pass?sizes[pass-1]:input.size();for(ID3D12Resource*r:{wr,in}){D3D12_SHADER_RESOURCE_VIEW_DESC s{};s.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;s.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;s.Buffer.StructureByteStride=4;s.Buffer.NumElements=(UINT)((r==wr?weights.size():ibytes)/4);dev->CreateShaderResourceView(r,&s,h);h.ptr+=inc;}D3D12_UNORDERED_ACCESS_VIEW_DESC u{};u.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;u.Buffer.StructureByteStride=4;u.Buffer.NumElements=(UINT)(sizes[pass]/4);dev->CreateUnorderedAccessView(buf[pass],nullptr,&u,h);h.ptr+=inc;}
 D3D12_COMMAND_QUEUE_DESC qd{};ID3D12CommandQueue*q=nullptr;ck("queue",dev->CreateCommandQueue(&qd,IID_PPV_ARGS(&q)));ID3D12CommandAllocator*ca=nullptr;ck("ca",dev->CreateCommandAllocator(D3D12_COMMAND_LIST_TYPE_DIRECT,IID_PPV_ARGS(&ca)));ID3D12GraphicsCommandList*cl=nullptr;ck("cl",dev->CreateCommandList(0,D3D12_COMMAND_LIST_TYPE_DIRECT,ca,nullptr,IID_PPV_ARGS(&cl)));ID3D12DescriptorHeap*heaps[]={heap};cl->SetDescriptorHeaps(1,heaps);cl->SetComputeRootSignature(rs);auto gh=heap->GetGPUDescriptorHandleForHeapStart();for(int i=0;i<4;i++){D3D12_GPU_DESCRIPTOR_HANDLE g=gh;g.ptr+=UINT64(i*3)*inc;cl->SetComputeRootDescriptorTable(0,g);cl->SetPipelineState(pso[i]);cl->Dispatch((UINT)((sizes[i]/4+63)/64),1,1);D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_UAV;b.UAV.pResource=buf[i];cl->ResourceBarrier(1,&b);}D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition.pResource=buf[3];b.Transition.Subresource=D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;b.Transition.StateBefore=D3D12_RESOURCE_STATE_UNORDERED_ACCESS;b.Transition.StateAfter=D3D12_RESOURCE_STATE_COPY_SOURCE;cl->ResourceBarrier(1,&b);cl->CopyBufferRegion(rb,0,buf[3],0,sizes[3]);ck("close",cl->Close());LARGE_INTEGER fq,t0,t1;QueryPerformanceFrequency(&fq);QueryPerformanceCounter(&t0);ID3D12CommandList*l[]={cl};q->ExecuteCommandLists(1,l);ID3D12Fence*f=nullptr;ck("fence",dev->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&f)));q->Signal(f,1);HANDLE ev=CreateEventW(nullptr,FALSE,FALSE,nullptr);f->SetEventOnCompletion(1,ev);WaitForSingleObject(ev,INFINITE);QueryPerformanceCounter(&t1);D3D12_RANGE all{0,(SIZE_T)sizes[3]};rb->Map(0,&all,&m);auto*got=(float*)m,*want=(float*)oracle.data();double ae=0,se=0,sg=0,sw=0,sp=0;for(UINT64 i=0;i<N*3ull;i++){double d=got[i]-want[i];ae+=fabs(d);se+=d*d;sg+=got[i]*got[i];sw+=want[i]*want[i];sp+=got[i]*want[i];}std::ofstream(argv[4],std::ios::binary).write((char*)got,sizes[3]);std::printf("ms=%.3f MAE=%.9g RMSE=%.9g cosine=%.12g\n",1000.0*(t1.QuadPart-t0.QuadPart)/fq.QuadPart,ae/(N*3),sqrt(se/(N*3)),sp/sqrt(sg*sw));return 0;
}
