#pragma once
class Fp16Crop512RuntimePass {
public:
    void Create(ID3D12Device *device,ID3D12Resource *input,ID3D12Resource *output){
        const char shader[]=R"(ByteAddressBuffer input:register(t0);RWStructuredBuffer<float> output:register(u0);float H(uint i){uint x=input.Load((i&~1)*2);return f16tof32((x>>((i&1)*16))&65535);}[numthreads(64,1,1)]void main(uint3 id:SV_DispatchThreadID){uint i=id.x;if(i>=34*60*512)return;uint p=i/512,c=i%512,x=p%60,y=p/60;output[i]=H((y*64+x)*512+c);})";
        ID3DBlob *code=nullptr,*error=nullptr;dmlrt_check("crop compile",D3DCompile(shader,sizeof(shader)-1,nullptr,nullptr,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&error));
        D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,1,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,1}};D3D12_ROOT_PARAMETER p{};p.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;p.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=1;rd.pParameters=&p;ID3DBlob *sig=nullptr;dmlrt_check("crop signature",D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&error));dmlrt_check("crop root",device->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root_)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root_;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};dmlrt_check("crop pso",device->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso_)));
        D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,2,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};dmlrt_check("crop heap",device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap_)));UINT step=device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap_->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;sv.Buffer.NumElements=40*64*512/2;device->CreateShaderResourceView(input,&sv,cpu);cpu.ptr+=step;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Buffer.StructureByteStride=4;uv.Buffer.NumElements=34*60*512;device->CreateUnorderedAccessView(output,nullptr,&uv,cpu);
    }
    void Record(ID3D12GraphicsCommandList *commands){ID3D12DescriptorHeap *heaps[]={heap_};commands->SetDescriptorHeaps(1,heaps);commands->SetComputeRootSignature(root_);commands->SetComputeRootDescriptorTable(0,heap_->GetGPUDescriptorHandleForHeapStart());commands->SetPipelineState(pso_);commands->Dispatch((34*60*512+63)/64,1,1);}
private:ID3D12RootSignature *root_{};ID3D12PipelineState *pso_{};ID3D12DescriptorHeap *heap_{};
};
