#pragma once
#include "native_split.h"
class NativeVitQkv {
 ID3D12Resource *input{},*weights{},*raw{},*output{};ID3D12RootSignature*root{};ID3D12PipelineState*pso[2]{};UINT count{};bool recorded{};
 static void ck(HRESULT h){if(FAILED(h))throw std::runtime_error("ViT QKV HRESULT="+std::to_string(unsigned(h)));}
 static ID3D12Resource* buffer(ID3D12Device*d,UINT64 bytes,const std::vector<float>*data=nullptr){D3D12_HEAP_PROPERTIES hp{};hp.Type=data?D3D12_HEAP_TYPE_UPLOAD:D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC rd{};rd.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;rd.Width=bytes;rd.Height=1;rd.DepthOrArraySize=rd.MipLevels=1;rd.SampleDesc.Count=1;rd.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;rd.Flags=data?D3D12_RESOURCE_FLAG_NONE:D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;ID3D12Resource*r=nullptr;ck(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&rd,data?D3D12_RESOURCE_STATE_GENERIC_READ:D3D12_RESOURCE_STATE_UNORDERED_ACCESS,nullptr,IID_PPV_ARGS(&r)));if(data){void*p=nullptr;D3D12_RANGE none{};ck(r->Map(0,&none,&p));std::memcpy(p,data->data(),bytes);r->Unmap(0,nullptr);}return r;}
 static void barrier(ID3D12GraphicsCommandList*c,ID3D12Resource*r,bool begin){D3D12_RESOURCE_BARRIER b{};b.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;b.Transition={r,D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,begin?D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE:D3D12_RESOURCE_STATE_UNORDERED_ACCESS,begin?D3D12_RESOURCE_STATE_UNORDERED_ACCESS:D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE};c->ResourceBarrier(1,&b);}
public:
 NativeVitQkv()=default;NativeVitQkv(const NativeVitQkv&)=delete;
 ~NativeVitQkv(){for(auto*r:{input,weights,raw,output})if(r)r->Release();if(root)root->Release();for(auto*p:pso)if(p)p->Release();}
 void Create(ID3D12Device*d,ID3D12Resource*src,UINT tokens,const std::vector<float>&coefficients,const std::wstring&dir){
  if(input||!d||!src||(tokens!=64&&tokens!=256)||coefficients.size()!=3145760)throw std::runtime_error("ViT QKV contract");input=src;input->AddRef();count=tokens;weights=buffer(d,coefficients.size()*4,&coefficients);raw=buffer(d,UINT64(tokens)*3072*4);output=buffer(d,UINT64(tokens)*3072*4);
  D3D12_ROOT_PARAMETER params[4]{};for(UINT i=0;i<2;i++){params[i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;params[i].Descriptor.ShaderRegister=i;}params[2].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;params[3].ParameterType=D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;params[3].Constants={0,0,1};D3D12_ROOT_SIGNATURE_DESC desc{};desc.NumParameters=4;desc.pParameters=params;ID3DBlob*blob=nullptr,*error=nullptr;ck(D3D12SerializeRootSignature(&desc,D3D_ROOT_SIGNATURE_VERSION_1,&blob,&error));ck(d->CreateRootSignature(0,blob->GetBufferPointer(),blob->GetBufferSize(),IID_PPV_ARGS(&root)));blob->Release();if(error)error->Release();
  const char*entries[]={"project","normalize"};for(UINT i=0;i<2;i++){blob=nullptr;error=nullptr;auto hr=CompileNativeShader(dir+L"\\native_vit_qkv.hlsl",nullptr,entries[i],&blob,&error);if(FAILED(hr)){std::string message=error?std::string((const char*)error->GetBufferPointer(),error->GetBufferSize()):"QKV compilation";if(error)error->Release();throw std::runtime_error(message);}if(error)error->Release();D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={blob->GetBufferPointer(),blob->GetBufferSize()};ck(d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));blob->Release();}
 }
 void Record(ID3D12GraphicsCommandList*c){if(recorded){barrier(c,raw,true);barrier(c,output,true);}for(UINT i=0;i<2;i++){c->SetComputeRootSignature(root);c->SetPipelineState(pso[i]);c->SetComputeRootShaderResourceView(0,(i?raw:input)->GetGPUVirtualAddress());c->SetComputeRootShaderResourceView(1,weights->GetGPUVirtualAddress());c->SetComputeRootUnorderedAccessView(2,(i?output:raw)->GetGPUVirtualAddress());c->SetComputeRoot32BitConstants(3,1,&count,0);c->Dispatch((count*(i?96:3072)+63)/64,1,1);barrier(c,i?output:raw,false);}recorded=true;}
 ID3D12Resource* Output()const{return output;}
};
