#include <cuda.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <vector>
static void ck(const char*n,CUresult r){if(!r)return;const char*s=nullptr;cuGetErrorString(r,&s);std::fprintf(stderr,"%s=%d %s\n",n,r,s?s:"?");std::exit(1);}
static std::vector<unsigned char>rd(const char*p,size_t n){std::vector<unsigned char>x(n);std::ifstream f(p,std::ios::binary);if(!f||!f.read((char*)x.data(),n))std::exit(2);return x;}
int main(int ac,char**av){if(ac!=9){std::fprintf(stderr,"usage: %s q k v work aux output work-out aux-out\n",av[0]);return 2;}constexpr size_t A=2097152;auto hq=rd(av[1],A),hk=rd(av[2],A),hv=rd(av[3],A),hw=rd(av[4],A),ha=rd(av[5],A);ck("init",cuInit(0));CUdevice d;ck("dev",cuDeviceGet(&d,0));CUcontext c;ck("ctx",cuDevicePrimaryCtxRetain(&c,d));ck("set",cuCtxSetCurrent(c));CUmodule m;ck("module",cuModuleLoad(&m,"/tmp/dlssnr-cubins/dlssnr-05.cubin"));CUfunction f;ck("function",cuModuleGetFunction(&f,m,"cc_vit_1d_attention_fp8"));CUdeviceptr q[3],work,aux,out;for(auto*p:{&q[0],&q[1],&q[2],&work,&aux,&out}){ck("alloc",cuMemAlloc(p,A));ck("zero",cuMemsetD8(*p,0,A));}ck("q",cuMemcpyHtoD(q[0],hq.data(),A));ck("k",cuMemcpyHtoD(q[1],hk.data(),A));ck("v",cuMemcpyHtoD(q[2],hv.data(),A));ck("work",cuMemcpyHtoD(work,hw.data(),A));ck("aux",cuMemcpyHtoD(aux,ha.data(),A));CUdeviceptr a4=aux+0x1800,a5=aux+0x1e00;uint64_t dims=8ull|(8ull<<32);unsigned char p[0x40]{};std::memcpy(p,&q[0],8);std::memcpy(p+8,&q[1],8);std::memcpy(p+16,&q[2],8);std::memcpy(p+24,&out,8);std::memcpy(p+32,&work,8);std::memcpy(p+40,&a4,8);std::memcpy(p+48,&a5,8);std::memcpy(p+56,&dims,8);void*args[]={p};ck("launch",cuLaunchKernel(f,32,1,1,32,4,1,0,nullptr,args,nullptr));ck("sync",cuCtxSynchronize());std::vector<unsigned char>x(A);for(auto item:{std::pair<const char*,CUdeviceptr>{av[6],out},{av[7],work},{av[8],aux}}){ck("read",cuMemcpyDtoH(x.data(),item.second,A));std::ofstream(item.first,std::ios::binary).write((char*)x.data(),x.size());}return 0;}
