#pragma once
struct VitQkvPack1080Pass {
    ID3D12RootSignature* root{};
    ID3D12PipelineState* pso{};
    ID3D12DescriptorHeap* heap{};
    void Create(ID3D12Device* device, ID3D12Resource* input,
                ID3D12Resource* scales, ID3D12Resource* q,
                ID3D12Resource* k, ID3D12Resource* v,
                UINT64 inputBytes, UINT64 outputBytes) {
        const char* source = R"(
ByteAddressBuffer input:register(t0); StructuredBuffer<float> scales:register(t1);
RWByteAddressBuffer q:register(u0),k:register(u1),v:register(u2);
groupshared float qv[32],kv[32],vv[32],sumv[32];
float H(uint i){uint x=input.Load((i&~1)*2);return f16tof32((x>>((i&1)*16))&65535);}
[numthreads(32,1,1)] void main(uint3 lane:SV_GroupThreadID,uint3 gid:SV_GroupID){
 uint t=gid.x,h=gid.y,d=lane.x,qi=(t*3)*1024+h*32+d,ki=qi+1024,vi=ki+1024;
 qv[d]=H(qi);kv[d]=H(ki);vv[d]=H(vi);sumv[d]=qv[d]*qv[d];GroupMemoryBarrierWithGroupSync();
 for(uint s=16;s;s>>=1){if(d<s)sumv[d]+=sumv[d+s];GroupMemoryBarrierWithGroupSync();}
 float qs=scales[h]*rsqrt(max(sumv[0],1e-12));sumv[d]=kv[d]*kv[d];GroupMemoryBarrierWithGroupSync();
 for(uint s=16;s;s>>=1){if(d<s)sumv[d]+=sumv[d+s];GroupMemoryBarrierWithGroupSync();}
 float ks=scales[32+h]*rsqrt(max(sumv[0],1e-12));qv[d]*=qs;kv[d]*=ks;GroupMemoryBarrierWithGroupSync();
 if((d&1)==0){uint o=(h*T*32+t*32+d)*2;q.Store(o,f32tof16(qv[d])|(f32tof16(qv[d+1])<<16));k.Store(o,f32tof16(kv[d])|(f32tof16(kv[d+1])<<16));v.Store(o,f32tof16(vv[d])|(f32tof16(vv[d+1])<<16));}}
)";
        char tokens[16]; std::snprintf(tokens,sizeof(tokens),"%u",540u);
        D3D_SHADER_MACRO macros[]={{"T",tokens},{nullptr,nullptr}};
        ID3DBlob* code=nullptr,*error=nullptr;
        dmlrt_check("qkv pack compile",D3DCompile(source,std::strlen(source),nullptr,macros,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&error));
        D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,2,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,3,0,0,2}};
        D3D12_ROOT_PARAMETER parameter{};parameter.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;parameter.DescriptorTable={2,ranges};
        D3D12_ROOT_SIGNATURE_DESC rootDesc{};rootDesc.NumParameters=1;rootDesc.pParameters=&parameter;
        ID3DBlob* signature=nullptr;dmlrt_check("qkv pack signature",D3D12SerializeRootSignature(&rootDesc,D3D_ROOT_SIGNATURE_VERSION_1,&signature,&error));
        dmlrt_check("qkv pack root",device->CreateRootSignature(0,signature->GetBufferPointer(),signature->GetBufferSize(),IID_PPV_ARGS(&root)));
        D3D12_COMPUTE_PIPELINE_STATE_DESC pipeline{};pipeline.pRootSignature=root;pipeline.CS={code->GetBufferPointer(),code->GetBufferSize()};
        dmlrt_check("qkv pack pso",device->CreateComputePipelineState(&pipeline,IID_PPV_ARGS(&pso)));
        D3D12_DESCRIPTOR_HEAP_DESC heapDesc{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,5,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};
        dmlrt_check("qkv pack heap",device->CreateDescriptorHeap(&heapDesc,IID_PPV_ARGS(&heap)));
        UINT step=device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();
        D3D12_SHADER_RESOURCE_VIEW_DESC srv{};srv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;srv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;srv.Format=DXGI_FORMAT_R32_TYPELESS;srv.Buffer.NumElements=(UINT)(inputBytes/4);srv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;device->CreateShaderResourceView(input,&srv,cpu);cpu.ptr+=step;
        srv.Format=DXGI_FORMAT_UNKNOWN;srv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_NONE;srv.Buffer.StructureByteStride=4;srv.Buffer.NumElements=64;device->CreateShaderResourceView(scales,&srv,cpu);cpu.ptr+=step;
        D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};uav.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uav.Format=DXGI_FORMAT_R32_TYPELESS;uav.Buffer.NumElements=(UINT)(outputBytes/4);uav.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;
        for(auto* output:{q,k,v}){device->CreateUnorderedAccessView(output,nullptr,&uav,cpu);cpu.ptr+=step;}
    }
    void Record(ID3D12GraphicsCommandList* commands) {
        ID3D12DescriptorHeap* heaps[]={heap};commands->SetDescriptorHeaps(1,heaps);commands->SetComputeRootSignature(root);commands->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());commands->SetPipelineState(pso);commands->Dispatch(540,32,1);
    }
};

struct VitOutput1080Pass {
    ID3D12RootSignature* root{};ID3D12PipelineState* pso[2]{};ID3D12DescriptorHeap* heap{};
    void Create(ID3D12Device* device,ID3D12Resource* attention,ID3D12Resource* projectionRaw,ID3D12Resource* hidden,ID3D12Resource* skip,ID3D12Resource* attentionInput,ID3D12Resource* finalF32,UINT64 mainBytes){
        const char* source=R"(ByteAddressBuffer attention:register(t0),projection:register(t1),hidden:register(t2),skip:register(t3);RWByteAddressBuffer attentionInput:register(u0);RWStructuredBuffer<float> finalOutput:register(u1);float H(ByteAddressBuffer b,uint i){uint x=b.Load((i&~1)*2);return f16tof32((x>>((i&1)*16))&65535);}float F(float x){if(x==0)return 0;float s=x<0?-1:1,a=abs(x);if(a<.015625)return s*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return s*min(exp2(e)*(1+m/8),448.);}[numthreads(64,1,1)]void unpack_attention(uint3 id:SV_DispatchThreadID){uint i=id.x*2;if(i>=T*1024)return;uint t=i/1024,c=i%1024,h=c/32,d=c%32;uint a=(h*T*32+t*32+d);float x=F(H(attention,a)),y=F(H(attention,a+1));attentionInput.Store(i*2,f32tof16(x)|(f32tof16(y)<<16));}[numthreads(64,1,1)]void finish_projection(uint3 id:SV_DispatchThreadID){uint i=id.x;if(i>=T*1024)return;finalOutput[i]=F(H(projection,i)+H(hidden,i)*H(skip,i%1024));})";
        char tokens[16];std::snprintf(tokens,sizeof(tokens),"%u",540u);D3D_SHADER_MACRO macros[]={{"T",tokens},{nullptr,nullptr}};const char*entries[]={"unpack_attention","finish_projection"};ID3DBlob*code[2]{},*error=nullptr;for(int i=0;i<2;i++)dmlrt_check("output compile",D3DCompile(source,std::strlen(source),nullptr,macros,nullptr,entries[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code[i],&error));D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,2,0,0,4}};D3D12_ROOT_PARAMETER parameter{};parameter.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;parameter.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=1;rd.pParameters=&parameter;ID3DBlob*sig=nullptr;dmlrt_check("output signature",D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&error));dmlrt_check("output root",device->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root)));for(int i=0;i<2;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={code[i]->GetBufferPointer(),code[i]->GetBufferSize()};dmlrt_check("output pso",device->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));}D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,6,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};dmlrt_check("output heap",device->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));UINT step=device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC srv{};srv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;srv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;srv.Format=DXGI_FORMAT_R32_TYPELESS;srv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;for(auto x:{std::pair<ID3D12Resource*,UINT64>{attention,mainBytes},{projectionRaw,mainBytes},{hidden,mainBytes},{skip,2048}}){srv.Buffer.NumElements=(UINT)(x.second/4);device->CreateShaderResourceView(x.first,&srv,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};uav.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uav.Format=DXGI_FORMAT_R32_TYPELESS;uav.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;uav.Buffer.NumElements=(UINT)(mainBytes/4);device->CreateUnorderedAccessView(attentionInput,nullptr,&uav,cpu);cpu.ptr+=step;uav.Format=DXGI_FORMAT_UNKNOWN;uav.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_NONE;uav.Buffer.StructureByteStride=4;uav.Buffer.NumElements=(UINT)(mainBytes/2);device->CreateUnorderedAccessView(finalF32,nullptr,&uav,cpu);
    }
    void Record(ID3D12GraphicsCommandList*commands,int which){ID3D12DescriptorHeap*heaps[]={heap};commands->SetDescriptorHeaps(1,heaps);commands->SetComputeRootSignature(root);commands->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());commands->SetPipelineState(pso[which]);commands->Dispatch(which==0?(540*1024+127)/128:(540*1024+63)/64,1,1);}
};

struct VitFront1080Pass {
    ID3D12RootSignature*root{};ID3D12PipelineState*pso[3]{};ID3D12DescriptorHeap*heap{};
    void Create(ID3D12Device*d,ID3D12Resource*source,ID3D12Resource*branch,ID3D12Resource*contractRaw,ID3D12Resource*skip,ID3D12Resource*main,ID3D12Resource*contractInput,ID3D12Resource*hidden,UINT64 mainBytes,UINT64 branchBytes){
        const char*s=R"(StructuredBuffer<float> source:register(t0);ByteAddressBuffer branch:register(t1),contractRaw:register(t2),skip:register(t3);RWByteAddressBuffer mainInput:register(u0),contractInput:register(u1),hidden:register(u2);float H(ByteAddressBuffer b,uint i){uint x=b.Load((i&~1)*2);return f16tof32((x>>((i&1)*16))&65535);}float F(float x){if(x==0)return 0;float q=x<0?-1:1,a=abs(x);if(a<.015625)return q*round(a*512)/512;float e=clamp(floor(log2(a)),-6.,8.),m=round((a/exp2(e)-1)*8);if(m>=8){m=0;e+=1;}return q*min(exp2(e)*(1+m/8),448.);}[numthreads(64,1,1)]void pack_input(uint3 id:SV_DispatchThreadID){uint i=id.x*2;if(i>=T*1024)return;mainInput.Store(i*2,f32tof16(source[i])|(f32tof16(source[i+1])<<16));}[numthreads(64,1,1)]void prepare_contract(uint3 id:SV_DispatchThreadID){uint i=id.x*2;if(i>=T*4096)return;float a=clamp(F(H(branch,i)),-4.,4.),b=clamp(F(H(branch,i+1)),-4.,4.);a=a*(.89453125+a*(.447265625-.055908203125*abs(a)));b=b*(.89453125+b*(.447265625-.055908203125*abs(b)));contractInput.Store(i*2,f32tof16(a)|(f32tof16(b)<<16));}[numthreads(64,1,1)]void finish_contract(uint3 id:SV_DispatchThreadID){uint i=id.x*2;if(i>=T*1024)return;float a=F(H(contractRaw,i)+source[i]*H(skip,i%1024)),b=F(H(contractRaw,i+1)+source[i+1]*H(skip,(i+1)%1024));hidden.Store(i*2,f32tof16(a)|(f32tof16(b)<<16));})";
        char tokens[16];std::snprintf(tokens,sizeof(tokens),"%u",540u);D3D_SHADER_MACRO macros[]={{"T",tokens},{nullptr,nullptr}};const char*entries[]={"pack_input","prepare_contract","finish_contract"};ID3DBlob*code[3]{},*error=nullptr;for(int i=0;i<3;i++)dmlrt_check("front compile",D3DCompile(s,std::strlen(s),nullptr,macros,nullptr,entries[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code[i],&error));D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,3,0,0,4}};D3D12_ROOT_PARAMETER p{};p.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;p.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=1;rd.pParameters=&p;ID3DBlob*sig=nullptr;dmlrt_check("front sig",D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&error));dmlrt_check("front root",d->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root)));for(int i=0;i<3;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={code[i]->GetBufferPointer(),code[i]->GetBufferSize()};dmlrt_check("front pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));}D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,7,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};dmlrt_check("front heap",d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC srv{};srv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;srv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;srv.Format=DXGI_FORMAT_UNKNOWN;srv.Buffer.StructureByteStride=4;srv.Buffer.NumElements=(UINT)(mainBytes/2);d->CreateShaderResourceView(source,&srv,cpu);cpu.ptr+=step;srv.Format=DXGI_FORMAT_R32_TYPELESS;srv.Buffer.StructureByteStride=0;srv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;for(auto x:{std::pair<ID3D12Resource*,UINT64>{branch,branchBytes},{contractRaw,mainBytes},{skip,2048}}){srv.Buffer.NumElements=(UINT)(x.second/4);d->CreateShaderResourceView(x.first,&srv,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};uav.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uav.Format=DXGI_FORMAT_R32_TYPELESS;uav.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;for(auto x:{std::pair<ID3D12Resource*,UINT64>{main,mainBytes},{contractInput,branchBytes},{hidden,mainBytes}}){uav.Buffer.NumElements=(UINT)(x.second/4);d->CreateUnorderedAccessView(x.first,nullptr,&uav,cpu);cpu.ptr+=step;}
    }
    void Record(ID3D12GraphicsCommandList*c,int which){ID3D12DescriptorHeap*h[]={heap};c->SetDescriptorHeaps(1,h);c->SetComputeRootSignature(root);c->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());c->SetPipelineState(pso[which]);UINT values=which==1?540*4096:540*1024;c->Dispatch((values+127)/128,1,1);}
};

struct VitPredown1080Pass {
    ID3D12RootSignature*root{};ID3D12PipelineState*pso[2]{};ID3D12DescriptorHeap*heap{};
    void Create(ID3D12Device*d,ID3D12Resource*down,ID3D12Resource*enter,ID3D12Resource*input,ID3D12Resource*mid,ID3D12Resource*output){
        const char*s=R"(StructuredBuffer<float> down:register(t0),enter:register(t1),input:register(t2),midInput:register(t3);RWStructuredBuffer<float> mid:register(u0),output:register(u1);[numthreads(64,1,1)]void apply_matrix(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=34*60*512)return;uint p=z/512,j=z%512;float v=0;[loop]for(uint c=0;c<512;c++)v+=input[p*512+c]*down[c*512+j];mid[z]=v;}[numthreads(64,1,1)]void pool_enter(uint3 id:SV_DispatchThreadID){uint z=id.x;if(z>=18*30*1024)return;if(z>=17*30*1024){output[z]=0;return;}uint p=z/1024,o=z%1024,x=p%30,y=p/30;float v=0;[loop]for(uint c=0;c<512;c++){float q=0;[unroll]for(uint dy=0;dy<2;dy++)for(uint dx=0;dx<2;dx++)q+=midInput[((y*2+dy)*60+x*2+dx)*512+c];v+=q*.25*enter[o*512+c];}output[z]=v;})";
        const char*entries[]={"apply_matrix","pool_enter"};ID3DBlob*code[2]{},*error=nullptr;for(int i=0;i<2;i++)dmlrt_check("predown compile",D3DCompile(s,std::strlen(s),nullptr,nullptr,nullptr,entries[i],"cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code[i],&error));D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,4,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,2,0,0,4}};D3D12_ROOT_PARAMETER p{};p.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;p.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=1;rd.pParameters=&p;ID3DBlob*sig=nullptr;dmlrt_check("predown sig",D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&error));dmlrt_check("predown root",d->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root)));for(int i=0;i<2;i++){D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root;pd.CS={code[i]->GetBufferPointer(),code[i]->GetBufferSize()};dmlrt_check("predown pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso[i])));}D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,6,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};dmlrt_check("predown heap",d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC srv{};srv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;srv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;srv.Buffer.StructureByteStride=4;for(auto x:{std::pair<ID3D12Resource*,UINT64>{down,UINT64(512)*512*4},{enter,UINT64(512)*1024*4},{input,UINT64(34)*60*512*4},{input,UINT64(34)*60*512*4}}){srv.Buffer.NumElements=(UINT)(x.second/4);d->CreateShaderResourceView(x.first,&srv,cpu);cpu.ptr+=step;}D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};uav.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uav.Buffer.StructureByteStride=4;uav.Buffer.NumElements=34*60*512;d->CreateUnorderedAccessView(mid,nullptr,&uav,cpu);cpu.ptr+=step;uav.Buffer.NumElements=18*30*1024;d->CreateUnorderedAccessView(output,nullptr,&uav,cpu);
    }
    void Record(ID3D12GraphicsCommandList*c,int which){if(which==0)return;ID3D12DescriptorHeap*h[]={heap};c->SetDescriptorHeaps(1,h);c->SetComputeRootSignature(root);c->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());c->SetPipelineState(pso[which]);UINT n=which==0?34*60*512:18*30*1024;c->Dispatch((n+63)/64,1,1);}
};
class VitSoftmax1080Pass {
public:
 void Create(ID3D12Device*d,ID3D12Resource*score,ID3D12Resource*prob,UINT64 bytes){const char*s=R"(ByteAddressBuffer score:register(t0);RWByteAddressBuffer probability:register(u0);groupshared float tmp[64];float H(uint i){uint x=score.Load((i&~1)*2);return f16tof32((x>>((i&1)*16))&65535);}[numthreads(64,1,1)]void main(uint3 lane:SV_GroupThreadID,uint3 gid:SV_GroupID){uint query=gid.x,head=gid.y,base=head*540*540+query*540;float mx=-3.4e38;for(uint key=lane.x;key<540;key+=64)mx=max(mx,H(base+key));tmp[lane.x]=mx;GroupMemoryBarrierWithGroupSync();for(uint z=32;z;z>>=1){if(lane.x<z)tmp[lane.x]=max(tmp[lane.x],tmp[lane.x+z]);GroupMemoryBarrierWithGroupSync();}mx=tmp[0];float sum=0;for(uint key=lane.x;key<540;key+=64)sum+=exp(H(base+key)-mx);tmp[lane.x]=sum;GroupMemoryBarrierWithGroupSync();for(uint z=32;z;z>>=1){if(lane.x<z)tmp[lane.x]+=tmp[lane.x+z];GroupMemoryBarrierWithGroupSync();}sum=tmp[0];for(uint pair=lane.x;pair<270;pair+=64){uint key=pair*2;uint bits=f32tof16(exp(H(base+key)-mx)/sum);if(key+1<540)bits|=f32tof16(exp(H(base+key+1)-mx)/sum)<<16;probability.Store((base+key)*2,bits);}})";ID3DBlob*code=nullptr,*error=nullptr;dmlrt_check("vit softmax compile",D3DCompile(s,std::strlen(s),nullptr,nullptr,nullptr,"main","cs_5_1",D3DCOMPILE_OPTIMIZATION_LEVEL3,0,&code,&error));D3D12_DESCRIPTOR_RANGE ranges[2]={{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,1,0,0,0},{D3D12_DESCRIPTOR_RANGE_TYPE_UAV,1,0,0,1}};D3D12_ROOT_PARAMETER p{};p.ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;p.DescriptorTable={2,ranges};D3D12_ROOT_SIGNATURE_DESC rd{};rd.NumParameters=1;rd.pParameters=&p;ID3DBlob*sig=nullptr;dmlrt_check("vit softmax signature",D3D12SerializeRootSignature(&rd,D3D_ROOT_SIGNATURE_VERSION_1,&sig,&error));dmlrt_check("vit softmax root",d->CreateRootSignature(0,sig->GetBufferPointer(),sig->GetBufferSize(),IID_PPV_ARGS(&root_)));D3D12_COMPUTE_PIPELINE_STATE_DESC pd{};pd.pRootSignature=root_;pd.CS={code->GetBufferPointer(),code->GetBufferSize()};dmlrt_check("vit softmax pso",d->CreateComputePipelineState(&pd,IID_PPV_ARGS(&pso_)));D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,2,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};dmlrt_check("vit softmax heap",d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap_)));UINT step=d->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);auto cpu=heap_->GetCPUDescriptorHandleForHeapStart();D3D12_SHADER_RESOURCE_VIEW_DESC sv{};sv.ViewDimension=D3D12_SRV_DIMENSION_BUFFER;sv.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;sv.Format=DXGI_FORMAT_R32_TYPELESS;sv.Buffer.NumElements=(UINT)(bytes/4);sv.Buffer.Flags=D3D12_BUFFER_SRV_FLAG_RAW;d->CreateShaderResourceView(score,&sv,cpu);cpu.ptr+=step;D3D12_UNORDERED_ACCESS_VIEW_DESC uv{};uv.ViewDimension=D3D12_UAV_DIMENSION_BUFFER;uv.Format=DXGI_FORMAT_R32_TYPELESS;uv.Buffer.NumElements=(UINT)(bytes/4);uv.Buffer.Flags=D3D12_BUFFER_UAV_FLAG_RAW;d->CreateUnorderedAccessView(prob,nullptr,&uv,cpu);}
 void Record(ID3D12GraphicsCommandList*c){ID3D12DescriptorHeap*h[]={heap_};c->SetDescriptorHeaps(1,h);c->SetComputeRootSignature(root_);c->SetComputeRootDescriptorTable(0,heap_->GetGPUDescriptorHandleForHeapStart());c->SetPipelineState(pso_);c->Dispatch(540,32,1);}
private:ID3D12RootSignature*root_{};ID3D12PipelineState*pso_{};ID3D12DescriptorHeap*heap_{};
};
