#!/bin/bash
# Regenerates tools/bench-norebuild.ps1 from scripts/bench.ps1: every dxc compile line and its exit check dropped (env + exe only).
cd "$(dirname "$0")/../.."
grep -v '^ *& \$Dxc \|LASTEXITCODE -ne 0' scripts/bench.ps1 | sed 's/^# Builds every shader of the fast chain/# (bench-norebuild: generated by tools\/make-norebuild.sh; no dxc) Builds every shader of the fast chain/' > Development/tools/bench-norebuild.ps1
echo "$(grep -c Dxc Development/tools/bench-norebuild.ps1) dxc refs left"
