#pragma once
#include "native_low_frequency_shader.h"
#include "native_fast_history_support.h"
#include "native_shader_cache.h"
#include <wrl/client.h>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
// Experimental synchronous owner: control/guide reuse waits for the previous
// explicitly submitted consumer. Unknown submission is retained, never freed.
class NativeLowFrequencyTemporal {
 using R=Microsoft::WRL::ComPtr<ID3D12Resource>;
 struct Params{UINT w,h,ph,past,mw,mh,motion,pad;float sx,sy,memory,unused;UINT reserved[4];};
 static_assert(sizeof(Params)==64);
 R difference,observed,observationGuide,control,rawPin,outPin,motionPin;
 std::array<R,2> band,guide;
 Microsoft::WRL::ComPtr<ID3D12RootSignature> root;
 std::array<Microsoft::WRL::ComPtr<ID3D12PipelineState>,3> pipelines;
 Microsoft::WRL::ComPtr<ID3D12DescriptorHeap> heap;
 Microsoft::WRL::ComPtr<ID3D12Fence> fence;
 HANDLE event{};UINT64 retirement{},counter{};UINT w{},h{},ph{},next{};
 bool prior{},pending{},orphan{},lastMotion{},haveTime{},haveId{},enhance{};float enhancementStrength{1};UINT frame{};float exposure{1};Params p{};
 std::chrono::steady_clock::time_point stamp{};
 static R Buffer(ID3D12Device*d,UINT64 bytes,D3D12_HEAP_TYPE type=D3D12_HEAP_TYPE_DEFAULT){R r;D3D12_HEAP_PROPERTIES hp{};hp.Type=type;D3D12_RESOURCE_DESC x{};x.Dimension=D3D12_RESOURCE_DIMENSION_BUFFER;x.Width=bytes;x.Height=x.DepthOrArraySize=x.MipLevels=x.SampleDesc.Count=1;x.Layout=D3D12_TEXTURE_LAYOUT_ROW_MAJOR;x.Flags=type==D3D12_HEAP_TYPE_DEFAULT?D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS:D3D12_RESOURCE_FLAG_NONE;NativeFastHistorySupport::Check(d->CreateCommittedResource(&hp,D3D12_HEAP_FLAG_NONE,&x,type==D3D12_HEAP_TYPE_DEFAULT?D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE:D3D12_RESOURCE_STATE_GENERIC_READ,nullptr,IID_PPV_ARGS(&r)),"low-frequency buffer");return r;}
 void Wait(){if(retirement&&fence->GetCompletedValue()<retirement){NativeFastHistorySupport::Check(fence->SetEventOnCompletion(retirement,event),"low-frequency retirement");if(WaitForSingleObject(event,30000)!=WAIT_OBJECT_0)throw std::runtime_error("low-frequency retirement timeout");}if(fence&&fence->GetCompletedValue()==UINT64_MAX)throw std::runtime_error("low-frequency device removed");}
 void Detach(){difference.Detach();observed.Detach();observationGuide.Detach();control.Detach();rawPin.Detach();outPin.Detach();motionPin.Detach();for(auto&r:band)r.Detach();for(auto&r:guide)r.Detach();root.Detach();for(auto&r:pipelines)r.Detach();heap.Detach();fence.Detach();}
 void Bind(ID3D12GraphicsCommandList*c,ID3D12Resource*raw,ID3D12Resource*out){auto old=next^1;c->SetDescriptorHeaps(1,heap.GetAddressOf());c->SetComputeRootSignature(root.Get());c->SetComputeRootDescriptorTable(0,heap->GetGPUDescriptorHandleForHeapStart());ID3D12Resource*s[]={raw,difference.Get(),observed.Get(),observationGuide.Get(),band[old].Get(),guide[old].Get()};for(UINT i=0;i<6;i++)c->SetComputeRootShaderResourceView(1+i,s[i]->GetGPUVirtualAddress());ID3D12Resource*u[]={difference.Get(),observed.Get(),observationGuide.Get(),band[next].Get(),guide[next].Get(),out};for(UINT i=0;i<6;i++)c->SetComputeRootUnorderedAccessView(7+i,u[i]->GetGPUVirtualAddress());c->SetComputeRootConstantBufferView(13,control->GetGPUVirtualAddress());}
public:
 bool enabled{};
 NativeLowFrequencyTemporal()=default;NativeLowFrequencyTemporal(const NativeLowFrequencyTemporal&)=delete;
 ~NativeLowFrequencyTemporal(){if(!Close()){std::fputs("low-frequency unknown GPU ownership retained\n",stderr);Detach();}if(event)CloseHandle(event);}
 bool Close()noexcept{if(pending||orphan)return false;try{if(enabled)Wait();return true;}catch(...){return false;}}
 bool Pending()const{return pending;}
 void Reset(){prior=false;haveId=false;}
 void CancelUnsubmitted(){if(pending){orphan=true;pending=false;}prior=false;}
 void Create(ID3D12Device*d,UINT width,UINT height,UINT processingHeight,bool enhancement=false,float strength=1.f){enhance=enhancement;enhancementStrength=strength;if(!std::isfinite(strength)||strength<0||strength>2)throw std::runtime_error("enhancement strength");if(enabled||!d||!width||!height||processingHeight<height)throw std::runtime_error("low-frequency initialization");w=width;h=height;ph=processingHeight;UINT64 n=UINT64(w)*h,small=UINT64((w+1)/2)*((h+1)/2);difference=Buffer(d,n*16);observed=Buffer(d,small*8);observationGuide=Buffer(d,small*8);control=Buffer(d,256,D3D12_HEAP_TYPE_UPLOAD);for(auto&r:band)r=Buffer(d,n*8);for(auto&r:guide)r=Buffer(d,n*8);
 D3D12_DESCRIPTOR_RANGE range{D3D12_DESCRIPTOR_RANGE_TYPE_SRV,1,0,0,0};D3D12_ROOT_PARAMETER a[14]{};a[0].ParameterType=D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;a[0].DescriptorTable={1,&range};for(UINT i=0;i<6;i++){a[1+i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_SRV;a[1+i].Descriptor.ShaderRegister=1+i;a[7+i].ParameterType=D3D12_ROOT_PARAMETER_TYPE_UAV;a[7+i].Descriptor.ShaderRegister=i;}a[13].ParameterType=D3D12_ROOT_PARAMETER_TYPE_CBV;D3D12_ROOT_SIGNATURE_DESC rs{14,a,0,nullptr,D3D12_ROOT_SIGNATURE_FLAG_NONE};Microsoft::WRL::ComPtr<ID3DBlob>b,e;NativeFastHistorySupport::Check(D3D12SerializeRootSignature(&rs,D3D_ROOT_SIGNATURE_VERSION_1,&b,&e),"low-frequency root");NativeFastHistorySupport::Check(d->CreateRootSignature(0,b->GetBufferPointer(),b->GetBufferSize(),IID_PPV_ARGS(&root)),"low-frequency root create");const char*entry[]={"Extract","Observe","Update"};for(UINT i=0;i<3;i++){b.Reset();e.Reset();auto hr=NativeCompileShaderBlob(NativeLowFrequencyShader,sizeof(NativeLowFrequencyShader)-1,"IndependentLowFrequency",nullptr,nullptr,entry[i],&b,&e,"cs_5_0");if(FAILED(hr))throw std::runtime_error(e?std::string(static_cast<const char*>(e->GetBufferPointer()),e->GetBufferSize()):"low-frequency shader compile");D3D12_COMPUTE_PIPELINE_STATE_DESC ps{};ps.pRootSignature=root.Get();ps.CS={b->GetBufferPointer(),b->GetBufferSize()};NativeFastHistorySupport::Check(d->CreateComputePipelineState(&ps,IID_PPV_ARGS(&pipelines[i])),"low-frequency PSO");}NativeFastHistorySupport::Check(d->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)),"low-frequency fence");event=CreateEventW(nullptr,FALSE,FALSE,nullptr);if(!event)throw std::runtime_error("low-frequency event");enabled=true;}
 void Prepare(ID3D12CommandQueue*q,UINT id,bool knownId,float exp,bool reset,ID3D12Resource*motion=nullptr,UINT rw=0,UINT rh=0,float scaleX=0,float scaleY=0,bool unjittered=false,double fixtureSeconds=-1){if(!enabled||!q||pending||orphan)throw std::runtime_error("low-frequency pending consumer must retire before reuse");Wait();Microsoft::WRL::ComPtr<ID3D12Device>d;NativeFastHistorySupport::Check(q->GetDevice(IID_PPV_ARGS(&d)),"low-frequency queue device");bool mv=false;if(motion&&unjittered&&rw&&rh){auto desc=motion->GetDesc();mv=!NativeFastHistorySupport::TextureIssue(desc)&&(desc.Format==DXGI_FORMAT_R16G16_FLOAT||desc.Format==DXGI_FORMAT_R32G32_FLOAT)&&desc.Width==rw&&desc.Height==rh&&std::isfinite(scaleX)&&std::isfinite(scaleY);}auto now=std::chrono::steady_clock::now();double seconds=haveTime?std::chrono::duration<double>(now-stamp).count():0;if(fixtureSeconds>=0)seconds=fixtureSeconds;bool cold=reset||!prior||!haveTime||seconds<=0||seconds>.25||!std::isfinite(exp)||exp<=0||exp!=exposure||mv!=lastMotion||(knownId&&haveId&&id!=frame+1);p={w,h,ph,cold?0u:1u,mv?rw:1u,mv?rh:1u,mv?1u:0u,enhance?1u:0u,mv?scaleX/rw*w:0,mv?scaleY/rh*h:0,cold?0.f:float(std::exp(-seconds/.08)),enhancementStrength,{0,0,0,0}};stamp=now;haveTime=true;exposure=exp;frame=id;haveId=knownId;lastMotion=mv;motionPin=mv?motion:nullptr;
 D3D12_DESCRIPTOR_HEAP_DESC hd{D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV,1,D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE,0};heap.Reset();NativeFastHistorySupport::Check(d->CreateDescriptorHeap(&hd,IID_PPV_ARGS(&heap)),"low-frequency guide heap");D3D12_SHADER_RESOURCE_VIEW_DESC view{};view.Format=mv?NativeFastHistorySupport::MotionFormat(motion->GetDesc().Format):DXGI_FORMAT_R32G32_FLOAT;view.ViewDimension=D3D12_SRV_DIMENSION_TEXTURE2D;view.Shader4ComponentMapping=D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;view.Texture2D.MipLevels=1;d->CreateShaderResourceView(mv?motion:nullptr,&view,heap->GetCPUDescriptorHandleForHeapStart());void*data{};D3D12_RANGE none{};NativeFastHistorySupport::Check(control->Map(0,&none,&data),"low-frequency control");memcpy(data,&p,sizeof(p));control->Unmap(0,nullptr);static unsigned logs=0;if(logs++<4)fprintf(stderr,"low-frequency mode%u motion_compensated=%u frame_sequence_observed=%u synchronous_owner=1 work_domain=codec_encoded\n",enhance?3u:2u,unsigned(mv),unsigned(knownId));}
 UINT UsingPast()const{return p.past;}
 void Record(ID3D12GraphicsCommandList*c,ID3D12Resource*raw,ID3D12Resource*out,D3D12_RESOURCE_STATES rawRest=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATES motionRest=D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE){using NativeFastHistorySupport::Transition;if(!enabled||pending||!c||!raw||!out)throw std::runtime_error("low-frequency record");if(raw->GetDesc().Dimension!=D3D12_RESOURCE_DIMENSION_BUFFER||out->GetDesc().Dimension!=D3D12_RESOURCE_DIMENSION_BUFFER||raw->GetDesc().Width<UINT64(w)*ph*16||out->GetDesc().Width<UINT64(w)*ph*12||raw==out)throw std::runtime_error("low-frequency buffer layout/alias");rawPin=raw;outPin=out;Transition(c,raw,rawRest,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);if(motionPin)Transition(c,motionPin.Get(),motionRest,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,0);Transition(c,out,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);Transition(c,difference.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);Bind(c,raw,out);c->SetPipelineState(pipelines[0].Get());c->Dispatch((w+7)/8,(h+7)/8,1);Transition(c,difference.Get(),D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);
 for(auto*r:{observed.Get(),observationGuide.Get()})Transition(c,r,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);c->SetPipelineState(pipelines[1].Get());c->Dispatch(((w+1)/2+7)/8,((h+1)/2+7)/8,1);for(auto*r:{observed.Get(),observationGuide.Get()})Transition(c,r,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);for(auto*r:{band[next].Get(),guide[next].Get()})Transition(c,r,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,D3D12_RESOURCE_STATE_UNORDERED_ACCESS);c->SetPipelineState(pipelines[2].Get());c->Dispatch((w+7)/8,(h+7)/8,1);for(auto*r:{band[next].Get(),guide[next].Get(),out})Transition(c,r,D3D12_RESOURCE_STATE_UNORDERED_ACCESS,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE);if(motionPin)Transition(c,motionPin.Get(),D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,motionRest,0);Transition(c,raw,D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE,rawRest);pending=true;}
 void Submitted(ID3D12CommandQueue*q){if(!pending)throw std::runtime_error("low-frequency no recorded consumer");UINT64 target=++counter;NativeFastHistorySupport::Check(q->Signal(fence.Get(),target),"low-frequency consumer retirement");retirement=target;pending=false;prior=true;next^=1;}
};
